### ISSUE TITLE
tools/build-sdlmixer.sh (macports-based build failure)

### ISSUE THREAD

**Issue by fingon** [kivy/kivy-ios#106]
has hardcoded -I/usr/local/share/aclocal which makes aclocal fail if directory does not exist. I am not sure why it is needed, though, as by default aclocal should have 'system' paths in it's include list already?

If using macports, something like this is needed:

(Probably more elegant thing would be to autodetect existence of the dir and add it to include list if it exists, if it is really needed..)

diff --git a/tools/build-sdlmixer.sh b/tools/build-sdlmixer.sh
index bd884e0..9304eef 100755
--- a/tools/build-sdlmixer.sh
+++ b/tools/build-sdlmixer.sh
@@ -47,7 +47,7 @@ if [ ! -f libtremor/tremor/.libs/libvorbisidec.a ]; then
 	OGG_CFLAGS="-I../../libogg/include" \
 	OGG_LDFLAGS="-L../../libogg/src/.libs" \
 	PKG_CONFIG_LIBDIR="../../libogg" \
-	ACLOCAL_FLAGS="-I $DESTROOT/share/aclocal -I `aclocal --print-ac-dir` -I /usr/local/share/aclocal" ./autogen.sh \
+	ACLOCAL_FLAGS="-I $DESTROOT/share/aclocal -I `aclocal --print-ac-dir`" ./autogen.sh \
 	    --prefix=$DESTROOT \
 		--disable-shared \
 		--host=arm-apple-darwin \

**Comment by tito** [comment]
SDL2* used in the new toolchain doesn't use aclocal anymore, they are using the XCode project inside them. We don't have this issue anymore.
