### ISSUE TITLE
build-kivy.sh fails if kivy already cloned

### ISSUE THREAD

**Issue by Laspimon** [kivy/kivy-ios#113]
**In build-kivy.sh, the script only enters the kivy folder if it is newly cloned, otherwise the script will fail and terminate build-all.sh. This normally wouldn't happen, but if for any reason a previous compile had failed, and you had to rerun the script, you would have to delete and reclone kivy in order to build.**

https://github.com/kivy/kivy-ios/blob/master/tools/build-kivy.sh#L16
> if [ ! -d $TMPROOT/kivy ] ; then
	try pushd $TMPROOT
	try git clone -b $KIVY_BRANCH $KIVY_REPO
	try cd kivy
	try popd

**So if a kivy directiory is already present in $TMPROOT, we wont be entering into it, and thus wont be able to run setup.py:**

https://github.com/kivy/kivy-ios/blob/master/tools/build-kivy.sh#L40
>echo "First build ========================================"
HOSTPYTHON=$TMPROOT/Python-$IOS_PYTHON_VERSION/hostpython
$HOSTPYTHON setup.py build_ext -g
echo "cythoning =========================================="
find . -name *.pyx -exec $KIVYIOSROOT/tools/cythonize.py {} \;
echo "Second build ======================================="
try $HOSTPYTHON setup.py build_ext -g
try $HOSTPYTHON setup.py install -O2 --root iosbuild

**The script will fail with final output:**
>First build ========================================
/Users/Lasper/git/kivy-ios/tmp/Python-2.7.1/hostpython: can't open file 'setup.py': [Errno 2] No such file or directory
cythoning ==========================================
find: properties.pyx: unknown primary or operator
Second build =======================================
/Users/Lasper/git/kivy-ios/tmp/Python-2.7.1/hostpython: can't open file 'setup.py': [Errno 2] No such file or directory

**I suggest moving *try cd kivy* outside of the *if*-clause.**

**Comment by tito** [comment]
New toolchain don't have this issue anymore.
