### ISSUE TITLE
New Toolchains : can't compile 'stdio.h' file not found

### ISSUE THREAD

**Issue by doudz** [kivy/kivy-ios#120]
When running ./toolschain.py build kivy I got the following error :

/Users/seb/kivy-ios/build/freetype/i386/freetype-2.5.5/src/tools/apinames.c:19:10: fatal error: 
      'stdio.h' file not found

I'm running OSX 10.9 with XCode 6.1.1

**Comment by Remolten** [comment]
I had a similar issue.  Look up and install Xcode command line tools to fix this (and make sure Xcode is properly installed).

**Comment by doudz** [comment]
running xcode-select --install fix de problem
sorry for this false issue

**Comment by tito** [comment]
It's not a false issue, thanks for testing!

I'll ensure this liine will appear in the README, and add a FAQ section about it as well.

**Comment by doudz** [comment]
jinja2 is also needed, please add it in the README ;)

**Comment by ryandoherty** [comment]
Just ran into this issue because I was following the instructions on the Kivy site here: https://kivy.org/docs/guide/packaging-ios.html and here https://kivy.org/docs/guide/packaging-ios-prerequisites.html#packaging-ios-prerequisites

Can those get updated too? Thanks!
