### ISSUE TITLE
Audio OGG doesn't work anymore

### ISSUE THREAD

**Issue by tito** [kivy/kivy-ios#121]
Ref: kivy/kivy#3113
##

**Comment by tito** [comment]
It seems that kivy wasn't allow the SDL2 audio loader, which is done now. So it should be fixed.

**Comment by directrix1** [comment]
Still not working here.

**Comment by tito** [comment]
@directrix1 With a fresh clone of kivy-ios ?

**Comment by directrix1** [comment]
Cloned this morning for the first time.

**Comment by tito** [comment]
Thanks for letting us know i'll investigate more.

**Comment by directrix1** [comment]
Converting the files to WAVs, and the app works fine. So it's definitely the ogg loader.

**Comment by bionoid** [comment]
Maybe related to kivy/kivy#3626

**Comment by Zen-CODE** [comment]
Multiple change and upgrade may have addressed this problem? Please retry with a recent checkout and re-raise if the problem persists.
