### ISSUE TITLE
iPhone6 have low-res display

### ISSUE THREAD

**Issue by matafc** [kivy/kivy-ios#123]
I noticed that the new build of the app look really bad. I took some screenshots from the new app to compare from screenshots from a previous build. First two images are the old build, then two from the new build. No code/config was changed on how to display images or fonts between the builds. All images are from the iphone 6 simulator, I can see similar results on a real iphone 5s and iphone 6.

![old1](https://cloud.githubusercontent.com/assets/1737895/6590144/12a9b72a-c769-11e4-96df-626813610302.png)
![old2](https://cloud.githubusercontent.com/assets/1737895/6590145/19d86532-c769-11e4-9ed8-31215e2e2c8e.png)
![toolchain1](https://cloud.githubusercontent.com/assets/1737895/6590149/2076cc8a-c769-11e4-9f9b-df1735b87b90.png)
![toolchain2](https://cloud.githubusercontent.com/assets/1737895/6590150/22c426ea-c769-11e4-8d0f-206c845aedff.png)

**Comment by tito** [comment]
iPhone6 still have issues yes, honestly, i tried to fix it, didn't success yet. It seems to have something about LaunchImage, but the iphone6 is in it. Any help to debug it would be welcomed :)

**Comment by matafc** [comment]
Poking around and doing some research, I suspect that it could be moving from sdl to sdl2 that caused this. Here are some sources that lead me to believe this.
http://forums.libsdl.org/viewtopic.php?t=10877&sid=1a297218cb5e56610254874ab82b87cb
http://stackoverflow.com/questions/26442005/sdl2-retina-display-macbook-blurry-window

And for this issue, it occurs not only the iphone 6, but on any retina ios device.

**Comment by matafc** [comment]
Ok, I now have it pretty much working on my kivy fork of your ios-poly-arch branch here: https://github.com/matafc/kivy/tree/ios-poly-arch

I tested with all simluators and my own devices(iphone 5s, ipad air 2) and they all show up nicely again.There are some concerns I have with what I fixed.

1. I modified the cython sdl2 code to use SDL_GL_GetDrawableSize to set the size in setup_window(). I don't know what other OSes use that sdl2 code, but we can add a USE_IOS flag if necessary.

2. I modified the resize_display_mode() code to do the same, as the SDL_WINDOWEVENT_RESIZED event returns the smaller (scaled) resolution, which kivy uses in window_sdl2.py:_mainloop() to set the size. I had it return the size we get from SDL_GL_GetDrawableSize to set the size in kivy upon resize. Again, we may only want to do this with iOS.

3. I could not trigger the resize_window() function in the cython sdl2 code(_window_sdl2.pyx), so I did not touch it yet, cause I can't test it. If is is used in iOS, then we might be able to do the same thing, assuming all windows in iOS are always supposed to be fullscreen.

4. I cannot remember for sure, but when I worked on my previous release(around Oct 2014) I think the Window.size returned the smaller resolution, even though the assets and fonts were drawn with higher resolutions. This was only for iOS, I think android and desktop builds reported the same resolution as expected. This isn't a problem with most of my application, but it may affect others. In fact, I know I will have to change the way I size my iAd banner with pyobjus, but that should be an easy fix for me.

This also fixed the issue with the iphone 6 plus simluator crashing on start. I haven't tested a real iphone 6 plus, but will let you know the results as soon as I do.

If this issue is resolved, it can also resolve #122

**Comment by tito** [comment]
Could you try to update your repo on the latest master, use the "IF IOS" for theses cases, and make a PR? That would be reallllly appreciated :)

**Comment by matafc** [comment]
So I was able to test on a real iphone 6 plus, and it worked. While updating the code and testing, I found another issue. The setup_window function only sets the orientation to landscape. So I updated the code to start in portrait mode if available. I noticed #125 and I can' recreate the bug with this code, so it could have potentially fixed that as well.

**Comment by matafc** [comment]
Pull request submitted https://github.com/kivy/kivy/pull/3164

**Comment by tito** [comment]
Fixed by the merged PR
