### ISSUE TITLE
pyobjus code crashing on 64 bit devices after using new toolchain

### ISSUE THREAD

**Issue by matafc** [kivy/kivy-ios#124]
First, I am not sure if this should be here or in the pyobjus repo. Since this is what triggered it, and the problem files are in the kivy-ios/build directroy, I decided to start here.

First, the old code worked on all simluators and devices previously. I can replicate crashes on start sometimes with every 64 bit simulator and real device listed. For the simluators, it will sometimes start the app and display the ad, but after rotating a bit it will crash. I have included the errors I have seen so far.

simluator:
  iphone 4s: ok
  iphone 5: ok
  iphone 5s:
    sometimes on start, xcode debugger stops at:

```
      kivy-ios/build/python/x86_64/Python-2.7.1/Modules/gcmodule.c
        gc->gc.gc_refs = Py_REFCNT(FROM_GC(gc));    Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```

or xcode debugger stops at:

```
      kivy-ios/build/python/x86_64/Python-2.7.1/Modules/gcmodule.c
        if (PyObject_IS_GC(op)) { Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```

it will sometimes start, able to toggle ad, then sometimes on rotate, xcode debugger stops at:

```
      kivy-ios/build/sdl2/x86_64/slime73-sdl-experiments-a66a7f7e8cd8/src/video/uikit/SDL_uikitevents.m
        result = CFRunLoopRunInMode(kCFRunLoopDefaultMode, seconds, TRUE);  Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```

  iphone 6:
      same as iphone 5s, but sometimes also see it crash at start with, xcode debugger stops at:

```
      kivy-ios/build/python/x86_64/Python-2.7.1/Modules/gcmodule.c
        _PyObject_GC_UNTRACK(op); Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```

  iphone 6 plus: 
    cannot test, see issue #122 
  ipad 2: ok
  ipad air: same as iphone 5s
  ipad retina: ok

 It seems all 32 bit devices work properly.

Real devices:
  iphone 5s:
      on start always crashes with xcode debugger stopping at:

```
        kivy-ios/build/python/arm64/Python-2.7.1/Objects/listobject.c
          op->ob_item = (PyObject **) PyMem_MALLOC(nbytes); Thread 1: signal SIGABRT
```

xcode log:

```
          kivy-iad-sample(2549,0x1997e5310) malloc: *** error for object 0x17420c320: Invalid pointer dequeued from free list
          *** set a breakpoint in malloc_error_break to debug
          (lldb) 
```

Confirmed removing all pyobjus code allows it to run properly

  ipad air 2: same as real iphone 5s

  I don't have a 32-bit real ios device to test on, I suspect it would work.
##

**Comment by JulienDrecq** [comment]
Hi @matafc , I try to integrate your sample kivy-iad-sample in my kivy app and i meet the same error as you, on all devices. 
At Kivy, Other idea to fix the bug ?

Thank you.
NB: I work with Mac OS X 10.10.3 and Xcode 6.3.

**Comment by matafc** [comment]
Sorry, I haven't made any progress on this. I ended up modifying the main.m for iad banners, and I'll update my sample code when I get a chance. This is probably not the best place for this discussion, you can raise an issue at my repo if you like.

**Comment by tito** [comment]
I remember that i did few fixes for arm64. Do you still hit the issue?

**Comment by Blackbaud-FrankMata** [comment]
I tested latest kivy-ios with iphone 5s and iphone 6, same results.

There may be a new bug, the app will not start at all in iphone 5s ios 7.1. '

````
[INFO              ] [Kivy        ] v1.9.0-dev
[INFO              ] [Python      ] v2.7.1 (r271:86832, Aug 17 2015, 19:52:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[INFO              ] [Factory     ] 173 symbols loaded
[INFO              ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[CRITICAL          ] [Window      ] Unable to find any valuable Window provider at all!
sdl2 - TypeError: setup_window() takes exactly 8 positional arguments (7 given)
  File "/Users/frankie/Library/Developer/CoreSimulator/Devices/DE8A64C0-7087-4E52-9BC6-42D37D062533/data/Applications/E8CF0B54-CB8F-49DB-9AB0-9BC9D2B8D299/hachimaru.app/lib/python2.7/site-packages/kivy/core/__init__.py", line 65, in core_select_lib
    cls = cls()
  File "/Users/frankie/Library/Developer/CoreSimulator/Devices/DE8A64C0-7087-4E52-9BC6-42D37D062533/data/Applications/E8CF0B54-CB8F-49DB-9AB0-9BC9D2B8D299/hachimaru.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 119, in __init__
    super(WindowSDL, self).__init__()
  File "/Users/frankie/Library/Developer/CoreSimulator/Devices/DE8A64C0-7087-4E52-9BC6-42D37D062533/data/Applications/E8CF0B54-CB8F-49DB-9AB0-9BC9D2B8D299/hachimaru.app/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 606, in __init__
    self.create_window()
  File "/Users/frankie/Library/Developer/CoreSimulator/Devices/DE8A64C0-7087-4E52-9BC6-42D37D062533/data/Applications/E8CF0B54-CB8F-49DB-9AB0-9BC9D2B8D299/hachimaru.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 167, in create_window
    resizable)
  File "kivy/core/window/_window_sdl2.pyx", line 23, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:1078)
````

**Comment by satels** [comment]
+1

**Comment by tito** [comment]
@Blackbaud-FrankMata This is not the same bug as discussed in this issue.

**Comment by matafc** [comment]
If you are asking about the new behavior, I understand, I just wanted to
report what I saw. But the main issue still occurred, in the same manner as
first reported.

On Sun, Oct 4, 2015 at 4:42 PM, Mathieu Virbel <notifications@github.com>
wrote:

> @Blackbaud-FrankMata <https://github.com/Blackbaud-FrankMata> This is not
> the same bug as discussed in this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy-ios/issues/124#issuecomment-145402972>.
>



-- 

Frank Mata

Software Engineer

Blackbaud Inc.

https://www.blackbaud.com/

**Comment by satels** [comment]
I raise this bug (EXC_BAD_ACCESS) with code:

Any random line, containing `__setter__` method. For example:

```python
self.bannerView.setDelegate_(self)
```
or

```python
self.bannerView.adUnitID = 'xxx'
```
or 

```python
self.bannerView.rootViewController = rootViewController
```

**Sometimes this code has successful result.**

Full example:

```python
from kivy.core.window import Window
from pyobjus import autoclass, protocol
from pyobjus.objc_py_types import CGRect, CGSize, CGPoint
from kivy.logger import Logger


class AdMobBanner():

        def __init__(self):

            Logger.info('Admob Banner Start init')

            GADBannerView = autoclass('GADBannerView')
            GADRequest = autoclass('GADRequest')

            Logger.info('Admob Banner with GADBannerView and GADRequest')

            rootViewController = autoclass('UIApplication').sharedApplication().keyWindow.rootViewController()
            self.view = rootViewController.view()

            Logger.info('Admob Banner with rootViewController')

            ad_frame = self.get_frame()

            Logger.info('Admob Banner with frame')

            self.bannerView = GADBannerView.alloc().initWithFrame_(ad_frame)

            self.bannerView.adUnitID = 'xxx'

            self.bannerView.rootViewController = rootViewController

            self.bannerView.setDelegate_(self)

            Logger.info('Admob Banner with bannerView')

            self.request = GADRequest.alloc()

            Logger.info('Admob Banner with request')

            self.request.testDevices = ["Simulator",]

            Logger.info('Admob Banner with request testDevices')

            self.bannerView.loadRequest_(self.request)

            Logger.info('Admob Banner with bannerView.loadRequest')

            Window.bind(size=self.win_size_change)

            Logger.info('Admob Banner with Window size change')

        def win_size_change(self, instance, value):
            self.resize()

        def show(self):
            self.view.addSubview_(self.bannerView)

            Logger.info('Admob Banner with banner showed')

        def remove(self):
            self.bannerView.removeFromSuperview()

        def resize(self):
            if self.bannerView.isDescendantOfView_(self.view):
                self.bannerView.setFrame_(self.get_frame())

        def get_frame(self):

            screen = autoclass('UIScreen').mainScreen()

            try:
                scale_factor = screen.nativeScale
            except:
                scale_factor = None

            if scale_factor is None:
                try:
                    scale_factor = screen.scale
                except:
                    scale_factor = 1

            frame_height = 50
            show_offset = frame_height

            ad_center = (0, Window.height/scale_factor - show_offset)

            ad_size = (Window.width/scale_factor, frame_height)

            Logger.info('Admob Banner Frame: scale=%s, center=%s, size=%s', scale_factor, ad_center, ad_size)

            return CGRect(
                CGPoint(*ad_center),
                CGSize(*ad_size))

        @protocol('GADBannerViewDelegate')
        def adViewDidReceiveAd_(self, banner):
            self.resize()

        @protocol('GADBannerViewDelegate')
        def adView_didFailToReceiveAdWithError_(self, banner, error):
            self.resize()

```

**Comment by tito** [comment]
If you can reproduce it partially, or randomly, can you add in your main.m (the objective-c file in xcode, available in Sources > main.m), under all the putenv:

    putenv("PYOBJUS_DEBUG=1");

Then, when you get the segfault, share the whole output from the start of your app. I might be able to reproduce it.

(Please note that i'm owning a 64bit ipad mini retina, i didn't got any crash using Moodstocks, CoreBluetooth, CoreLocation etc)

**Comment by matafc** [comment]
I haven't touched that project in months, but if you want to replicate it,
you can use my demo code.

https://github.com/matafc/hachimaru-blog/tree/master/kivy-iad-sample

BTW, my workaround was to not use pyobjus anymore. So even though this
issue may still exist, it does not affect me anymore.

On Mon, Oct 5, 2015 at 1:07 PM, Mathieu Virbel <notifications@github.com>
wrote:

> If you can reproduce it partially, or randomly, can you add in your main.m
> (the objective-c file in xcode, available in Sources > main.m), under all
> the putenv:
>
> putenv("PYOBJUS_DEBUG=1");
>
> Then, when you get the segfault, share the whole output from the start of
> your app. I might be able to reproduce it.
>
> (Please note that i'm owning a 64bit ipad mini retina, i didn't got any
> crash using Moodstocks, CoreBluetooth, CoreLocation etc)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy/kivy-ios/issues/124#issuecomment-145652819>.
>



-- 

Frank Mata

Software Engineer

Blackbaud Inc.

https://www.blackbaud.com/

**Comment by kollivier** [comment]
I'm seeing this issue too and I've got some output with PYOBJUS_DEBUG, which I've pasted here:

http://pastebin.com/a8d5G8k3

It actually seems to have crashed quite a long time after the line that I added when the problem started occurring. Often when I see a problem like this it is a sign of a threading bug. However, I'm not using threads in my app (yet...).

**Comment by kollivier** [comment]
Also, I've managed to make a minimal sample that shows the problem. 

http://pastebin.com/PSTby68U

To trigger the crash, uncomment the line:

self.configuration.requiresUserActionForMediaPlayback = False

**Comment by AllieCarver** [comment]
OK so I'm trying to integrate AdMob into my app. I had some success already using Pyobjus to link to app store review page by cobbling together a couple of examples and am still hoping to be able to use  Pyobjus instead of trying for an objective-c solution(wholly because I lack objective-c experience) . After finding this thread decided to try @satels implementation as it looked promising.  Exact same situation, the GADBannerView is successful some of the time but will more or less always crash with one of the errors listed by @matafc .  I followed @tito advice, adding `putenv("PYOBJUS_DEBUG=1");` in main.m. 
[log.txt](https://github.com/kivy/kivy-ios/files/762285/log.txt)

I reviewed @kollivier example  and it would seem the common denominator may be initWithFrame?
I can afford to spend another day or two trying to resolve this after which I will have take a closer look at adding via main.m. I will post link to solution regardless of how I manage to get ads working.

**Comment by AllieCarver** [comment]
I'll start with the bad news: I still have absolutely no idea what's causing the crash, largely because I don't know what the fuck I'm doing lol.  But seriously there's a lot of moving pieces here.  I can try to get better familiarized with things a later date and hopefully be of more use. This issue needs someone with the python/C/objective-c skills plus knowledge of the kivy-ios toolchain and pybojus codebase.  

Now the good news is I've managed to integrate Admob using pyobjus. No, really. 

Step 1: Aimlessly flop around for a few of days. 
Step 2: Integrate Admob
Basically all I had to do was write a simple NSObject class to create and toggle ads.  I found an open source sdl project and made use of most of its banner ad class(credited and linked in gist). 

Working sample here - https://gist.github.com/AllieCarver/7c1bce67e9e1b723fa4866c37b61b56a

I did have one other issue I should mention when adding the Google Firebase and AdMob frameworks in xcode. (linker flags are new to me) First follow the instructions to manually add firebase and admob to your xcode project(or the pod method if you know how that works, I don't). Then I had to change the _Other Linker Flags_under the Linking settings,load_all or whatever was default was causing compilation errors, I added the -ObjC flag (as stated in Google docs not actually sure if this was necessary)   -Wl,-no_compact_unwind (this just suppressed some errors, so optional, note that is a " , "  this is all one flag. And finally add -force_load path-to/kivy-ios/dist/lib/libsdl2_ttf.a for all libraries in lib folder.

**Comment by zoltan-fedor** [comment]
Thanks @AllieCarver , I have just followed your working example to make AdMob work in my iOS app.
I was using cocoapods to manage the XCode project's dependencies, so it was relatively easy to integrate the Firebase/AdMob framework, no manual hacking was required.

Below is my Podfile in case anybody is interested:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'YOURAPP' do
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
end
```

One thing for others to remember, that in XCode under Build Settings you have to set "Enable Modules (C and Objective-c)" Yes for @AllieCarver 's working sample (https://gist.github.com/AllieCarver/7c1bce67e9e1b723fa4866c37b61b56a) to compile.

**Comment by AllieCarver** [comment]
@zoltan-fedor awesome advice. Your approach is by far superior, I actually wish I had taken the 5 minutes to learn about cocoapods when I was initially doing this. I ended up needing to use cocoapods to get the Google iOS game services dependencies correct as the instructions for manually including the libraries are just plain wrong and I couldn't manage to resolve all the linker errors myself.
