### ISSUE TITLE
New kivy-ios toolchain, application crashes when portrait orientation is disabled

### ISSUE THREAD

**Issue by zygmuntw** [kivy/kivy-ios#125]
Hi, I never done it before so I'm not sure is it right place to post it, but already posted to stackoverflow and kivy google groups with only answer to report it here so I'm doing it.

I tried to create package for iOS 8.2 using new kivy-ios toolchain on OS X 10.9.5 and 10.10.2 Unfortunately when I disable 'Portrait' orientation in 'Deployment Info' xcode 6.2, application crashes.

Here is output from touchtracer demo:

![2015-03-13_19-20-44](https://cloud.githubusercontent.com/assets/7529725/6645784/412babda-c9b7-11e4-996d-124a650d79db.png)
![2015-03-13_19-19-47](https://cloud.githubusercontent.com/assets/7529725/6645836/93909bd8-c9b7-11e4-842e-dc41038f3f18.png)
![2015-03-13_19-34-42](https://cloud.githubusercontent.com/assets/7529725/6645928/23d030be-c9b8-11e4-9a8b-e0e99308c94d.png)

I have done test on iPhone 5s and iOS symulator, both gave me same results.

It worked fine before, on old kivy-ios toolchain, iOS 8.1 and xcode 6.1

**Comment by tito** [comment]
I got the same too. Unable to understand it yet, i'm on it.

**Comment by tito** [comment]
After publishing 2 app on the store, what i understood is you need launchimage for portrait otherwise it will crash.
