### ISSUE TITLE
OpenSSL Support and Recipes

### ISSUE THREAD

**Issue by mcastle** [kivy/kivy-ios#128]
The latest release of kivy-ios does not include a recipe for OpenSSL nor its libraries libssl or libcrypto. This is required for many applications that require user authentication. Are there plans to provide OpenSSL support? If I want to write a recipe for OpenSSL, which examples and current recipes would serve as good references?

**Comment by johnlsanders** [comment]
(I mentioned this in the kivy users google group, but it's probably more useful here)
I need ssl support, too. Please let me know if someone is working on it, and what I can do to help.
