### ISSUE TITLE
disable_multitouch causes two on_press and on_release events per touch in iOS

### ISSUE THREAD

**Issue by kmonson** [kivy/kivy-ios#129]
Like the title says, if "Config.set('input', 'mouse', 'mouse,disable_multitouch')" is set in a Kivy application it will double trigger touch related events. This behavior does not exist on Windows or Android. I have not tested OSX or Linux.

Tested against Kivy master (retrieved a few weeks ago, about 1 day after the 1.9.0 release) and kivy-ios master.

The follow program demonstrates the problem:

``` python
from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.label import Label
from kivy.uix.floatlayout import FloatLayout
from kivy.config import Config
Config.set('input', 'mouse', 'mouse,disable_multitouch')

class TestApp(App):
    def build(self):
        self.down_count = 0
        self.up_count = 0
        layout = FloatLayout()
        b = Button(text='CLICK ME!',
                   pos_hint={'x': 0.0, 'y':0.0},
                   size_hint=(1.0, 0.5))
        b.bind(on_press=self.touch_down_count)
        b.bind(on_release=self.touch_up_count)
        layout.add_widget(b)

        self.l = Label(text='',
                   pos_hint={'x': 0.0, 'y':0.5},
                   size_hint=(1.0, 0.5))
        layout.add_widget(self.l)
        return layout

    def touch_down_count(self, instance):
        self.down_count += 1
        self.l.text += 'Press down count: {}\n'.format(self.down_count)

    def touch_up_count(self, instance):
        self.up_count += 1
        self.l.text += 'Release count: {}\n'.format(self.up_count)

TestApp().run()
```

Expected: One message per press and release of the button.
Actual: Two messages (and count is incremented twice) per press and release of the button.

Commenting out `Config.set('input', 'mouse', 'mouse,disable_multitouch')` fixes the problem.

Problem exists in both the simulator and on a device. (Thanks for getting the simulator working!)

This also causes other weirdness such as touch events being immediately passed through to the child widgets of scrollable areas.

Thank you for all the work you do on this great framework.
##

**Comment by dessant** [comment]
Tracking at https://github.com/kivy/kivy/issues/3274.
