### ISSUE TITLE
can no longer submit a kivy-ios app to apple store

### ISSUE THREAD

**Issue by niavlys** [kivy/kivy-ios#133]
TL;DR: kivy-ios broken, again...

does anyone tried to upload a kivy-ios app recently, using the new toolchain? by recently, I mean since April 22th...

It looks like something has changed in Apple's codesign process, preventing many projects using 3rd party lib to be built correctly => see SO for former details: http://stackoverflow.com/search?tab=newest&q=ITMS-90035

Kivy seems to be affected too; here's an output of an archive trial:
http://pastebin.com/56tg1QaS

it look like we should/must no longer have executable file into the «Resources » part of the bundle.

**Comment by tito** [comment]
I forgot one step in the new toolchain: clean the installation. Currently, every package install everything (py, pyo, pyc) and don't even clean previous .o. It might fix this.

**Comment by tito** [comment]
So basically, every files with executable bits, or with a shell bang, must be signed.

Now, there is an additionnal step (untested, cause i didn't got time to rebuild everything before pushing the app): before installing to the root/dist, the recipe install is cleaned: extensions like so.libs, so.o, pyc, py, sh, are removed.

Python install-sh is also removed cause it's not needed on the platform.

If you want to fix your submission without rebuilding the whole toolchain, you can strip the unwanted files manually in the dist/root, and then re-generate an archive. (`find -iname '*.pyc' -exec rm {} \;`, and same for others extensions.)

Any files that the submission show can be deleted safely as we don't have any other binary requirement within the package, so none of them are valid.
