### ISSUE TITLE
Kivy-ios creating empty projects

### ISSUE THREAD

**Issue by rfanimation** [kivy/kivy-ios#136]
This one is driving me crazy!  I was succesfully able create XCode projects for several days until something unknown changed and now I just can't.  When I build "touchtracer", for example, I get no errors but the resulting "touchtracer-ios/YourApp" folder contains nothing related to touchtracer- it's all just appears to be the default project stuff (android.txt, README.txt, pictures.kv, shadow32.png, and an images folder containing some sample images.)   This is true of anything I attempt to build, including simple tests and kivy projects that worked fine a few days ago.

What I've tried:
I've reinstalled everything, including Python, Kivy, all dependencies, and kivy-ios itself.  At first I couldn't get "./toolchain.py build kivy" to work (it was giving the error "NameError: global name 'ios_build' is not defined", but then I changed line 820 in ./toolchain.py to "self.remove_junk(iosbuild)" and it succesfully built.  But it hasn't changed anything - still getting empty ios projects.

Please help, this is driving me crazy!

Here's the Terminal output of a sample attempt to build the Touchtracer demo:

```
server:kivy-ios robertfield$ ./toolchain.py create touchtracer ./touchtracer

Global: hostpython located at /Users/robertfield/kivy-ios/dist/hostpython/bin/python
Global: hostpgen located at /Users/robertfield/kivy-ios/dist/hostpython/bin/pgen
----------------------------------------------------------------------
The project need to have:
iOS Frameworks: ['AudioToolbox', 'ImageIO', 'MessageUI', 'UIKit', 'OpenGLES', 'CoreMotion', 'MobileCoreServices', 'CoreGraphics', 'Accelerate', 'QuartzCore']
iOS Libraries: ['libc++', 'libz', 'libsqlite3', 'libbz2']
iOS local Frameworks: []
Libraries: ['/Users/robertfield/kivy-ios/dist/lib/libios.a', '/Users/robertfield/kivy-ios/dist/lib/libsdl2_ttf.a', '/Users/robertfield/kivy-ios/dist/lib/libkivy.a', '/Users/robertfield/kivy-ios/dist/lib/libffi.a', '/Users/robertfield/kivy-ios/dist/lib/libsdl2.a', '/Users/robertfield/kivy-ios/dist/lib/libsdl2_image.a', '/Users/robertfield/kivy-ios/dist/lib/libsdl2_mixer.a', '/Users/robertfield/kivy-ios/dist/lib/libfreetype.a', '/Users/robertfield/kivy-ios/dist/lib/libpython.a']
Sources to link: []
----------------------------------------------------------------------
Analysis of /Users/robertfield/kivy-ios/touchtracer-ios/touchtracer.xcodeproj/project.pbxproj
Ensure AudioToolbox is in the project (system)
Ensure ImageIO is in the project (system)
Ensure MessageUI is in the project (system)
Ensure UIKit is in the project (system)
Ensure OpenGLES is in the project (system)
Ensure CoreMotion is in the project (system)
Ensure MobileCoreServices is in the project (system)
Ensure CoreGraphics is in the project (system)
Ensure Accelerate is in the project (system)
Ensure QuartzCore is in the project (system)
Ensure libc++ is in the project
Ensure libz is in the project
Ensure libsqlite3 is in the project
Ensure libbz2 is in the project
Ensure /Users/robertfield/kivy-ios/dist/lib/libios.a is in the project
Ensure /Users/robertfield/kivy-ios/dist/lib/libsdl2_ttf.a is in the project
Ensure /Users/robertfield/kivy-ios/dist/lib/libkivy.a is in the project
Ensure /Users/robertfield/kivy-ios/dist/lib/libffi.a is in the project
Ensure /Users/robertfield/kivy-ios/dist/lib/libsdl2.a is in the project
Ensure /Users/robertfield/kivy-ios/dist/lib/libsdl2_image.a is in the project
Ensure /Users/robertfield/kivy-ios/dist/lib/libsdl2_mixer.a is in the project
Ensure /Users/robertfield/kivy-ios/dist/lib/libfreetype.a is in the project
Ensure /Users/robertfield/kivy-ios/dist/lib/libpython.a is in the project
--
Project directory : touchtracer-ios
XCode project     : touchtracer-ios/touchtracer.xcodeproj
```
##

**Comment by tito** [comment]
Did you try putting a full absolute path instead of a relative ./touchtracer ?

**Comment by ForeverWintr** [comment]
For future readers: I encountered this issue when providing the wrong path to my kivy project. For example, I provided the path to the parent directory of my `main.py` entry point, rather than the directory containing `main.py`.

**Comment by Zen-CODE** [comment]
Correct. This behavior is explainable by an incorrect path.

@rfanimation. Please re-open if you still have this issue and can confirm your path to the project is the valid containing folder.
