### ISSUE TITLE
./toolchain.py build kivy big error

### ISSUE THREAD

**Issue by liubobo** [kivy/kivy-ios#152]
./toolchain.py build kivy
Want to build ['kivy']
Loaded recipe kivy (depends of ['python', 'sdl2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'ios'])
Loaded recipe python (depends of ['hostpython', 'libffi'])
Loaded recipe sdl2 (depends of [])
Loaded recipe sdl2_image (depends of ['sdl2'])
Loaded recipe sdl2_mixer (depends of ['sdl2'])
Loaded recipe sdl2_ttf (depends of ['sdl2', 'freetype'])
Loaded recipe ios (depends of ['python'])
Loaded recipe hostpython (depends of ['libffi'])
Loaded recipe libffi (depends of [])
Loaded recipe freetype (depends of [])
Build order is ['freetype', 'libffi', 'sdl2', 'hostpython', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python', 'ios', 'kivy']
Global: hostpython located at /Users/liubo/Desktop/os/kivy-ios/dist/hostpython/bin/python
Global: hostpgen located at /Users/liubo/Desktop/os/kivy-ios/dist/hostpython/bin/pgen
Download freetype
Traceback (most recent call last):
  File "./toolchain.py", line 1160, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1023, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1037, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 918, in build_recipes
    recipe.execute()
  File "/Users/liubo/Desktop/os/kivy-ios/toolchain.py", line 550, in execute
    self.download()
  File "/Users/liubo/Desktop/os/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/liubo/Desktop/os/kivy-ios/toolchain.py", line 579, in download
    self.ctx.state[key] = self.get_archive_rootdir(self.archive_fn)
  File "/Users/liubo/Desktop/os/kivy-ios/toolchain.py", line 416, in get_archive_rootdir
    archive = tarfile.open(filename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

**Comment by Zen-CODE** [comment]
I get this same issue. Mac OSX 10.9.

**Comment by Zen-CODE** [comment]
After investigating, turns our this file is not a valid archive:
    Opening  /Users/X/Documents/kivy-ios/kivy-ios/.cache/sdl2_mixer-SDL2_mixer-2.0.0.tar.gz

Still the same after running a "git clean -dxf' in the kivy-ios folder and re-running. Will investigate and post again.

**Comment by Zen-CODE** [comment]
Going to be bold and close. The above merge should solve this issue: difficult to test other downloads without being able to replicate. Please re-open if the problems persists. :-)
