### ISSUE TITLE
Audio/Video provider conflict

### ISSUE THREAD

**Issue by niavlys** [kivy/kivy-ios#156]
hi folks,
Since last commits on ffmpeg, i'm finally able to compile ffpyplayer for ios, which is cool ;)
but,
it looks like the audio and video provider (resp. audio_sdl2 and ffpyplayer) are somewhere conflicting : 
Use case snippet

``` python
import kivy
from kivy.app import App

from kivy.core.audio import SoundLoader
from kivy.uix.video import Video

class VideoPlayerApp(App):

    def build(self):
        s=SoundLoader.load('plop.wav')
        #NOTE: the sound is just loaded, not played...
        v = Video(allow_stretch=True,source='cut.mp4')
        v.state='play'
        return v

if __name__ == '__main__':
    VideoPlayerApp().run()
```

with a correctly (h264/aac) encoded video and a random sound file that is just loaded, not played.
the result is that the video is played without its embedded sound, and the logs exhibits the following error

```
[INFO              ] [Kivy        ] v1.9.1-dev
[INFO              ] [Python      ] v2.7.1 (r271:86832, Jun 29 2015, 09:50:33) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
[INFO              ] [Factory     ] 176 symbols loaded
[INFO              ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)
[INFO              ] [Audio       ] Providers: audio_sdl2 (audio_avplayer, audio_pygst, audio_ffpyplayer ignored)
[INFO              ] [VideoFFPy   ] Using ffpyplayer 3.2-dev
[INFO              ] [Video       ] Provider: ffpyplayer(['video_pygst', 'video_ffmpeg'] ignored)
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] OpenGL version <OpenGL ES 2.0 Apple A7 GPU - 50.6.11>
[INFO              ] [GL          ] OpenGL vendor <Apple Inc.>
[INFO              ] [GL          ] OpenGL renderer <Apple A7 GPU>
[INFO              ] [GL          ] OpenGL parsed version: 2, 0
[INFO              ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO              ] [GL          ] Texture max size <4096>
[INFO              ] [GL          ] Texture max units <8>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Base        ] Start application main loop
[WARNING           ] [ffpyplayer  ] SDL_OpenAudio (1 channels): Audio device is already opened
[ERROR             ] [ffpyplayer  ] No more channel combinations to try, audio open failed
```

It seems that the audio provider preempts the resource, thus preventing the video to use it. If I don't load the sound, the video is working perfectly...

Setting KIVY AUDIO doesn't help, and the above code works fine on desktop and android (but this may not be relevant as it's using different combinations of provider...)

my build env:
macosx 10.9.5 , xcode 6.2, cython 0.20.2, kivy & kivy-ios master
##

**Comment by niavlys** [comment]
well, I've seen afterwards:

https://github.com/kivy/kivy/blob/master/kivy/core/audio/audio_sdl2.pyx#L6
:s/might/does/g ;(

according to https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.pdf , one shouldn't mix SDL_OpenAudio and MIX_OpenAudio calls.

So, it seems to be a ffpyplayer issue ?

(heads-up @matham , any opinion? )

**Comment by rammie** [comment]
I ran into the same issue, I was wondering if there was any progress on this or a workaround.

**Comment by Zen-CODE** [comment]
Multiple change and upgrade may have addressed this problem? Please retry with a recent checkout and re-raise if the problem persists.
