### ISSUE TITLE
Big problem toolchain OS X 10.11 GM and Xcode 7

### ISSUE THREAD

**Issue by LucaInfante** [kivy/kivy-ios#163]
Goodmorning everyone. I'm new to Python and Kivy (come from other languages) and I would have some problems.

Kivy-ios can not be building on OS X 10.11 GM and Xcode 7. Fails written by the same procedure as in the other thread (https://github.com/kivy/kivy-ios/issues/162).

Downloading Xcode 6.4 (always on OS X 10.11 GM) can fill and I can create the Xcode project. When launching the project Xcode tells me that missing "pygments". In this thread https://github.com/kivy/kivy-ios/issues/88 wrote "Yes, pygments is a dependency not included by default, you need to add it When building the toolchain.".

I did not understand how to do it. Help me with an example?

**Comment by LucaInfante** [comment]
Thanks and sorry for my bad english!

I have need ASAP :-(

**Comment by D-Cipher** [comment]
I had a lot problems with the build and I got it to work, I posted a guide to the build detailing some of the stumbling blocks I found here:
https://goo.gl/swR2L5

This might be helpful.

**Comment by rammie** [comment]
I'm not sure that this is true. I was able to build with the latest xcode (7.2), command line tools, and OSX 10.11.2 without issues. I had to add a perl script to my path to build ffmpeg, but other than that it worked like a charm. I've successfully built kivy, ffpyplayer, ffmpeg, and pyobjus following the instructions. The perl script I installed was gas-preprocessor.pl (taken from https://github.com/ffmpeg/gas-preprocessor). It should have executable permissions. That should probably be added to the ffmpeg recipe, or to the build instructions.

**Comment by JMSwag** [comment]
I can confirm what @rammie said

**Comment by ryandoherty** [comment]
For pygments, I had to manually copy the pygments directory from the Kivy.app to my app's source directory like so:

`cp -R /Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/pygments .`

Kivy docs are lacking and the maintainer's responses are often very vague and unhelpful.

**Comment by kived** [comment]
#162 has been resolved, and I have no issues building with Xcode 7.3. As for adding pure-Python modules and packages, like pygments, you can just add them into your project, next to your main.py file. That folder will be on the PYTHONPATH of your app. You can also use [buildozer](https://github.com/kivy/buildozer), which can handle installing pure-Python packages into your app via pip, instead of using kivy-ios directly.
