### ISSUE TITLE
Cannot build pil in latest

### ISSUE THREAD

**Issue by gorgonaut04** [kivy/kivy-ios#171]
I've had a few different, seemingly similar building problems. First, `plyer` wouldn't build after building some other packages, but it would build if i built it first (similar to issue #127). Now, I can't get `pil` to build at all, even if I run `distclean` then `build plyer` (of course I understand this is after the prereqs have been built. Anyway, are there any work-arounds that will get me a working `pil` packages, or is it currently broken?

Here's the error:

```
    Download host_setuptools
    Extract host_setuptools
    Extract host_setuptools for i386
    Build_all host_setuptools
    Build host_setuptools for i386 (filtered)
    Build host_setuptools
    Prebuild host_setuptools for i386
    Could not find platform dependent libraries <exec_prefix>
    Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
    Traceback (most recent call last):
      File "./ez_setup.py", line 415, in <module>
        sys.exit(main())
      File "./ez_setup.py", line 411, in main
        archive = download_setuptools(**_download_args(options))
      File "./ez_setup.py", line 327, in download_setuptools
        version = _resolve_version(version)
      File "./ez_setup.py", line 347, in _resolve_version
        resp = urlopen('https://pypi.python.org/pypi/setuptools/json')
      File "/Users/mac/kivy-ios/dist/hostpython/lib/python2.7/urllib2.py", line 126, in urlopen
        return _opener.open(url, data, timeout)
      File "/Users/mac/kivy-ios/dist/hostpython/lib/python2.7/urllib2.py", line 392, in open
        response = self._open(req, data)
      File "/Users/mac/kivy-ios/dist/hostpython/lib/python2.7/urllib2.py", line 415, in _open
        'unknown_open', req)
      File "/Users/mac/kivy-ios/dist/hostpython/lib/python2.7/urllib2.py", line 370, in _call_chain
        result = func(*args)
      File "/Users/mac/kivy-ios/dist/hostpython/lib/python2.7/urllib2.py", line 1219, in unknown_open
        raise URLError('unknown url type: %s' % type)
    urllib2.URLError: <urlopen error unknown url type: https>
    Traceback (most recent call last):
      File "./toolchain.py", line 1225, in <module>
        ToolchainCL()
      File "./toolchain.py", line 1041, in __init__
        getattr(self, args.command)()
      File "./toolchain.py", line 1065, in build
        build_recipes(args.recipe, ctx)
      File "./toolchain.py", line 934, in build_recipes
        recipe.execute()
      File "/Users/mac/kivy-ios/toolchain.py", line 557, in execute
        self.build_all()
      File "/Users/mac/kivy-ios/toolchain.py", line 56, in _cache_execution
        f(self, *args, **kwargs)
      File "/Users/mac/kivy-ios/toolchain.py", line 644, in build_all
        self.build(arch)
      File "/Users/mac/kivy-ios/toolchain.py", line 56, in _cache_execution
        f(self, *args, **kwargs)
      File "/Users/mac/kivy-ios/toolchain.py", line 629, in build
        self.prebuild_arch(arch)
      File "/Users/mac/kivy-ios/recipes/host_setuptools/__init__.py", line 17, in prebuild_arch
        shprint(hostpython, "./ez_setup.py")
      File "/Users/mac/kivy-ios/toolchain.py", line 39, in shprint
        for line in command(*args, **kwargs):
      File "./tools/external/sh.py", line 565, in next
        self.wait()
      File "./tools/external/sh.py", line 500, in wait
        self.handle_command_exit_code(exit_code)
      File "./tools/external/sh.py", line 516, in handle_command_exit_code
        raise exc(self.ran, self.process.stdout, self.process.stderr)
    sh.ErrorReturnCode_1: 

      RAN: '/Users/mac/kivy-ios/dist/hostpython/bin/python ./ez_setup.py'

      STDOUT:
    Could not find platform dependent libraries <exec_prefix>
    Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
    Traceback (most recent call last):
      File "./ez_setup.py", line 415, in <module>
        sys.exit(main())
      File "./ez_setup.py", line 411, in main
        archive = download_setuptools(**_download_args(options))
      File "./ez_setup.py", line 327, in download_setuptools
        version = _resolve_version(version)
      File "./ez_setup.py", line 347, in _resolve_version
        resp = urlopen('https://pypi.python.org/pypi/setuptools/json')
      File "/Users/mac/kivy-ios/dist/hostpython/lib/python2.7/urllib2.py", line 126, in urlopen
        return _opener.open(url, data, timeout)
      File "/Users/mac/kivy-ios/dist/hostpython/lib/python2.7/urllib2.py", line ... (492 more, please see e.stdout)

      STDERR:
```

edit to better use markdown
##

**Comment by gorgonaut04** [comment]
Okay that problem was related to the hostpython not supporting https, which is needed to download setuptools. I have hacked urllib2.urlopen so that it returns a fd to a local version of the remote setuptools.json whenever that link is sent as an argument. But now I have a new problem with Pil. The "biglink" operation is warning that no files are selected to be added to "libpil.a", even though there are a few .so.lib files for each arch. I can't see a reason why, unless the wrong directory is being fed to os.walk? Unfortunately this warning is only printed the first time you run ./toolchain.py build pil. After this, the toolchain believes the build is already complete, but the libpil.a file wasn't created, so it fails to find it and fails immediately for that reason. So I haven't yet added any prints to try to diagnose the problem.

**Comment by lukaszzenko** [comment]
I have an exactly same problem.
@gorgonaut04 Have you been able to solve this issue?

**Comment by gorgonaut04** [comment]
No

**Comment by lukaszzenko** [comment]
I was able to find a walkaround and compile PIL.

I tweaked `_resolve_version` in `host_setuptools/ez_setup.py` to return hard-coded constant value, instead of getting it dynamically from https://pypi.python.org/pypi/setuptools/json.

I also needed to modify recipe `recipes/host_setuptools/__init__.py`, so it doesn't download `ez_setup.py`, but uses the local version.

**Comment by jahammons** [comment]
@lkaszenko suggestions worked.  I also created ModulesSetup.openssl and edited __ini__.py in recipes/hostpython, as posted by @cbenhagen . However, the build crashes because libpil.a was not created. Has anyone figured out a way to build pil yet? Below is the error:  fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/xxx/Documents/kivy-ios/build/pil/i386/Pillow-2.8.2/libpil.a (No such file or directory)

**Comment by gorgonaut04** [comment]
Thanks @lukaszzenko! I was eventually able to build using this advice, but ran into additional problems in the post-build process. This really needs to be cleaned up by someone with more knowledge of how the kivy-ios recipe build process works!

Anyway if others have the same trouble, search for libpil.a in kivy-ios/build using the Finder. You will see one version of the file that is larger than the rest (1.7 MB on my mac). This is the one that has all architectures integrated within it. Copy this to the same directory that has your xcode project's other "*.a" files

Now install PIL 2.8.2 to your local python installation using pip. Find your local site-packages directory that contains this PIL sub-directory. Copy this folder into kivy-ios/dist/root/.../site-packages (sorry don't have the mac in front of me, but you should be able to find it). Most importantly now, you MUST replace all five "*.so" files in this PIL directory with *empty files of the same name*. Otherwise Apple won't let you upload your app to the app store. I believe the data from these .so files is already packed into libpil.a

**Comment by filipefigcorreia** [comment]
I'm using the patch provided by @cbenhagen, but my build is still failing with the error `urllib2.URLError: <urlopen error unknown url type: https>`. 

Is there something that I have missed doing? I'm creating a recipe; do I need to say explicitly somewhere that the hostpython in my recipe needs to have openssl support?

**Comment by gorgonaut04** [comment]
I just had this issue in another context. Looks like there are two entirely separate causes:
- ":" in url: http://stackoverflow.com/questions/27115803/urllib-error-urlerror-urlopen-error-unknown-url-type-https
- Whatever python is having the error doesn't have SSL support: http://stackoverflow.com/questions/28376506/python-and-urllib-https-request-urlopen-error-unknown-url-type-https

**Comment by Zen-CODE** [comment]
@gorgonaut04. Is this still an issue? Did you manage to resolve it?

**Comment by Zen-CODE** [comment]
The latest PIL recipe seems fully functional. Please try that and re-open if not.
