### ISSUE TITLE
Failed build kivy

### ISSUE THREAD

**Issue by AtsushiSakai** [kivy/kivy-ios#175]
I do:
$ ./toolchain.py build kivy

Then, there is an error when it download freetype.

Python 2.7.10
OSX 10.10.5

This is error message:

Want to build ['kivy']
Loaded recipe kivy (depends of ['python', 'sdl2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'ios'], optional are [])
Loaded recipe python (depends of ['hostpython', 'libffi'], optional are ['openssl'])
Loaded recipe sdl2 (depends of [], optional are [])
Loaded recipe sdl2_image (depends of ['sdl2'], optional are [])
Loaded recipe sdl2_mixer (depends of ['sdl2'], optional are [])
Loaded recipe sdl2_ttf (depends of ['sdl2', 'freetype'], optional are [])
Loaded recipe ios (depends of ['python'], optional are [])
Loaded recipe hostpython (depends of ['hostlibffi'], optional are [])
Loaded recipe libffi (depends of [], optional are [])
Loaded recipe freetype (depends of [], optional are [])
Loaded recipe hostlibffi (depends of [], optional are [])
Build order is ['freetype', 'hostlibffi', 'libffi', 'sdl2', 'hostpython', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python', 'ios', 'kivy']
Include dir added: {arch.arch}/freetype
Include dir added: {arch.arch}/hostlibffi
Include dir added: {arch.arch}/libffi
Include dir added: common/sdl2
Global: hostpython located at /Users/AtsushiSakai/Dropbox/Program/python/kivy/kivy-ios/dist/hostpython/bin/python
Global: hostpgen located at /Users/AtsushiSakai/Dropbox/Program/python/kivy/kivy-ios/dist/hostpython/bin/pgen
Include dir added: common/sdl2_image
Include dir added: common/sdl2_mixer
Include dir added: common/sdl2_ttf
Download freetype
Downloading http://download.savannah.gnu.org/releases/freetype/freetype-2.5.5.tar.bz2
Traceback (most recent call last):
IOError: [Errno socket error] [Errno 60] Operation timed out

**Comment by Zen-CODE** [comment]
That seems like a simple connection issue. Are you able to manually download the file?

http://download.savannah.gnu.org/releases/freetype/freetype-2.5.5.tar.bz2
