### ISSUE TITLE
The documentation needs to be complemented

### ISSUE THREAD

**Issue by andong777** [kivy/kivy-ios#180]
Currently the documentation of kivy-ios is very brief, and lacks some content included in p4a.
At first, I was confused about recipe, until I found it is documented in p4a.
Such things should be added, or two projects can share content if possible.
##

**Comment by Zen-CODE** [comment]
@inclement 

The point here about recipes is very valid. We needs docs explaining the difference between iOS and Android recipes and then a pointer back to the python-for-android recipes docs.

We want to avoid duplication wherever possible, so perhaps a concise explanation of the iOS differences and considerations and a link to p4a docs? I'm willing to do the docs, but have little knowledge in this area. Where can I find out about these differences?

**Comment by inclement** [comment]
I wouldn't worry about duplication, python-for-android and kivy-ios are
basically completely separate projects. Although the Recipe system has
the same basic structure, they're mostly quite different and I think it
will normally be more confusing than helpful to draw connections between
the projects.

**Comment by Zen-CODE** [comment]
PR's welcome
