### ISSUE TITLE
Command line tools error

### ISSUE THREAD

**Issue by jredd** [kivy/kivy-ios#181]
When building kivy-ios the build needs command line tools installed... Be nice if the documentation actually said something about that...

**Comment by kived** [comment]
https://github.com/kivy/kivy-ios#requirements

1. Xcode 6 or above, with an iOS SDK and command line tools installed:

`xcode-select --install`

**Comment by jredd** [comment]
I'm going off of this post 

https://kivy.org/docs/guide/packaging-ios.html
