### ISSUE TITLE
Black screen on iPad

### ISSUE THREAD

**Issue by wawachief** [kivy/kivy-ios#183]
I have a problem when I try to launch a ivy program on iPad : the screen is black and the app doesn't shows up. On the simulator, everything works just fine.

I Use Xcode 7.3 on osx 10.11.4 and iOS 9.3.1 on iPad air

Here is the console output.

Thanks for your help.

2016-04-09 09:54:54.960 showfactor[348:40202] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2016-04-09 09:54:54.962 showfactor[348:40202] PythonHome is: /var/containers/Bundle/Application/DCDD94C9-A619-45AF-88D7-0B50F97DABD0/showfactor.app
2016-04-09 09:54:54.964 showfactor[348:40202] Initializing python
2016-04-09 09:54:55.085 showfactor[348:40202] Running main.pyo: /var/containers/Bundle/Application/DCDD94C9-A619-45AF-88D7-0B50F97DABD0/showfactor.app/YourApp/main.pyo
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.1 (r271:86832, Apr  9 2016, 09:18:38) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] OpenGL version <OpenGL ES 2.0 Apple A7 GPU - 77.14>
[INFO              ] [GL          ] OpenGL vendor <Apple Inc.>
[INFO              ] [GL          ] OpenGL renderer <Apple A7 GPU>
[INFO              ] [GL          ] OpenGL parsed version: 2, 0
[INFO              ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO              ] [GL          ] Texture max size <4096>
[INFO              ] [GL          ] Texture max units <8>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Base        ] Start application main loop

**Comment by Zen-CODE** [comment]
Please can you post the app code so we can try and reproduce it.

**Comment by wawachief** [comment]
Thank you for taking my problem into consideration. Here is the files : 
- showfactor.zip is the kivy source project
- showfactor-ios.zip is the generated Xcode project

[showfactor.zip](https://github.com/kivy/kivy-ios/files/216431/showfactor.zip)
[showfactor-ios.zip](https://github.com/kivy/kivy-ios/files/216432/showfactor-ios.zip)

**Comment by wawachief** [comment]
I found the problem : it was the .kv name which was not lowercased. I renamed testKivy.kv into testkivy.kv and now it is working.

**Comment by Zen-CODE** [comment]
Awesome. Glad you're sorted :-)
