### ISSUE TITLE
'Supported orientations has no common orientation' crash on iPhone  [$100]

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/kivy-ios#195]
'Supported orientations has no common orientation' crash on iPhone. On iPad/iPad2, all is fine.

Running XCode 7.2 on MacOSX 10.10.5, using the latest kivy-ios checkout as of today.

This problem only occurs on iPhones (phones and simulators). All works if you use all orientations, but if you restrict it to landscape only, it crashes with this error:

2016-05-27 15:21:43.167 cami-apps[32335:240418] *** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [SDLLaunchScreenController shouldAutorotate] is returning YES'

Full log here: https://gist.github.com/Zen-CODE/81c0128752706ac5115169016c8f9142

The app crashes at lin 60 of SDL_uikitappdelegate.m

    UIApplicationMain(argc, argv, nil, [SDLUIKitDelegate getAppDelegateClassName]);

![iphone6 crash](https://cloud.githubusercontent.com/assets/3539755/15609877/b30a154a-2422-11e6-9868-68d393a9a341.png)

Any ideas on how to fix?

**Comment by evbo** [comment]
Each time you use kivy-ios toolchain to create a project, it automatically starts you off with a `main.m` file in your sources folder. This `main.m` file does a few important things, including communicating the available device orientations through an environment variable called `KIVY_ORIENTATION`. Setting this environment variable to only the orientations you prefer is the key to solving this problem:

```
// on line 93 in main.m, I specify I only want landscape mode (home button on right)
NSString *result = [[NSString alloc] initWithString:@"KIVY_ORIENTATION=LandscapeRight"
```

First, ensure that your [your app name]-info.plist matches the default provided (when a new kivy-ios project is created). It should, by default, contain all orientations. You never should disable them, as it will cause the error you experienced. Think of that .plist file as describing all _possible_ orientations for devices - not the preferred orientations.

Next, open the `main.m` and proceed to line 93 where you can specify your preferred orientations. By default, it tries to include all orientations. Here is an example of setting the orientations only to landscape:


```
// This method read available orientations from the Info.plist, and share them
// in an environment variable. Kivy will automatically set the orientation
// according to this environment value, if exist.
void export_orientation() {
    NSDictionary *info = [[NSBundle mainBundle] infoDictionary];
    NSArray *orientations = [info objectForKey:@"UISupportedInterfaceOrientations"];
    // here is all it takes to enforce landscape modes!
    NSString *result = [[NSString alloc] initWithString:@"KIVY_ORIENTATION=LandscapeLeft LandscapeRight"];
// here is what main.m did before - reading all possible orientations from the plist:
//    for (int i = 0; i < [orientations count]; i++) {
//        NSString *item = [orientations objectAtIndex:i];
//        item = [item substringFromIndex:22];
//        if (i > 0) {
//            result = [result stringByAppendingString:@" "];
//        }
//        result = [result stringByAppendingString:item];
//    }
```

The importance of that code sample is that I commented out the for loop that normally gathers all possible orientations, and instead I simply specified a string literal. Here is what that string literal would look like if you wanted to include all orientations (simply remove modes you wish not to include from this example):

`NSString *result = [[NSString alloc] initWithString:@"KIVY_ORIENTATION=LandscapeRight Portrait LandscapeLeft PortraitUpsideDown"`

**Comment by Zen-CODE** [comment]
@evbo
Thanks for the post, but changing the main.m as suggested makes to difference. My plist file has the following:

	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>

But I have not changed this directly, only but selecting the tickboxes in the 'Device Orientation' section in the XCode 'General -> Deployment Info' window.

Keep in mind that it works fine for the iPad, it's only in the iPhone that it breaks. So the issue must be related to some difference in the way they handle orientation...

**Comment by Zen-CODE** [comment]
@evbo. You're a hero. After re-reading your post, I selected all orientations in XCode and it now works. My plist is now.

	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>

**Comment by Zen-CODE** [comment]
@evbo. Please claim your bounty

**Comment by Zen-CODE** [comment]
@evbo. Still waiting for your claim. Really, we want to pay you, but if you don't claim  by the end of this month, we will award it to other kivy devs....

**Comment by evbo** [comment]
I accepted the bounty on the "bounty source" website. Should I have done it a different way?

**Comment by Zen-CODE** [comment]
No, probably not. This is my first time on the 'payee' side. I have
received a bountysource payment, but never given one. So please be patient
during this process whilst I figure this out :-)

On Wed, Jul 13, 2016 at 2:35 PM, evbo <notifications@github.com> wrote:

> I accepted the bounty on the "bounty source" website. Should I have done
> it a different way?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/kivy/kivy-ios/issues/195#issuecomment-232341517>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ADYDK1QZwXmL9E_Ofkv4fbs2L4pkss89ks5qVNt9gaJpZM4IohTD>
> .
>



-- 
===============
ZenKEY - Become one.
http://www.camiweb.com/zenkey

**Comment by evbo** [comment]
no problem, and thank you!
