### ISSUE TITLE
does this library support ios bluetooth frameworks?

### ISSUE THREAD

**Issue by evbo** [kivy/kivy-ios#197]

**Comment by Zen-CODE** [comment]
Hi

This is more of a question than a ticket, but in short, not yet.

https://github.com/kivy/plyer/issues/153

Of course, you can use PyObjus to create your own Python wrapper around the native iOS BlueTooth API, but I don't think anyone has completed a usable implementation yet. The above link is probably the best place to follow up.

Thanks
