### ISSUE TITLE
toolchain build error！

### ISSUE THREAD

**Issue by koalahl** [kivy/kivy-ios#199]
hi，first use this tool.  everything according to README. 
In the  build step,this error  always  happened .

![1e64fe7b-5387-44cb-af5a-74f2bfed87dc](https://cloud.githubusercontent.com/assets/16068616/16370308/2ac201a4-3c71-11e6-89fe-a8a44d444269.png)
##

**Comment by koalahl** [comment]
Mac OS X: 10.11.5

**Comment by Zen-CODE** [comment]
When did you last update your kivy-ios checkout? Your log output does not seem to match. Please try pulling the latest and see if that helps?

This error is usually when it is unable to download properly, either to a dropped connection or a firewall issue. Try a "./toolchain.py distclean" before building again....

**Comment by Zen-CODE** [comment]
Closing the issue. This may well have been fixed. If you still get the issue, please re-open with the complete log file.
