### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by rockeen** [kivy/kivy-ios#200]
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23

**Comment by Zen-CODE** [comment]
This is probably a paths error. But you don't say where or when you get this error, so it's not really possible to help.

Please check your paths are correct. If so, please specify exactly what command you are running, then post the full error log and re-open this ticket.

Thanks
