### ISSUE TITLE
Python with IPv6 support

### ISSUE THREAD

**Issue by Frimkron** [kivy/kivy-ios#203]
Hi

Since 1 June all apps submitted to iTunes are required to have support for IPv6-only networks. Unfortunately when the `python` recipe builds for armv7 and arm64 it doesn't enable ipv6 support, so connections made using the Python socket library don't meet Apple's guidelines.

I tried adding the `--enable-ipv6` configure option to the recipe, but when configure is run it gets the following error:

> Fatal: You must get working getaddrinfo() function.
>       or you can specify "--disable-ipv6".

I don't know whether there is genuinely a problem with this function on these architectures, or whether this is a bug in the test, but for my purposes I was able to comment out the test and proceed with the build without problems.
##

**Comment by Zen-CODE** [comment]
This now works by default (thanks @tito). Please update and try again. Note: You need to generate a new project and use the updated main.m file from there otherwise you will probably encounter compilation errors.

Thanks
