### ISSUE TITLE
EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by TheDocter** [kivy/kivy-ios#210]
I'm building just a basic app to test and learn on how to use this to create a game in python eventually and build it out to iOS. 

Xcode: 7.3.1 (7D1014)
Python: 2.7.12
Main.py - http://pastebin.com/udxuZfjr
Error File - context_instructions.c
Line that produces the Error: __Pyx_DECREF(((PyObject *)__pyx_v_self->_texture));
PyObject is Null (I am unsure where PyObject is getting set)

Here is all the output I could find. in Xcode

> 2016-09-11 23:15:00.262 rundogrun[18245:188983] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
> 2016-09-11 23:15:00.263 rundogrun[18245:188983] PythonHome is: /Developer/CoreSimulator/Devices/E052534F-DEA1-4AE4-BCB8-614F990FFB59/data/Containers/Bundle/Application/85BD74F9-1842-48F0-AEB8-B7A8B8CB9A1C/rundogrun.app
> 2016-09-11 23:15:00.263 rundogrun[18245:188983] Initializing python
> 2016-09-11 23:15:00.322 rundogrun[18245:188983] Running main.pyo: /Developer/CoreSimulator/Devices/E052534F-DEA1-4AE4-BCB8-614F990FFB59/data/Containers/Bundle/Application/85BD74F9-1842-48F0-AEB8-B7A8B8CB9A1C/rundogrun.app/YourApp/main.pyo
> [INFO              ] [Kivy        ] v1.9.1
> [INFO              ] [Python      ] v2.7.1 (r271:86832, Sep 11 2016, 22:11:40) 
> [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
> [INFO              ] [Factory     ] 179 symbols loaded
> [INFO              ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)
> [INFO              ] [OSC         ] using <thread> for socket
> [INFO              ] [Window      ] Provider: sdl2
> [INFO              ] [GL          ] OpenGL version <OpenGL ES 2.0 APPLE-12.0.41>
> [INFO              ] [GL          ] OpenGL vendor <Apple Inc.>
> [INFO              ] [GL          ] OpenGL renderer <Apple Software Renderer>
> [INFO              ] [GL          ] OpenGL parsed version: 2, 0
> [INFO              ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
> [INFO              ] [GL          ] Texture max size <4096>
> [INFO              ] [GL          ] Texture max units <8>
> [INFO              ] [Window      ] auto add sdl2 input provider
> [INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
> [INFO              ] [Text        ] Provider: sdl2
>  Exception ImportError: 'No module named pyobjus' in 'kivy.properties.dpi2px' ignored
> [INFO              ] [Base        ] Start application main loop
> [INFO              ] [GL          ] NPOT texture support is available
> rundogrun was compiled with optimization - stepping may behave oddly; variables may not be available.
> (lldb) 

Hopefully I've supplied enough info on my issue that someone can help me. If you need more info just let me know where to look and I will get it for you. Thanks for all your input and help on this issue. I've been googling and looking for answers on this all day.
##

**Comment by Zen-CODE** [comment]
Have you built using pyobjus i.e.
    ./toolchain.py build pyobjus

**Comment by Zen-CODE** [comment]
Okay, the code you posted leaves out the kv so we can't be certain whether it's using pyobjus.

    gamePres = Builder.load_file("RunDogRun.kv")

Please try:

a. installing pyobjus (see previous post)

b. pulling the latest version of kivy-ios and rebuilding.

If you still have errors, please re-open and post the kv and the new log file.

Thanks
