### ISSUE TITLE
ERROR ITMS-90171: "Invalid Bundle Structure..."

### ISSUE THREAD

**Issue by mrhdias** [kivy/kivy-ios#215]
I've included a screenshot of the full error message I'm getting. This happens when I try upload the app to App Store from Xcode. I don't get any errors when running the app.

This error only happen with pycrypto library.

![error](https://cloud.githubusercontent.com/assets/589045/19431817/ea30f42c-9451-11e6-8817-eed6e7c50c30.png)
##

**Comment by mrhdias** [comment]
I found the solution here:
https://groups.google.com/forum/#!topic/kivy-users/l9wVUhco98s
But the pycrypto recipe should automatically clean up this files after build the package.

**Comment by Zen-CODE** [comment]
This issue appears fixed. Please update and re-open the ticket if not.

Thanks
