### ISSUE TITLE
problem when downloading hostlibffi

### ISSUE THREAD

**Issue by cktonychang** [kivy/kivy-ios#216]
![image](https://cloud.githubusercontent.com/assets/22651281/19716157/c78ac852-9b8c-11e6-8428-a10b30a7b2b7.png)
well, I got in the same trouble when downloading freetype, too. I just download it manually and put it in the corresponding directory. However, it doesn't work when downloading hostlibffi. I put the file there, and the error message shows like below:
![image](https://cloud.githubusercontent.com/assets/22651281/19716224/2e814824-9b8d-11e6-89cb-62d14f22ea66.png)
##

**Comment by Zen-CODE** [comment]
Can you open the downloaded file and extract all contents successfully?

**Comment by Zen-CODE** [comment]
@cktonychang. Others have solved by ensuring the XCode command line tools are installed.This happens without them.

As this issue is getting old, we will assume this is the problem. Please post here again if this does not solve it for you.

**Comment by cktonychang** [comment]
oh sorry, the former mail has been put in the trash. I’ve installed the XCode Command line tools, but it still not works.

**Comment by Zen-CODE** [comment]
What 'not works'/? What message do you get now? It should not be the same as it does not need to download that file.

Also, perhaps try pulling the latest, do ./toochain.py distclean and try again?

**Comment by cktonychang** [comment]
Sorry, away from work several days. I’ve just do as you say, pull the latest ivy and run “./toolchain.py distclean” and build again. But errors still happened as following.

> 在 2016年11月25日，下午1:53，Richard Larkin <notifications@github.com> 写道：
> 
> ./toochain.py distclean

**Comment by Zen-CODE** [comment]
Please can you post the a full error log?
