### ISSUE TITLE
Removing `putenv("KIVY_NO_CONSOLELOG=1")` does not show print statements

### ISSUE THREAD

**Issue by kdheepak** [kivy/kivy-ios#217]
I've removed the line `putenv("KIVY_NO_CONSOLELOG=1")` from main.m but print statements still do not show. I'm using Xcode8.1 with iOS10.

**Comment by Zen-CODE** [comment]
Try this fix?

https://github.com/kivy/kivy-ios/pull/219/files

**Comment by kdheepak** [comment]
This worked!

**Comment by kdheepak** [comment]
Although, removing these lines prints console output in Xcode even if `putenv("KIVY_NO_CONSOLE=1")` is not removed.

**Comment by Zen-CODE** [comment]
Hmm. We could change that in the referenced code, but I think this runs before any of the user's Python code. Where are you setting your 'KIVY_NO_CONSOLE' ? I'll check shortly if it can be done here...

**Comment by Zen-CODE** [comment]
Should be fixed by https://github.com/kivy/kivy-ios/pull/219/files. Please re-open if not.
