### ISSUE TITLE
Windows and Linux Support

### ISSUE THREAD

**Issue by mondlos** [kivy/kivy-ios#230]
I would love to have the possiblity to create kivy-ios packages on Windows or Linux.

**Comment by Zen-CODE** [comment]
Yes, we all know that would be lovely. But it's not that simple and has a whole lot of legal and financial implications that are not within Kivy's control. The redistribution on Windows dll's being one. Simply not legal.

And Apple only allow you to use their tools on their hardware an operating systems. Out of our control. Sorry ;-)

**Comment by mondlos** [comment]
So I can conclude that if somebody creates the Open-Source Versions of the needed libraries kivy-ios can be ported for Windows and Mac?

**Comment by Zen-CODE** [comment]
To run an app natively on Windows, you need to call Windows API functions (same concept for Mac) and have them do stuff for you. They allow the operating system to manage devices and resources. There are are not simply 'library' functions, they are operating system functions. How would you propose the replace them?
