### ISSUE TITLE
Swift Project Creation

### ISSUE THREAD

**Issue by gfyoung** [kivy/kivy-ios#235]
It would be nice to be able to create a project in Swift and not just in Objective-C when building our `kivy` project.  Perhaps a flag to indicate which language you would prefer would be even better.
<hr/>
Want to back this issue? <b><a href="https://www.bountysource.com/issues/39615191-swift-project-creation?utm_campaign=plugin&utm_content=tracker%2F9081&utm_medium=issues&utm_source=github">Post a bounty on it!</a></b>

We accept bounties via **[Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F9081&utm_medium=issues&utm_source=github)**.

**Comment by Zen-CODE** [comment]
That would be nice, but I think that's a big project. You would basically need to another 'pyobjus' for swift. With all the bindings and type conversions etc. pyobjus was originally a GSOC project. Perhaps this is a new one? Or how do you envision this working?

**Comment by gfyoung** [comment]
I'm actually not really sure how this would work, especially since I am not aware of anything that could allow us to interface Python and Swift together.  Though your suggestion of another `pyobjus` would be the first way to explore I would imagine.  I brought this up given that Swift has become Apple's default language for apps now, so it would make sense at some point to move `kivy-ios` towards that.

**Comment by gfyoung** [comment]
Given the difficulty of this endeavor, I'm going to close this.  If anyone wants to take it up again, feel free to re-open the issue :smile:

**Comment by ColdGrub1384** [comment]
@Zen-CODE You can just mark your Swift classes and methods as `@objc` and it should work.

**Comment by Zen-CODE** [comment]
@ColdGrub1384. How would one then work with them from PyObjus?
