### ISSUE TITLE
Command failed: xcodebuild -configuration Debug ENABLE_BITCODE=NO clean build throws error

### ISSUE THREAD

**Issue by kennedyshead** [kivy/kivy-ios#236]
I did set those values in xcode but the app will not build :/

```
=== BUILD TARGET ***** OF PROJECT ****** WITH CONFIGURATION Debug ===

Check dependencies
Signing for "******" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.1'

Command failed: xcodebuild -configuration Debug ENABLE_BITCODE=NO clean build
Buildozer failed to execute the last command
The error might be hidden in the log above this error
Please read the full log, and search for it before
raising an issue with buildozer itself.
In case of a bug report, please add a full log with log_level = 2
```

**Comment by Zen-CODE** [comment]
Your error message indicates this is code signing issue. You need to setup your certificates in order to do this. Standard Apple procedures would apply.

https://developer.apple.com/support/code-signing/

Feel free to post again here if you don't come right.

**Comment by zoltan-fedor** [comment]
Have you ever managed to figure this out?

I had setup signing, setup development team in xcode for the project and I still receiving this error.

**Comment by Zen-CODE** [comment]
No. Personally, I never had this problem but I've only built from XCode, 
not from the command line. I would guess there is some parameter one 
needs to pass to specify which certificate to use to sign. XCode present 
you with a list which you select from. How would you specify these on 
the command line?

Perhaps this can help?

http://stackoverflow.com/questions/40924168/xcode-8-xcodebuild-manual-code-signing-from-command-line-for-multiple-provision

**Comment by zoltan-fedor** [comment]
Sorry, I figured it out right after I submitted it.
The problem was that I was using buildozer and I did not realize that it creates its on XCode project under the .buildozer/ library, so I was modifying the settings of an XCode project which actually wasn't used by the build process...

In any case, thanks for your response. Let's hope it will help somebody else too in the future.
