### ISSUE TITLE
Issue with Kivy's graphics when importing App on Kivy's master branch

### ISSUE THREAD

**Issue by cruor99** [kivy/kivy-ios#240]
Hello! I recently ran into an issue when trying to help a guy build an ios app, and there seems to have been a change on kivy's master branch that may have introduced an issue when building ios apps. Using buildozer for this, but I assume the issue would go here (or possibly on Kivy itself?)

The error is as follows:

> [INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.1 (r271:86832, Jan 11 2017, 23:29:36) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
[INFO   ] [Factory     ] 193 symbols loaded
 Traceback (most recent call last):
   File "/Users/cruor/code/sadpandareader/app/.buildozer/ios/platform/kivy-ios/sadpandareader-ios/YourApp/main.py", line 2, in <module>
   File "/Users/cruor/code/sadpandareader/app/.buildozer/ios/platform/kivy-ios/build/kivy/i386/kivy-master/iosbuild/lib/python2.7/site-packages/kivy/app.py", line 327, in <module>
   File "/Users/cruor/code/sadpandareader/app/.buildozer/ios/platform/kivy-ios/build/kivy/i386/kivy-master/iosbuild/lib/python2.7/site-packages/kivy/uix/widget.py", line 244, in <module>
   File "/Users/cruor/code/sadpandareader/app/.buildozer/ios/platform/kivy-ios/build/kivy/i386/kivy-master/iosbuild/lib/python2.7/site-packages/kivy/graphics/__init__.py", line 89, in <module>
   File "<string>", line 32, in load_module
 ImportError: dynamic module does not define init function (initinstructions)
2017-01-11 23:50:31.222854 sadpandareader[318:9880] Application quit abnormally!
2017-01-11 23:50:31.230134 sadpandareader[318:9880] Leaving

This change must have been very recent, between the 28th of december and now - and it seems that only one thing changed relating to the graphics part in that time window seems to be this commit https://github.com/kivy/kivy/commit/00b2ddbcb02edc661a77d3ca23dd2e91554f50f7 from the kivy project.

The code for my project can be found here
https://github.com/cruor99/sadpandareader

**Comment by oboingo** [comment]
I get similar if I try to compile TouchTracer with:

`requirements = kivy==master`

```
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.1 (r271:86832, Jan 11 2017, 16:11:14) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
[INFO   ] [Factory     ] 193 symbols loaded
 Traceback (most recent call last):
   File "/Users/me/code/touchtracer/.buildozer/ios/platform/kivy-ios/myapp-ios/YourApp/main.py", line 25, in <module>
   File "/Users/me/code/touchtracer/.buildozer/ios/platform/kivy-ios/build/kivy/i386/kivy-master/iosbuild/lib/python2.7/site-packages/kivy/app.py", line 327, in <module>
   File "/Users/me/code/touchtracer/.buildozer/ios/platform/kivy-ios/build/kivy/i386/kivy-master/iosbuild/lib/python2.7/site-packages/kivy/uix/widget.py", line 244, in <module>
   File "/Users/me/code/touchtracer/.buildozer/ios/platform/kivy-ios/build/kivy/i386/kivy-master/iosbuild/lib/python2.7/site-packages/kivy/graphics/__init__.py", line 89, in <module>
   File "<string>", line 32, in load_module
 ImportError: dynamic module does not define init function (initinstructions)
2017-01-11 16:57:07.254 myapp[67944:1107183] Application quit abnormally!
2017-01-11 16:57:07.260 myapp[67944:1107183] Leaving
```

**Comment by keavin7** [comment]
Also getting this. I believe this has to do with reading in some type of compiled library... Thought maybe it was because I was compiling in the 32 Bit Version because of the simulator i386 architecture.

Did you ever resolve this???

**Comment by oboingo** [comment]
Sort of.  I have no idea if it is the "right" way to do it though.  But here it is, in case it helps you out too.

- Get a repo with a copy of Kivy from December, so not the most recent master.  I used one from December 7th, before something changed that broke it (not sure what). I used this one:  https://github.com/Bakterija/kivy 
- Change your buildozer.spec file requirements to include kivy=badname (or anything that will fail).
- Try: buildozer ios debug
- This will get kivy-ios downloaded, including the kivy recipe, but...
- The build will fail because the kivy version doesn't exist.  (Again, don't know if this is the best, but it worked for me)
- Edit the kivy recipe in kivy-ios (in your .buildozer directory) and change the url in the file to the repo you selected in the first step.
- Edit your buildozer.spec again, and put kivy==master back into the requirements.  Now it will use your new recipe, pull from the old repo, and compile.
- Re-try: buildozer ios debug
- This time it will download (and use) your new kivy-ios recipe and download the alternate kivy.

That worked for me.  Your mileage may vary.  If there is an easier way to do all this (there must be), I am all ears.  I would love something easier.

**Comment by keavin7** [comment]
Ahh i see... I did something similar. I just went back to 1.9.1 and it seems to be working A OK.

**Comment by debauchery1st** [comment]
1. edit the file _kivy-ios/recipe/kivy/__init__.py_

**Comment by Zen-CODE** [comment]
I suspect it's this line in instructions.pyx

    include "../include/config.pxi"

There does not appear to be any such file.

**Comment by akshayaurora** [comment]
These were included cause of the recent change to the way kivy graphics
were compiled.

When do you get this error ?
While running it on the emulator or on the actual device?

**Comment by cruor99** [comment]
The error occurs on both ios device and emulators.

**Comment by Zen-CODE** [comment]
I get in in the emulator too. Have not tested on a device yet. Where is this file supposed to come from? Where is it compiled? Because I cannot find a matching filename anywhere in the repo.

**Comment by cruor99** [comment]
There is a reference to it in setup.py, I believe.
Have not been able to test this myself though :\

**Comment by Zen-CODE** [comment]
There are a few references to it in there, but they appear to assume it exists. I can't see how it is generated from there, but then again, I'm not at all familiar with the cython compiling side.

**Comment by cruor99** [comment]
I find it in my current virtualenv under kivy/include/config.pxi as expected, with the following output:

```
$ cat config.pxi
# Autogenerated file for Kivy Cython configuration
DEF PY3 = 1
DEF USE_RPI = 0
DEF USE_MALI = 0
DEF USE_EGL = 0
DEF USE_OPENGL_ES2 = 0
DEF USE_OPENGL_MOCK = 0
DEF USE_SDL2 = 1
DEF USE_IOS = 0
DEF USE_MESAGL = 0
DEF USE_X11 = 0
DEF USE_GSTREAMER = 0
DEF USE_AVFOUNDATION = 0
DEF USE_OSX_FRAMEWORKS = 0
DEF DEBUG_GL = 0
DEF DEBUG = False
DEF PLATFORM = "linux"
```

If you take a look in the makefile, there are some specific references to it in regards to ios, maybe that is related? 
https://github.com/kivy/kivy/blob/master/Makefile#L46-L64

**Comment by Zen-CODE** [comment]
I'm guessing it's a path issue. Look here: https://gist.github.com/Zen-CODE/aac71059f1b9b5b132bcffb05d0d26b8

That's the output of my './toolchain.py build kivy' command. If you search of 'config.pxi', sometimes it's in the include folder, sometimes in graphics. Perhaps that right and there are 2. Will investigate further....

**Comment by Zen-CODE** [comment]
@tito. Would you able to point me in the right direction here? I'm willing to do the gruntwork, but I'm not familiar with Cython and have no idea where to begin. How and where is config.pxi built?

**Comment by tito** [comment]
I wanted to look at it, but unfortunately, i'm still stuck on compiling openssl (MD5 missing symbol).
(i have an app to deliver for iOS in less than 2 weeks).

For the issue, i have no real idea, unsure about the changes about it in 1.10.0. Double check the setup.py to see where the config.pxi is (maybe there is no 2 of them?)

**Comment by Zen-CODE** [comment]
From logging the value of the paths in setup.py, and I can tell is that it's changed from
'kivy/graphics/config.pxi' to 'kivy/include/config.pxi'. That seems consistent with the changes to graphics/__init__.py,

**Comment by tito** [comment]
Do you have a recent Cython? Did you clean everything before building? Do you have Kivy in your PYTHONPATH?

**Comment by tito** [comment]
Ok, reproduced the issue, i'll look into it.

**Comment by tito** [comment]
The first issue was the cythonize.py function that rewrite a variable "cgl", into "kivy_graphics_cgl". After fixing that, it seems now we require a `KIVY_BACKEND=sdl2` to be set (to prevent auto detection that fail). But can't load it yet. Still on it.

**Comment by tito** [comment]
Fixed. You need to regenerate your project (for the new main.m), or backport main.m changes from the commit 91ecf0f into your own project!
