### ISSUE TITLE
Build fails loading associated schemes

### ISSUE THREAD

**Issue by zoltan-fedor** [kivy/kivy-ios#244]
Hi,
I have a project which is using Google Analytics, which in turn requires GoogleToolboxForMac.
All got installed via Cocoapods and after activating the GoogleToolboxForMac schema in XCode Products, it builds fine in XCode.

But when I try to compile it with kivy-ios (using it via buildozer), then the build fails with:
```
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1
```

The build command kivy-ios is running and fails also fails if I run it manually in the project (same error):
`xcodebuild -configuration Debug ENABLE_BITCODE=NO clean build`

But if I manually add the schema to it, then it succeeds, no issue finding the GoogleToolboxForMac schema:
`xcodebuild -workspace myproject.xcworkspace -scheme myproject -configuration Debug ENABLE_BITCODE=NO clean build`

So the question really is, whether is there a way to force kivy-ios to build with those additional flags?

Thanks

**Comment by tito** [comment]
I guess you could provide a patch do add it. But i don't understand the difference honestly :/

**Comment by zoltan-fedor** [comment]
Sorry, you are right. I re-read my issue above and it is not an easy read. :-) Apologies.

What I meant, that kivy-ios compile fails, because Cocopod installs require compile with the `-workspace myproject.xcworkspace -scheme myproject` flags and I was wondering whether we could have those added to kivy-ios.

**Comment by tito** [comment]
I understood about that, i just don't understand -why- both workspace and scheme need to be passed to xcoderun in this case. Not why you have the issue, just why it just been required now.
So yes, don't hesitate to submit a patch about it!

**Comment by Zen-CODE** [comment]
Multiple changes mean this issue is probably fixed. Please retry with the latest checkout and re-raise if the problem persists.
