### ISSUE TITLE
Building kivy-ios failure

### ISSUE THREAD

**Issue by joemac875** [kivy/kivy-ios#246]
Every time I attempt to run ./toolchain build kivy , the compilation gets stuck. I am running Sierra and Xcode 8.2.1. Here's my terminal output:

Prebuild python for i386
Apply patch ssize-t-max.patch
Apply patch dynload.patch
Apply patch static-_sqlite3.patch
Copy ModulesSetup to Modules/Setup.local
Copy _scproxy.py to Lib/_scproxy.py
Apply patch xcompile.patch
Apply patch setuppath.patch
Append ModulesSetup.mobile to Modules/Setup.local
Build python for i386
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
checking for --enable-universalsdk... no
checking for --with-universal-archs... 32-bit
checking MACHDEP... darwin
checking EXTRAPLATDIR... $(PLATMACDIRS)
checking machine type as reported by uname -m... x86_64
checking for --without-gcc... no
checking for i386-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang accepts -g... yes
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang option to accept ISO C89... none needed
checking for --with-cxx-main=<compiler>... no
checking for c++... c++
configure: WARNING:

  By default, distutils will build C++ extension modules with "c++".
  If this is not intended, then set CXX on the configure command line.
  
checking how to run the C preprocessor... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for --with-suffix... 
checking for case-insensitive build directory... yes
checking LIBRARY... libpython$(VERSION).a
checking LINKCC... $(PURIFY) $(MAINCC)
checking for GNU ld... no
checking for --enable-shared... no
checking for --enable-profiling... 
checking LDLIBRARY... libpython$(VERSION).a
checking for i386-apple-darwin-ranlib... no
checking for ranlib... ranlib
configure: WARNING: using cross tools not prefixed with host triplet
checking for ar... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
checking for svnversion... found
checking for a BSD-compatible install... /usr/bin/install -c
checking for --with-pydebug... no
checking whether /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang accepts -fno-strict-aliasing... yes
checking whether /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang accepts -OPT:Olimit=0... yes
checking whether gcc supports ParseTuple __format__... no
checking whether pthreads are available without options... no
checking whether /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang accepts -Kpthread... no
checking whether /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang accepts -Kthread... no
checking whether /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang accepts -pthread... no
checking whether c++ also accepts flags for thread support... no
checking for ANSI C header files... (cached) no
checking asm/types.h usability... no
checking asm/types.h presence... no
checking for asm/types.h... no
checking conio.h usability... no
checking conio.h presence... no
checking for conio.h... no
checking curses.h usability... yes
checking curses.h presence... no
configure: WARNING: curses.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: curses.h: proceeding with the compiler's result
checking for curses.h... yes
checking direct.h usability... no
checking direct.h presence... no
checking for direct.h... no
checking dlfcn.h usability... yes
checking dlfcn.h presence... no
configure: WARNING: dlfcn.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: dlfcn.h: proceeding with the compiler's result
checking for dlfcn.h... yes
checking errno.h usability... yes
checking errno.h presence... no
configure: WARNING: errno.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: errno.h: proceeding with the compiler's result
checking for errno.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... no
configure: WARNING: fcntl.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: fcntl.h: proceeding with the compiler's result
checking for fcntl.h... yes
checking grp.h usability... yes
checking grp.h presence... no
configure: WARNING: grp.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: grp.h: proceeding with the compiler's result
checking for grp.h... yes
checking ieeefp.h usability... no
checking ieeefp.h presence... no
checking for ieeefp.h... no
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking langinfo.h usability... yes
checking langinfo.h presence... no
configure: WARNING: langinfo.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: langinfo.h: proceeding with the compiler's result
checking for langinfo.h... yes
checking libintl.h usability... no
checking libintl.h presence... no
checking for libintl.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... no
configure: WARNING: ncurses.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: ncurses.h: proceeding with the compiler's result
checking for ncurses.h... yes
checking poll.h usability... yes
checking poll.h presence... no
configure: WARNING: poll.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: poll.h: proceeding with the compiler's result
checking for poll.h... yes
checking process.h usability... no
checking process.h presence... no
checking for process.h... no
checking pthread.h usability... yes
checking pthread.h presence... no
configure: WARNING: pthread.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: pthread.h: proceeding with the compiler's result
checking for pthread.h... yes
checking shadow.h usability... no
checking shadow.h presence... no
checking for shadow.h... no
checking signal.h usability... yes
checking signal.h presence... no
configure: WARNING: signal.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: signal.h: proceeding with the compiler's result
checking for signal.h... yes
checking for stdint.h... (cached) yes
checking stropts.h usability... no
checking stropts.h presence... no
checking for stropts.h... no
checking termios.h usability... yes
checking termios.h presence... no
configure: WARNING: termios.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: termios.h: proceeding with the compiler's result
checking for termios.h... yes
checking thread.h usability... no
checking thread.h presence... no
checking for thread.h... no
checking for unistd.h... (cached) yes
checking utime.h usability... yes
checking utime.h presence... no
configure: WARNING: utime.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: utime.h: proceeding with the compiler's result
checking for utime.h... yes
checking sys/audioio.h usability... no
checking sys/audioio.h presence... no
checking for sys/audioio.h... no
checking sys/bsdtty.h usability... no
checking sys/bsdtty.h presence... no
checking for sys/bsdtty.h... no
checking sys/epoll.h usability... no
checking sys/epoll.h presence... no
checking for sys/epoll.h... no
checking sys/event.h usability... yes
checking sys/event.h presence... no
configure: WARNING: sys/event.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/event.h: proceeding with the compiler's result
checking for sys/event.h... yes
checking sys/file.h usability... yes
checking sys/file.h presence... no
configure: WARNING: sys/file.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/file.h: proceeding with the compiler's result
checking for sys/file.h... yes
checking sys/loadavg.h usability... no
checking sys/loadavg.h presence... no
checking for sys/loadavg.h... no
checking sys/lock.h usability... yes
checking sys/lock.h presence... no
configure: WARNING: sys/lock.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/lock.h: proceeding with the compiler's result
checking for sys/lock.h... yes
checking sys/mkdev.h usability... no
checking sys/mkdev.h presence... no
checking for sys/mkdev.h... no
checking sys/modem.h usability... no
checking sys/modem.h presence... no
checking for sys/modem.h... no
checking sys/param.h usability... yes
checking sys/param.h presence... no
configure: WARNING: sys/param.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/param.h: proceeding with the compiler's result
checking for sys/param.h... yes
checking sys/poll.h usability... yes
checking sys/poll.h presence... no
configure: WARNING: sys/poll.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/poll.h: proceeding with the compiler's result
checking for sys/poll.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... no
configure: WARNING: sys/select.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/select.h: proceeding with the compiler's result
checking for sys/select.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... no
configure: WARNING: sys/socket.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/socket.h: proceeding with the compiler's result
checking for sys/socket.h... yes
checking sys/statvfs.h usability... yes
checking sys/statvfs.h presence... no
configure: WARNING: sys/statvfs.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/statvfs.h: proceeding with the compiler's result
checking for sys/statvfs.h... yes
checking for sys/stat.h... (cached) yes
checking sys/termio.h usability... no
checking sys/termio.h presence... no
checking for sys/termio.h... no
checking sys/time.h usability... yes
checking sys/time.h presence... no
configure: WARNING: sys/time.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/time.h: proceeding with the compiler's result
checking for sys/time.h... yes
checking sys/times.h usability... yes
checking sys/times.h presence... no
configure: WARNING: sys/times.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/times.h: proceeding with the compiler's result
checking for sys/times.h... yes
checking for sys/types.h... (cached) yes
checking sys/un.h usability... yes
checking sys/un.h presence... no
configure: WARNING: sys/un.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/un.h: proceeding with the compiler's result
checking for sys/un.h... yes
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... no
configure: WARNING: sys/utsname.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/utsname.h: proceeding with the compiler's result
checking for sys/utsname.h... yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... no
configure: WARNING: sys/wait.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/wait.h: proceeding with the compiler's result
checking for sys/wait.h... yes
checking pty.h usability... no
checking pty.h presence... no
checking for pty.h... no
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking sys/resource.h usability... yes
checking sys/resource.h presence... no
configure: WARNING: sys/resource.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/resource.h: proceeding with the compiler's result
checking for sys/resource.h... yes
checking netpacket/packet.h usability... no
checking netpacket/packet.h presence... no
checking for netpacket/packet.h... no
checking sysexits.h usability... yes
checking sysexits.h presence... no
configure: WARNING: sysexits.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sysexits.h: proceeding with the compiler's result
checking for sysexits.h... yes
checking bluetooth.h usability... no
checking bluetooth.h presence... no
checking for bluetooth.h... no
checking bluetooth/bluetooth.h usability... no
checking bluetooth/bluetooth.h presence... no
checking for bluetooth/bluetooth.h... no
checking linux/tipc.h usability... no
checking linux/tipc.h presence... no
checking for linux/tipc.h... no
checking spawn.h usability... yes
checking spawn.h presence... no
configure: WARNING: spawn.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: spawn.h: proceeding with the compiler's result
checking for spawn.h... yes
checking util.h usability... yes
checking util.h presence... no
configure: WARNING: util.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: util.h: proceeding with the compiler's result
checking for util.h... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking whether sys/types.h defines makedev... yes
checking for term.h... yes
checking for linux/netlink.h... no
checking for clock_t in time.h... no
checking for makedev... no
checking Solaris LFS bug... no
checking for mode_t... no
checking for off_t... no
checking for pid_t... no
checking for size_t... no
checking for uid_t in sys/types.h... no
checking for uint32_t... no
checking for uint64_t... no
checking for int32_t... no
checking for int64_t... no
checking for ssize_t... no
checking size of int... 0
checking size of long... 0
checking size of void *... 0
checking size of short... 0
checking size of float... 0
checking size of double... 0
checking size of fpos_t... 0
checking size of size_t... 0
checking size of pid_t... 0
checking for long long support... yes
checking size of long long... 0
checking for long double support... yes
checking size of long double... 0
checking for _Bool support... yes
checking size of _Bool... 0
checking for uintptr_t... yes
checking size of uintptr_t... configure: error: in `/Users/joemac/Documents/Software_Engineering/kivy-ios/build/python/i386/Python-2.7.1':
configure: error: cannot compute sizeof (uintptr_t)
See `config.log' for more details.
Traceback (most recent call last):
  File "./toolchain.py", line 1318, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1088, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1112, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 980, in build_recipes
    recipe.execute()
  File "/Users/joemac/Documents/Software_Engineering/kivy-ios/toolchain.py", line 590, in execute
    self.build_all()
  File "/Users/joemac/Documents/Software_Engineering/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/joemac/Documents/Software_Engineering/kivy-ios/toolchain.py", line 679, in build_all
    self.build(arch)
  File "/Users/joemac/Documents/Software_Engineering/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/joemac/Documents/Software_Engineering/kivy-ios/toolchain.py", line 666, in build
    self.build_arch(arch)
  File "/Users/joemac/Documents/Software_Engineering/kivy-ios/recipes/python/__init__.py", line 53, in build_arch
    _env=build_env)
  File "/Users/joemac/Documents/Software_Engineering/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_77: 

  RAN: '/Users/joemac/Documents/Software_Engineering/kivy-ios/build/python/i386/Python-2.7.1/configure CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld CFLAGS=-arch i386 -pipe -no-cpp-precomp --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk -O3 -miphoneos-version-min=6.0.0 -I/Users/joemac/Documents/Software_Engineering/kivy-ios/dist/include/i386/freetype -I/Users/joemac/Documents/Software_Engineering/kivy-ios/dist/include/i386/hostlibffi -I/Users/joemac/Documents/Software_Engineering/kivy-ios/dist/include/i386/libffi -I/Users/joemac/Documents/Software_Engineering/kivy-ios/dist/include/common/sdl2 -I/Users/joemac/Documents/Software_Engineering/kivy-ios/dist/include/common/sdl2_image -I/Users/joemac/Documents/Software_Engineering/kivy-ios/dist/include/common/sdl2_mixer -I/Users/joemac/Documents/Software_Engineering/kivy-ios/dist/include/common/sdl2_ttf LDFLAGS=-arch i386 --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk -L/Users/joemac/Documents/Software_Engineering/kivy-ios/dist/lib -lsqlite3 -miphoneos-version-min=6.0.0 -undefined dynamic_lookup --without-pymalloc --disable-toolbox-glue --host=i386-apple-darwin --prefix=/python --with-system-ffi --without-doc-strings'

  STDOUT:
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
checking for --enable-universalsdk... no
checking for --with-universal-archs... 32-bit
checking MACHDEP... darwin
checking EXTRAPLATDIR... $(PLATMACDIRS)
checking machine type as reported by uname -m... x86_64
checking for --without-gcc... no
checking for i386-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files.... (14182 more, please see e.stdout)

  STDERR:

**Comment by lc-soft** [comment]
You need to provide the contents of `config.log` file.

I suggest you try to [search for some related solutions](https://www.google.com/#q=error+cannot+compute+sizeof) first.

**Comment by tito** [comment]
I just build kivy-ios on fresh latest sierra, didn't got this issue. Please double check your installatino, clean all the caches (.buildozer and $HOME/.buildozer if you used it), maybe reclone kivy-ios to be sure there is no leftover, etc.
Maybe you also broke your installation by using others tools/installating others tool at some points with brew or port.
