### ISSUE TITLE
Build failed in Xcode

### ISSUE THREAD

**Issue by Mr-Binary** [kivy/kivy-ios#253]
Use the latest version

After using `./toolchain.py create <title> <app_directory>`

I tried open the `.xcodeproj`, it said `Build xxx: Failed`. List is too long, but I think the following is the related one.

```bash
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Listing /Users/albertgao/codes/python/ios_kivy/kivy-ios/salt-ios/YourApp ...
.....
```

Maybe it has something to do with my previous [issue](https://github.com/kivy/kivy-ios/issues/252)? But I don't know where to modify this time. Any clues?

**Comment by tito** [comment]
Nop, that's not an issue. Send the full log if you have an issue.
As for your previous issue, just be sure you can run Cython in the same way xcode does (not withing a venv.).
