### ISSUE TITLE
Build iOS project always fails at 2nd script compiling main.py

### ISSUE THREAD

**Issue by danyalejandro** [kivy/kivy-ios#256]
After successfully compiling for Android, I'm trying to compile a simple helloworld project for iOS and I'm running out of ideas on how to make this work at all.

The project code is only the "main.py" file from the website example (it compiles and works on my mac, removing indentation to deal with github markdown):
`import kivy`
`from kivy.app import App`
`from kivy.uix.label import Label`
`kivy.require('1.10.0')  # replace with your current kivy version !`

`class MyApp(App):`

`  def build(self):`
`  return Label(text='Hello world')`

`if __name__ == '__main__':`
`  MyApp().run()`

After building kivy-ios and using "python toolchain.py create PROJECTNAME ROUTETODIRECTORY" to create the XCode project, I open the generated project and click the "Play" button.

The Build always fails during the 2nd script, the one that says:
`/Users/danyalejandro/kivy/kivy-ios/dist/hostpython/bin/python -OO -m compileall "$PROJECT_DIR"/YourApp`

This is what my XCode shows:
![image](https://user-images.githubusercontent.com/1218608/27158361-62d7b75e-511b-11e7-9c10-9ccde16336b0.png)

At the end (after listing and compiling many files), the log shows the script fails when trying to compile the main.py file and returns "1". Of course, no .pyo or .pyc file is generated for said file.

![image](https://user-images.githubusercontent.com/1218608/27158487-13a5d534-511c-11e7-86a3-ab158d1a6a42.png)

This is the full log obtained from trying to build the project:

[log.txt](https://github.com/kivy/kivy-ios/files/1076149/log.txt)

What could be happening? I'm pulling out my hair on this...

**Comment by LarsDu** [comment]
I had the same issue. I was able to fix it by disabling all these Run scripts in xcode, but running them from command line before hitting the "play" button.

**Comment by hackalog** [comment]
The failure appears to be this: (a python error)
```
SyntaxError: ('invalid syntax', ('/Users/danyalejandro/kivy/kivy-ios/pong-ios/YourApp/.buildozer/android/platform/build/dists/pong/python-install/share/kivy-examples/miscellaneous/shapecollisions.py', 222, 25, '            Color(rgba=(*color, 0.6))\n'))
```

**Comment by Zen-CODE** [comment]
Multiple changes mean this issue is probably fixed. Please retry with the latest checkout and re-raise if the problem persists.
