### ISSUE TITLE
Not able to build python recipe

### ISSUE THREAD

**Issue by malverick** [kivy/kivy-ios#258]
After cloning the kivy-ios repository, I build `openssl` using `./toolchain.py build openssl` which was successful but after that I tried to build `python` recipe using `./toolchain.py build python` which was not successful and it gave me the following error and 2 warnings:

> ./Modules/posixmodule.c:2661:11: error: 'system' is unavailable: not available
>       on iOS
>     sts = system(command);
>           ^
> /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/stdlib.h:187:6: note: 
>       'system' has been explicitly marked unavailable here
> int      system(const char *) __DARWIN_ALIAS_C(system);
>          ^
> ./Modules/posixmodule.c:7301:12: warning: 'tempnam' is deprecated: This function
>       is provided for compatibility reasons only. Due to security concerns
>       inherent in the design of tempnam(3), it is highly recommended that you
>       use mkstemp(3) instead. [-Wdeprecated-declarations]
>     name = tempnam(dir, pfx);
>            ^
> /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/stdio.h:395:1: note: 
>       'tempnam' has been explicitly marked deprecated here
> __deprecated_msg("This function is provided for compatibility reasons on...
> ^
> /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/sys/cdefs.h:180:48: note: 
>       expanded from macro '__deprecated_msg'
>         #define __deprecated_msg(_msg) __attribute__((deprecated(_msg)))
>                                                       ^
> ./Modules/posixmodule.c:7348:12: warning: 'tmpnam' is deprecated: This function
>       is provided for compatibility reasons only. Due to security concerns
>       inherent in the design of tmpnam(3), it is highly recommended that you use
>       mkstemp(3) instead. [-Wdeprecated-declarations]
>     name = tmpnam(buffer);
>            ^
> /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/stdio.h:275:1: note: 
>       'tmpnam' has been explicitly marked deprecated here
> __deprecated_msg("This function is provided for compatibility reasons on...
> ^
> /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/sys/cdefs.h:180:48: note: 
>       expanded from macro '__deprecated_msg'
>         #define __deprecated_msg(_msg) __attribute__((deprecated(_msg)))
>                                                       ^
> 2 warnings and 1 error generated.
> make: *** [Modules/posixmodule.o] Error 1
> make: *** Waiting for unfinished jobs....

Every recipe which depends on `python` gives me this error. The recipes which are independent of `python` build successfully.

Complete logs are here.
[logs.txt](https://github.com/kivy/kivy-ios/files/1101058/logs.txt)

**Comment by malverick** [comment]
Solved it finally after so much struggle. Turns out that the beta software of xcode was creating problem. As soon as I installed the stable xcode in my system, the problem got solved.

**Comment by d0mj** [comment]
I have the same problem with the Xcode 9.0 GM.  This is likely an issue that will need to be patched.
