### ISSUE TITLE
kivy-ios/toolchain.py build kivy fails

### ISSUE THREAD

**Issue by JuanCarlosGrishka** [kivy/kivy-ios#259]
Hello! I've got some problems with packaging an iOS application.
On Kivy website is written:

$ git clone git://github.com/kivy/kivy-ios
$ cd kivy-ios
$ ./toolchain.py build kivy

But when I try I have:

MacBook-Air-Grishka:~ grishka$ kivy-ios/toolchain.py build kivy
Traceback (most recent call last):
  File "kivy-ios/toolchain.py", line 200, in <module>
    class ArchSimulator(Arch):
  File "kivy-ios/toolchain.py", line 205, in ArchSimulator
    sysroot = sh.xcrun("--sdk", "iphonesimulator", "--show-sdk-path").strip()
  File "kivy-ios/tools/external/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "kivy-ios/tools/external/sh.py", line 486, in __init__
    self.wait()
  File "kivy-ios/tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "kivy-ios/tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/usr/bin/xcrun --sdk iphonesimulator --show-sdk-path'

  STDOUT:

  STDERR:
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphonesimulator'

I have:
macOS 10.12
Xcode 8.3.3
Python 2.7.13

**Comment by John-K** [comment]
Use xcode to install the iphonesimulator. [This article](https://stackoverflow.com/questions/39013900/how-to-install-ios-10-simulator) might be helpful to you.

**Comment by hackalog** [comment]
I assume this can be closed. @JuanCarlosGrishka ?

**Comment by ChronoNinja** [comment]
I ran into this problem as well.  The "fix" needs to be added as part of the instructions on the main markdown page for those of us building from a clean install of brew, kivy-ios etc.

Open Xcode. Go to Preferences. Go to Locations. Your command line tools drop down is likely empty. Click the drop down and select the version (for me there was only the most recent version). I was then able to go back into kivy-ios and finish the process.
