### ISSUE TITLE
"_ENGINE_load_gost" error when compiling with openssl support

### ISSUE THREAD

**Issue by nstephens** [kivy/kivy-ios#262]
My kivy app uses python requests to talk to an https service, and requires openssl.  Following along with the README I have pulled the kivy-ios repo, and done the following:

```
./toolchain.py build python kivy openssl
./toolchain.py create assetMonster ~/code/assetMonster-27/
open assetmonster-ios/assetmonster.xcodeproj
```

Once xcode launches, I click Run, and it errors with the following:
```
Apple Mach-O Linker Error Group
: "_ENGINE_load_gost", referenced from:
: Linker command failed with exit code 1 (use -v to see invocation)
```

Any tips on getting openssl to play nicely?

xcode 8.3.2
macos 10.12.6

**Comment by Zen-CODE** [comment]
Multiple changes mean this issue is probably fixed. Please retry with the latest checkout and re-raise if the problem persists.
