### ISSUE TITLE
Command /bin/sh failed with exit code 23

### ISSUE THREAD

**Issue by jdigiacinto** [kivy/kivy-ios#263]
I followed the [instructions](https://kivy.org/docs/guide/packaging-ios.html#) on how to make an iOS package here until "Then click on Play, and enjoy." However, when I run the project I get this error: 

>rsync error: some files could not be transferred (code 23) at  
>/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(996) [sender=2.6.9]
> Command /bin/sh failed with exit code 23

I'm brand new to iOS app development and am working on a tight deadline. I'd really appreciate it if anyone could give some advice or feedback! Thanks!

**Comment by ColleenKuang** [comment]
I have the same problem， too.

**Comment by LarsDu** [comment]
I had a similar issue, and I solved it by disabling all the run scripts from within Xcode, but running those same scripts from command line before ios deployment.

**Comment by Zen-CODE** [comment]
This is most likely a problem with folder given to the `python3 toochain.py create` command. Please verify that this is a valid application folder? Thanks
