### ISSUE TITLE
Fails to build Kivy

### ISSUE THREAD

**Issue by mbrockman1** [kivy/kivy-ios#266]
macOS: 10.13
Xcode: 9
kivy-ios: latest
Cython: 0.27

Shell output after running command './toolchain.py build kivy':
https://pastebin.com/YYDTPhYy

I use brew to install the latest packages for my mac. I keep having issues with trying to build Kivy using the toolchain. It looks like the issue resides with sdl2_mixer.

**Comment by tonibagur** [comment]
I had a similar problem on osx10.12, please check if this pull request solves your problem too:
https://github.com/kivy/kivy-ios/pull/268

**Comment by mbrockman1** [comment]
This is still failing for me when trying to run '/toolchain.py build kivy'. Here is the total [output](https://gist.githubusercontent.com/mbrockman1/7cb7a11a71d5d73cf7b9e78e6b9d78b0/raw/1bd8147f6c774975532b44dbc1b7cdc1e7d63b5e/gistfile1.txt)
