### ISSUE TITLE
Apple watch support

### ISSUE THREAD

**Issue by mbrockman1** [kivy/kivy-ios#269]
Has anyone been able to build an Apple Watch app or know where to find information on building an Apple Watch app? I would love to leverage plyers/kivy-ios to start developing, I would like to avoid using Swift if possible.

**Comment by QGB** [comment]
kidding?

**Comment by Zen-CODE** [comment]
Please follow up on this inquiry via the forums: https://groups.google.com/forum/#!forum/kivy-users

Thanks
