### ISSUE TITLE
kivy-ios toolchain.py fails to build sdl2_mixer

### ISSUE THREAD

**Issue by llamawright** [kivy/kivy-ios#271]
Hello,

macOS Sierra 10.12.6
Python 2.7.14
clang Apple LLVM 9.0.0
xcode 9.0.1
cython 0.25

toolchain.py build sdl2_mixer fails.   The compiler complains of a missing header file endian.h in misc.h.  The output is here:

CompileC build/SDL_mixer.build/Release-iphonesimulator/Static\ Library.build/Objects-normal/i386/block.o /Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/external/libvorbisidec-1.2.1/block.c normal i386 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch i386 -fmessage-length=80 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DWAV_MUSIC -DMODPLUG_MUSIC -DMID_MUSIC -DOGG_MUSIC -DOGG_USE_TREMOR -DHAVE_STDINT_H -DHAVE_SETENV -DHAVE_SINF -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mios-simulator-version-min=3.0 -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -I/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/build/SDL_mixer.build/Release-iphonesimulator/Static\ Library.build/SDL2_mixer.hmap -I/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/build/Release-iphonesimulator/include -I/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/../../SDL/include -I/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/../external/libmodplug-0.8.8.4/src -I/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/../external/libmodplug-0.8.8.4/src/libmodplug -I/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/../external/libvorbisidec-1.2.1 -I/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/../external/libogg-1.3.1/include -I/Users/andrew/kivy-ios/dist/include/common/sdl2 -I/Users/andrew/kivy-ios/dist/include/common/sdl2_mixer -I/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/build/SDL_mixer.build/Release-iphonesimulator/Static\ Library.build/DerivedSources/i386 -I/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/build/SDL_mixer.build/Release-iphonesimulator/Static\ Library.build/DerivedSources -F/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/build/Release-iphonesimulator -MMD -MT dependencies -MF /Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/build/SDL_mixer.build/Release-iphonesimulator/Static\ Library.build/Objects-normal/i386/block.d --serialize-diagnostics /Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/build/SDL_mixer.build/Release-iphonesimulator/Static\ Library.build/Objects-normal/i386/block.dia -c /Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/external/libvorbisidec-1.2.1/block.c -o /Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/build/SDL_mixer.build/Release-iphonesimulator/Static\ Library.build/Objects-normal/i386/block.o
In file included from /Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/external/libvorbisidec-1.2.1/block.c:27:
/Users/andrew/kivy-ios/build/sdl2_mixer/i386/SDL2_mixer-2.0.0/Xcode-iOS/../external/libvorbisidec-1.2.1/misc.h:33:10: fatal error: 
      'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.

I have no idea how to fix this error within the kivy-ios system.  Any help would be welcome.
Thanks.

**Comment by dwoods** [comment]
I had this same issue.  The problem ended up being that I was using a case-sensitive filesystem. 

The only way I was able to fix this was to re-install MacOS using the case-insensitive filesystem.

**Comment by llamawright** [comment]
Thanks for response.  I also had to reinstall for the same reason.  However, I also had to change line:
#include <endian.h>  
  to  
#include <machine/endian.h>
  in file misc.h  which seems to have done the trick.
