### ISSUE TITLE
App Quitting When Clicking 

### ISSUE THREAD

**Issue by Hyped-247** [kivy/kivy-ios#272]
I have been trying to turn a kivy app to exe file using pyinstaller, but it keeps giving me errors. I have done exactly what I must do as it states on the [website](https://kivy.org/docs/guide/packaging-osx.html#additional-libraries). 
I am using: 
`Mac mini (Late 2014)`
`2.6 GHz Intel Core i5`
`Version 10.12.6`
`python 3.6.1`
`PyInstaller: 3.3`
`Platform: Darwin-16.7.0-x86_64-i386-64bit`
`kivy 1.10.1`

Here is what my main.py looks like: 
```

import kivy
kivy.require('1.0.6') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):

    def build(self):
        return Label(text='Hello world')
if __name__ == '__main__':
    MyApp().run()

```
I have used pyinstaller to run the following command: 
`
pyinstaller -y --clean --windowed --name simple \
  --exclude-module _tkinter \
  --exclude-module Tkinter \
  --exclude-module enchant \
  --exclude-module twisted \
  main.py
`
And it keeps giving me this error:
![screen shot 2017-11-10 at 2 52 24 pm](https://user-images.githubusercontent.com/28418995/32681932-ca91326e-c626-11e7-818d-69b9f68c0e71.png)

I have tried to ignore it, and just keep doing what is said on the [website](https://kivy.org/docs/guide/packaging-osx.html#additional-libraries). That is, adding the tree object: 

`
coll = COLLECT(exe,
               Tree('/Users/mohammadmohjoub/PycharmProjects/Kivy'), 
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='simple')
`
and running the following command: 
`pyinstaller -y --clean --windowed simple.spec`

Now it made it worst because I got the same error that I had above, and this new error: 
` WARNING: stderr: FileNotFoundError: [Errno 2] No such file or directory: '/Users/mohammadmohjoub/PycharmProjects/Kivy/dist/simple.app/Contents/Resources/lib2to3/Grammar.txt'`

![screen shot 2017-11-10 at 3 02 14 pm](https://user-images.githubusercontent.com/28418995/32682244-5d553360-c628-11e7-8153-bb0702de02fa.png)

What is the reason for `ModuleNotFoundError` error, and the ` FileNotFoundError` error? Is this is why every time I try to open the app it just closes immediately? If that is not the reason, then how can I build the app in a way that doesn't make it close unexpectedly? I have been trying to fix this for weeks. I would really appreciate any kind of support.

**Comment by Zen-CODE** [comment]
This does not seem to be related to kivy-ios, as for ios, you cannot use pyinstaller. If you are still experiencing issues, perhaps ask on the kivy forums or the pyinstaller forums?

https://groups.google.com/forum/#!forum/kivy-users
