### ISSUE TITLE
Build ios for armv7 - architecture not supported

### ISSUE THREAD

**Issue by AlexKordic** [kivy/kivy-ios#273]
kivy.__version__ '1.10.1.dev0'
Cython version 0.27.2
MAC OS 10.13.1 (17B48)
XCODE Version 9.1 (9B55)

In compile command:

	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -arch armv7 -pipe -no-cpp-precomp --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk -O3 -miphoneos-version-min=6.0.0 -I/usr/local/perun/kivy-ios/dist/include/armv7/freetype -I/usr/local/perun/kivy-ios/dist/include/armv7/hostlibffi -I/usr/local/perun/kivy-ios/dist/include/armv7/libffi -I/usr/local/perun/kivy-ios/dist/include/common/sdl2 -I/usr/local/perun/kivy-ios/dist/include/common/sdl2_image -I/usr/local/perun/kivy-ios/dist/include/common/sdl2_mixer -I/usr/local/perun/kivy-ios/dist/include/common/sdl2_ttf -arch i386 -arch x86_64 -pipe -g -I/usr/local/perun/kivy-ios/dist/hostpython/include/python2.7 -I/usr/include/python2.7 -c ios.c -o build/temp.macosx-10.13-x86_64-2.7/ios.o

There are multiple `-arch` commands: -arch armv7 -arch i386 -arch x86_64 .  How to eliminate `-arch i386 -arch x86_64` from `Build ios for armv7` step ?

Full make output:

	./toolchain.py build kivy
	Building with 8 processes, where supported
	Want to build ['kivy']
	Loaded recipe kivy (depends of ['python', 'sdl2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'ios', 'pyobjus'], optional are [])
	Loaded recipe python (depends of ['hostpython', 'libffi'], optional are ['openssl'])
	Loaded recipe sdl2 (depends of [], optional are [])
	Loaded recipe sdl2_image (depends of ['sdl2'], optional are [])
	Loaded recipe sdl2_mixer (depends of ['sdl2'], optional are [])
	Loaded recipe sdl2_ttf (depends of ['sdl2', 'freetype'], optional are [])
	Loaded recipe ios (depends of ['python'], optional are [])
	Loaded recipe pyobjus (depends of ['python'], optional are [])
	Loaded recipe hostpython (depends of ['hostlibffi'], optional are ['openssl'])
	Loaded recipe libffi (depends of [], optional are [])
	Loaded recipe freetype (depends of [], optional are [])
	Loaded recipe hostlibffi (depends of [], optional are [])
	Build order is ['freetype', 'hostlibffi', 'libffi', 'sdl2', 'hostpython', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python', 'ios', 'pyobjus', 'kivy']
	Include dir added: {arch.arch}/freetype
	Include dir added: {arch.arch}/hostlibffi
	Include dir added: {arch.arch}/libffi
	Include dir added: common/sdl2
	Global: hostpython located at /usr/local/perun/kivy-ios/dist/hostpython/bin/python
	Global: hostpgen located at /usr/local/perun/kivy-ios/dist/hostpython/bin/pgen
	Include dir added: common/sdl2_image
	Include dir added: common/sdl2_mixer
	Include dir added: common/sdl2_ttf
	# (ignored) Download freetype
	# (ignored) Extract freetype
	# (ignored) Build_all freetype
	# (ignored) Download hostlibffi
	# (ignored) Extract hostlibffi
	Build hostlibffi for x86_64 (filtered)
	# (ignored) Build hostlibffi
	# (ignored) Download libffi
	# (ignored) Extract libffi
	# (ignored) Build_all libffi
	# (ignored) Download sdl2
	# (ignored) Extract sdl2
	# (ignored) Build_all sdl2
	# (ignored) Download hostpython
	# (ignored) Extract hostpython
	# (ignored) Build_all hostpython
	# (ignored) Download sdl2_image
	# (ignored) Extract sdl2_image
	# (ignored) Build_all sdl2_image
	# (ignored) Download sdl2_mixer
	# (ignored) Extract sdl2_mixer
	# (ignored) Build_all sdl2_mixer
	# (ignored) Download sdl2_ttf
	# (ignored) Extract sdl2_ttf
	# (ignored) Build_all sdl2_ttf
	# (ignored) Download python
	# (ignored) Extract python
	# (ignored) Build_all python
	# (ignored) Download ios
	# (ignored) Extract ios
	Build_all ios
	Build ios for i386, x86_64, armv7, arm64 (filtered)
	# (ignored) Build ios
	# (ignored) Build ios
	Build ios
	Warning: ios build for armv7 has been incomplete
	Warning: deleting the build and restarting.
	Prebuild ios for armv7
	Build ios for armv7
	Cythonize ios.pyx
	('-- cythonize', ['/usr/local/perun/kivy-ios/tools/cythonize.py', 'ios.pyx'])
	('cythonize:', 'ios.pyx')
	('no need to rewrite', 'ios.pyx')
	running build_ext
	building 'ios' extension
	creating build
	creating build/temp.macosx-10.13-x86_64-2.7
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -arch armv7 -pipe -no-cpp-precomp --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk -O3 -miphoneos-version-min=6.0.0 -I/usr/local/perun/kivy-ios/dist/include/armv7/freetype -I/usr/local/perun/kivy-ios/dist/include/armv7/hostlibffi -I/usr/local/perun/kivy-ios/dist/include/armv7/libffi -I/usr/local/perun/kivy-ios/dist/include/common/sdl2 -I/usr/local/perun/kivy-ios/dist/include/common/sdl2_image -I/usr/local/perun/kivy-ios/dist/include/common/sdl2_mixer -I/usr/local/perun/kivy-ios/dist/include/common/sdl2_ttf -arch i386 -arch x86_64 -pipe -g -I/usr/local/perun/kivy-ios/dist/hostpython/include/python2.7 -I/usr/include/python2.7 -c ios.c -o build/temp.macosx-10.13-x86_64-2.7/ios.o
	In file included from ios.c:4:
	In file included from /usr/local/perun/kivy-ios/dist/hostpython/include/python2.7/Python.h:19:
	In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/limits.h:37:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/limits.h:63:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/cdefs.h:761:2: error: 
	      Unsupported architecture
	#error Unsupported architecture
	 ^
	In file included from ios.c:4:
	In file included from /usr/local/perun/kivy-ios/dist/hostpython/include/python2.7/Python.h:19:
	In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/limits.h:37:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/limits.h:64:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/machine/limits.h:8:2: error: 
	      architecture not supported
	#error architecture not supported
	 ^
	In file included from ios.c:4:
	In file included from /usr/local/perun/kivy-ios/dist/hostpython/include/python2.7/Python.h:33:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/stdio.h:67:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/_types.h:27:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:33:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/machine/_types.h:34:2: error: 
	      architecture not supported
	#error architecture not supported
	 ^
	In file included from ios.c:4:
	In file included from /usr/local/perun/kivy-ios/dist/hostpython/include/python2.7/Python.h:33:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/stdio.h:67:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/_types.h:27:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:55:9: error: 
	      unknown type name '__int64_t'
	typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:56:9: error: 
	      unknown type name '__int32_t'
	typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:57:9: error: 
	      unknown type name '__int32_t'
	typedef __int32_t       __darwin_dev_t;         /* dev_t */
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:60:9: error: 
	      unknown type name '__uint32_t'
	typedef __uint32_t      __darwin_gid_t;         /* [???] process and gro...
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:61:9: error: 
	      unknown type name '__uint32_t'
	typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, o...
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:62:9: error: 
	      unknown type name '__uint64_t'
	typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bi...
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:68:9: error: 
	      unknown type name '__darwin_natural_t'
	typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:70:9: error: 
	      unknown type name '__uint16_t'
	typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:71:9: error: 
	      unknown type name '__int64_t'
	typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:72:9: error: 
	      unknown type name '__int32_t'
	typedef __int32_t       __darwin_pid_t;         /* [???] process and gro...
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:73:9: error: 
	      unknown type name '__uint32_t'
	typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:74:9: error: 
	      unknown type name '__int32_t'
	typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:75:9: error: 
	      unknown type name '__uint32_t'
	typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types.h:76:9: error: 
	      unknown type name '__uint32_t'
	typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
	        ^
	In file included from ios.c:4:
	In file included from /usr/local/perun/kivy-ios/dist/hostpython/include/python2.7/Python.h:33:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/stdio.h:71:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types/_va_list.h:31:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/machine/types.h:37:2: error: 
	      architecture not supported
	#error architecture not supported
	 ^
	In file included from ios.c:4:
	In file included from /usr/local/perun/kivy-ios/dist/hostpython/include/python2.7/Python.h:33:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/stdio.h:71:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/sys/_types/_va_list.h:32:9: error: 
	      unknown type name '__darwin_va_list'; did you mean '__builtin_va_list'?
	typedef __darwin_va_list va_list;
	        ^
	note: '__builtin_va_list' declared here
	fatal error: too many errors emitted, stopping now [-ferror-limit=]
	20 errors generated.
	error: command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang' failed with exit status 1
	Traceback (most recent call last):
	  File "./toolchain.py", line 1365, in <module>
	    ToolchainCL()
	  File "./toolchain.py", line 1114, in __init__
	    getattr(self, args.command)()
	  File "./toolchain.py", line 1155, in build
	    build_recipes(args.recipe, ctx)
	  File "./toolchain.py", line 1005, in build_recipes
	    recipe.execute()
	  File "/usr/local/perun/kivy-ios/toolchain.py", line 615, in execute
	    self.build_all()
	  File "/usr/local/perun/kivy-ios/toolchain.py", line 56, in _cache_execution
	    f(self, *args, **kwargs)
	  File "/usr/local/perun/kivy-ios/toolchain.py", line 704, in build_all
	    self.build(arch)
	  File "/usr/local/perun/kivy-ios/toolchain.py", line 56, in _cache_execution
	    f(self, *args, **kwargs)
	  File "/usr/local/perun/kivy-ios/toolchain.py", line 691, in build
	    self.build_arch(arch)
	  File "/usr/local/perun/kivy-ios/toolchain.py", line 963, in build_arch
	    _env=build_env)
	  File "/usr/local/perun/kivy-ios/toolchain.py", line 39, in shprint
	    for line in command(*args, **kwargs):
	  File "./tools/external/sh.py", line 565, in next
	    self.wait()
	  File "./tools/external/sh.py", line 500, in wait
	    self.handle_command_exit_code(exit_code)
	  File "./tools/external/sh.py", line 516, in handle_command_exit_code
	    raise exc(self.ran, self.process.stdout, self.process.stderr)
	sh.ErrorReturnCode_1: 

	  RAN: '/usr/local/perun/kivy-ios/dist/hostpython/bin/python setup.py build_ext -g'

	  STDOUT:
	running build_ext
	building 'ios' extension
	creating build
	creating build/temp.macosx-10.13-x86_64-2.7
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -arch armv7 -pipe -no-cpp-precomp --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk -O3 -miphoneos-version-min=6.0.0 -I/usr/local/perun/kivy-ios/dist/include/armv7/freetype -I/usr/local/perun/kivy-ios/dist/include/armv7/hostlibffi -I/usr/local/perun/kivy-ios/dist/include/armv7/libffi -I/usr/local/perun/kivy-ios/dist/include/common/sdl2 -I/usr/local/perun/kivy-ios/dist/include/common/sdl2_image -I/usr/local/perun/kivy-ios/dist/include/comm... (7862 more, please see e.stdout)

	  STDERR:

Env:

	$ env
	TERM_PROGRAM=Apple_Terminal
	SHELL=/bin/bash
	TERM=xterm-256color
	TMPDIR=/var/folders/gb/vttxhpxs6ll67ymkzq9_n998n07mkg/T/
	Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.SAsDLKIfN7/Render
	TERM_PROGRAM_VERSION=400
	TERM_SESSION_ID=B6193111-EC57-4260-9068-7BE7EDF42933
	USER=alexxxxx
	SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.l4xrCScmzL/Listeners
	PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
	LANG=en_GB.UTF-8
	XPC_FLAGS=0x0
	XPC_SERVICE_NAME=0
	SHLVL=1
	HOME=/Users/alexxxxx
	LOGNAME= alexxxxx
	SECURITYSESSIONID=186a7
	_=/usr/bin/env

**Comment by tito** [comment]
armv7 works on master with XCode 10.1
