### ISSUE TITLE
Apps loses sound after phone call or Siri

### ISSUE THREAD

**Issue by sastels** [kivy/kivy-ios#274]
from https://github.com/kivy/kivy/issues/5501

Apps on iOS lose sound permanently after engaging Siri or using the telephone. Need to kill and restart app to get sound again.

Problem is twofold:
* kivy-ios is currently using an old development fork of SDL rather than the latest release.
* the latest SDL release fixes the problem for Siri but not for phone calls. (see https://discourse.libsdl.org/t/getting-back-audio-after-phone-call-on-ios-and-sdl-2-0-5/22144/6) This has to be fixed in the SDL library, then (presumably) it will work in kivy-ios.

Once we get things fixed in SDL I'll put in a PR for kivy-ios that uses a version of SDL that fixes the issue.

**Comment by Zen-CODE** [comment]
Please re-open if this is still and issue. And please include code that demonstrates the issue? i.e. How and where are you loading audio? Thanks.
