### ISSUE TITLE
ios chinese or japanese keyboard not work

### ISSUE THREAD

**Issue by d0kyuan** [kivy/kivy-ios#279]
when i use en keyboard , windows.request_keyboard on_keyboard_down  output was right like :
```
('The key', (107, 'k'), 'have been pressed')
 - text is u'k'
 - modifiers are []
```
but when i use jp or ch keyboard event cant get any feedback

**Comment by Zen-CODE** [comment]
Testing with the current version of kivy-ios (using kivy 2.0.0rc1), I am able to generate and receive keyboard input on the iOS simulator using the Chinese keyboard. It is possible this issue has been fixed already.

If you still experience the issue, please re-open with test code (a runnable example) that reproduces the issue.

Thanks
