### ISSUE TITLE
Opencv recipe

### ISSUE THREAD

**Issue by aliericcantona** [kivy/kivy-ios#284]
Do you know how can I use opencv python on ios using kivy-ios?
there is no recipe for that.

**Comment by GoBig87** [comment]
Not sure if you still need opencv but It looks like I'll need to use opencv too.  I've already written recipes for libiconv, libzbar, zbar and zbarlight might as well add opencv to the list too!

**Comment by GoBig87** [comment]
After digging further into what my app needed for the camera I was able to just use the AVfoundation with out the need of openCV.  I started work on a openCV recipe but it was little tougher than other recipes and some one with more experience might need to work on it.
