### ISSUE TITLE
Force Camera orientation and enable autofocus

### ISSUE THREAD

**Issue by GoBig87** [kivy/kivy-ios#290]
I've recently got zbarcam working with ios and one of the things that needs fixed is that the camera is flipping and isn't the right orientation that I need.  What would be the best way to implement this?  The garden xcamera has a good example of how to do this with pyjnius but androids seems like its a lot easier to play with the device internals.  Would I be able to do something similar with pyobjus? Or should I try and wrap obj-c like the camera_avfoundation code that enables the camera?  I plan on doing the coding I just need some direction on which way to go.

**Comment by AndreMiras** [comment]
I'm cheating it on Android too, see https://github.com/kivy-garden/garden.zbarcam/blob/20171220/zbarcam/zbarcam.kv#L22
So probably we want to include ios in that cheat. I let you give a try and come up with a PR for garden.zbarcam

**Comment by GoBig87** [comment]
Camera is fixed with this https://github.com/kivy/kivy/pull/6156. Closing issue.
