### ISSUE TITLE
UnboundLocalError: local variable 'iterkeys' referenced before assignment

### ISSUE THREAD

**Issue by zycool** [kivy/kivy-ios#294]
python kivy-ios/toolchain.py create xxx ~/Documents/2018/KivyWorkPlace/xiaoqiang/
Include dir added: {arch.arch}/freetype
Global: hostpython located at /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/hostpython/bin/python
Global: hostpgen located at /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/hostpython/bin/pgen
Include dir added: {arch.arch}/libffi
Include dir added: common/sdl2
Include dir added: common/sdl2_image
Include dir added: common/sdl2_mixer
Include dir added: common/sdl2_ttf
----------------------------------------------------------------------
The project need to have:
iOS Frameworks: ['AudioToolbox', 'ImageIO', 'MessageUI', 'UIKit', 'OpenGLES', 'CoreMotion', 'MobileCoreServices', 'CoreGraphics', 'Accelerate', 'QuartzCore']
iOS Libraries: ['libc++', 'libz', 'libsqlite3', 'libbz2']
iOS local Frameworks: []
Libraries: ['/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libios.a', '/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libsdl2.a', '/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libsdl2_ttf.a', '/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libpython.a', '/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libfreetype.a', '/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libsdl2_image.a', '/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libsdl2_mixer.a', '/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libpyobjus.a', '/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libkivy.a', '/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libffi.a']
Sources to link: []
----------------------------------------------------------------------
Analysis of /Users/neo/Documents/2018/KivyWorkPlace/xxx-ios/xxx.xcodeproj/project.pbxproj
Ensure AudioToolbox is in the project (system)
Ensure ImageIO is in the project (system)
Ensure MessageUI is in the project (system)
Ensure UIKit is in the project (system)
Ensure OpenGLES is in the project (system)
Ensure CoreMotion is in the project (system)
Ensure MobileCoreServices is in the project (system)
Ensure CoreGraphics is in the project (system)
Ensure Accelerate is in the project (system)
Ensure QuartzCore is in the project (system)
Ensure libc++ is in the project
Ensure libz is in the project
Ensure libsqlite3 is in the project
Ensure libbz2 is in the project
Ensure /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libios.a is in the project
Ensure /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libsdl2.a is in the project
Ensure /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libsdl2_ttf.a is in the project
Ensure /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libpython.a is in the project
Ensure /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libfreetype.a is in the project
Ensure /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libsdl2_image.a is in the project
Ensure /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libsdl2_mixer.a is in the project
Ensure /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libpyobjus.a is in the project
Ensure /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libkivy.a is in the project
Ensure /Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/dist/lib/libffi.a is in the project
Traceback (most recent call last):
  File "kivy-ios/toolchain.py", line 1368, in <module>
    ToolchainCL()
  File "kivy-ios/toolchain.py", line 1114, in __init__
    getattr(self, args.command)()
  File "kivy-ios/toolchain.py", line 1248, in create
    update_pbxproj(filename)
  File "kivy-ios/toolchain.py", line 1081, in update_pbxproj
    project.save()
  File "/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/tools/external/mod_pbxproj.py", line 1197, in save
    self.saveFormat3_2(file_name)
  File "/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/tools/external/mod_pbxproj.py", line 1201, in saveFormat3_2
    self.save_new_format(file_name)
  File "/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/tools/external/mod_pbxproj.py", line 1263, in save_new_format
    self._printNewXCodeFormat(out, self.data, '', enters=True)
  File "/Users/neo/Documents/2018/KivyWorkPlace/kivy-ios/tools/external/mod_pbxproj.py", line 1300, in _printNewXCodeFormat
    for key in sorted(iterkeys):  # keep the same order as Apple.
UnboundLocalError: local variable 'iterkeys' referenced before assignment

**Comment by zycool** [comment]
in 
kivy-ios/tools/external/mod_pbxproj.py   1300

            try:
                iterKeys = root.iterkeys()
            except:
                # python 3 support
                iterkeys = root.keys()

**Comment by pauloqnx** [comment]
I have the same problema! Do you have success?

**Comment by tito** [comment]
mod_pbxproj got removed and using the latest version, require to handle new extension for XCode 10. 
Latest mod_pbxproj requires python 3 installed on the system first :/
