### ISSUE TITLE
Include Unit tests and CI to test build for the toolchain

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy-ios#296]
- [ ] Unit tests
- [ ] CI Build test for Python2.7
- [ ] CI Build test for Python 3.7

**Comment by Zen-CODE** [comment]
Hi. A lot of work has been done adding CI. See https://github.com/kivy/kivy-ios/tree/master/.ci

And unit tests are a bit vague? I think it would help if we could break this down into more actionable and exact tickets? Thanks

**Comment by Julian-O** [comment]
No reply after 3 years. Closing as stale.
