### ISSUE TITLE
Pip doesn't install in the right location when using python3

### ISSUE THREAD

**Issue by irreverentperson** [kivy/kivy-ios#298]
ivy app fails on launch and says no module named requests.
I have tried putting requests into my project directory and still the same.

./toolchain.py recipe for requests?
is there another workaround?

**Comment by tito** [comment]
`./toolchain.py pip install requests`

**Comment by jefcolbi** [comment]
> `./toolchain.py pip install requests`

depending of the version of python you use when building the toolchain you have error.
if you build with python2 then it is ok
but if you build with python3 then pip will install requests in the python2/site-packages directory so one have to manually copy them to python3/site-packages.
these directories are located in dist/root/python3/lib

**Comment by tito** [comment]
That's a issue ok

**Comment by hackalog** [comment]
I think this should be fixed since https://github.com/kivy/kivy-ios/pull/325 was merged. @irreverentperson  can you try the latest kivy-ios?

**Comment by Zen-CODE** [comment]
Appears to be fixed? Please re-open if not.
