### ISSUE TITLE
toolkit build error libffi

### ISSUE THREAD

**Issue by heatherbaroody** [kivy/kivy-ios#299]
Hi, I'm having an issue when I go to ./toolchain.py build kivy that is preventing me from creating a package for IOS for my kivy app. Here is my build log:
[buildLog.txt](https://github.com/kivy/kivy-ios/files/2439958/buildLog.txt)

And here is the config.log:
 `$ more /Users/heather//kivy-ios/build/hostlibffi/x86_64/libffi-3.2.1/build_macosx-i386/config.log
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by libffi configure 3.2.1, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ../configure -host i386-apple-darwin10

## --------- ##

hostname = Heathers-MacBook-Pro.local
uname -m = x86_64
uname -r = 17.7.0
uname -s = Darwin
uname -v = Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
         Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Kernel configured for up to 4 processors.
2 processors are physically available.
4 processors are logically available.
Processor type: i486 (Intel 80486)
Processors active: 0 1 2 3
Primary memory available: 8.00 gigabytes
Default processor set: 354 tasks, 1540 threads, 4 processors
Load average: 4.70, Mach factor: 0.76
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/gnu/bin
PATH: /usr/local/bin
PATH: /bin
PATH: /usr/bin
PATH: .

## ----------- ##

configure:2745: checking build system type
configure:2759: result: i386-apple-darwin17.7.0
configure:2779: checking host system type
configure:2792: result: i386-apple-darwin10
configure:2812: checking target system type
configure:2825: result: i386-apple-darwin10
configure:2922: checking for gsed
configure:2953: result: sed
configure:2981: checking for a BSD-compatible install
configure:3049: result: /usr/bin/install -c
configure:3060: checking whether build environment is sane
configure:3115: result: yes
configure:3171: checking for i386-apple-darwin10-strip
configure:3201: result: no
configure:3211: checking for strip
configure:3227: found /usr/bin/strip
configure:3238: result: strip
configure:3263: checking for a thread-safe mkdir -p
configure:3302: result: ../install-sh -c -d
configure:3309: checking for gawk
configure:3339: result: no
configure:3309: checking for mawk
configure:3339: result: no
configure:3309: checking for nawk
configure:3339: result: no
configure:3309: checking for awk
configure:3325: found /usr/bin/awk
configure:3336: result: awk
configure:3347: checking whether make sets $(MAKE)
configure:3369: result: yes
configure:3398: checking whether make supports nested variables
configure:3415: result: yes
configure:3518: checking for i386-apple-darwin10-gcc
configure:3545: result: xcrun -sdk macosx clang -arch i386
configure:3814: checking for C compiler version
configure:3823: xcrun -sdk macosx clang -arch i386 --version >&5
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: i386-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:3834: $? = 0
configure:3823: xcrun -sdk macosx clang -arch i386 -v >&5
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: i386-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:3834: $? = 0
configure:3823: xcrun -sdk macosx clang -arch i386 -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3834: $? = 1
configure:3823: xcrun -sdk macosx clang -arch i386 -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:3834: $? = 1
configure:3854: checking whether the C compiler works
configure:3876: xcrun -sdk macosx clang -arch i386 -mmacosx-version-min=10.6   conftest.c  >&5
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
  "_exit", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3880: $? = 1
configure:3918: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libffi"
| #define PACKAGE_TARNAME "libffi"
| #define PACKAGE_VERSION "3.2.1"
| #define PACKAGE_STRING "libffi 3.2.1"
| #define PACKAGE_BUGREPORT "http://github.com/atgreen/libffi/issues"
| #define PACKAGE_URL ""
| #define PACKAGE "libffi"
| #define VERSION "3.2.1"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3923: error: in `/Users/heather/kivy-ios/build/hostlibffi/x86_64/libffi-3.2.1/build_macosx-i386':
configure:3925: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_build=i386-apple-darwin17.7.0
ac_cv_env_CCASFLAGS_set=
ac_cv_env_CCASFLAGS_value=
ac_cv_env_CCAS_set=
ac_cv_env_CCAS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
:
`
Many thanks for any help!

**Comment by dacb** [comment]
I'm having a similar problem.

**Comment by hypherion2** [comment]
Yup, XCode 10 no longer allows building i386 architectures.

**Comment by heatherbaroody** [comment]
> Yup, XCode 10 no longer allows building i386 architectures.

Lame, any suggestions on getting kivy app to iphone?

**Comment by HeaTTheatR** [comment]
I'm having a similar problem.

**Comment by PhilippeLandry-Logient** [comment]
Same problem here, the future  doesn't look good for kivy-ios

**Comment by tito** [comment]
I'm on it.

**Comment by rickdps** [comment]
Thank you very much for your efforts, Mathieu.

**Comment by tito** [comment]
hostlibffi is fixed in master, as well as libffi. But python can't compile yet for another reason. Still checking.

**Comment by sgpy** [comment]
@tito Any update? I am not sure why this happens, but will you mind sharing here?
