### ISSUE TITLE
How to create a package for iOS?

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy-ios#300]
I compiled kivy-ios, Python and all dependencies (./toolchain.py build kivy). Created a project in XCode, linked missing libraries and launched the project with the "Play" button in XCode. Got a message - "Build Successful", IOS emulator was launched, in which my application was opened. What should I do now to get the package for iOS?

**Comment by tito** [comment]
After a talk to discord, we've seen it can be many thing, and you go step by step.
