### ISSUE TITLE
STDERR building kivy

### ISSUE THREAD

**Issue by irreverentperson** [kivy/kivy-ios#308]
macOS 10.13.6 High Sierra Xcode 10.1

./toolchain.py build kivy
warning: Traditional headermap style is no longer supported: please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'libSDL-IOS')

CreateBuildDirectory /Users/... (19989 more, please see e.stdout)

STDERR:

**Comment by tito** [comment]
It's not about building kivy, but SDL2. It has been reported in #302
