### ISSUE TITLE
kivy-ios/dist/hostpython2/bin/python: No such file or directory

### ISSUE THREAD

**Issue by irreverentperson** [kivy/kivy-ios#312]
MacOS 10.13.6
Xcode 10.1

Just recloned kivy-ios and did clean install of everything, linked libraries, disabled bitcode.
When i hit play in xcode i get the following error.

`/Users/jim/Library/Developer/Xcode/DerivedData/tester-epnmulbhkafyfbdrxbfkcscnxfwh/Build/Intermediates.noindex/tester.build/Debug-iphoneos/tester.build/Script-113D17E2153E3DB5001310A6.sh: line 2: /Users/jim/kivy-ios/dist/hostpython2/bin/python: No such file or directory `

**Comment by tito** [comment]
It works if you have specified the python version in the ./toolchain.py. Did you?
Can you show all the command ./toolchain you did?

**Comment by irreverentperson** [comment]
this time i did:
./toolchain.py build openssl
./toolchain.py build kivy
I'm using python 2.7.
Can you tell me what command/order i should build in?
Should i edit the first line of ./toolcain.py before the build?

Really excited... Seems like i've almost got it.
