### ISSUE TITLE
App store validation fails due to .so.o files

### ISSUE THREAD

**Issue by cruor99** [kivy/kivy-ios#315]
As per the discussion on Discord yesterday, I went back and did some more specific app store validation - I realized that the birdflight system I've been sending things through to my internal people didn't validate in the same way the app store does.

https://i.imgur.com/YcegQ8B.png

Apparently it reacts like this for basically all the .so.o files built by Kivy and Pyobjus.

Let me know if there's anything specific I can do to assist.

Edit: I should specify, it doesn't show anything for the .so files in the log. Only .so.o files.

**Comment by cruor99** [comment]
An interesting update: I merely deleted the .so.o files, and the app still ran without issues. 
This then made it pass validation, and was successfully uploaded as a build to appstoreconnect and is now in active use among my beta testers.

I curiously did not run into the same issues as #306.

**Comment by Dirk-Sandberg** [comment]
Hey, I'm the one who opened #306. I think my issue might be with how I'm trying to include the python modules i'm using (like requests, PIL, etc...). How did you include the modules you used? I had copied them from where they were downloaded into the folder with my main application so they'd be a part of the kivy project. Maybe send me a private message if you're willing to help a bit? Much appreciated!

**Comment by hackalog** [comment]
@Dirk-Sandberg you should be able to install python-only modules using: `toolchain.py pip install requests` and so on.

For cython dependencies, you'll need to create a Recipe and use `toolchain.py build <module_name>`

If there is junk that you can just delete, buildozer should let you exclude those patterns with `source.exclude_patterns` (if you are using it).

**Comment by Dirk-Sandberg** [comment]
Any update on this? I'm about to try the solution of removing the .so.o files from my site-packages folder, but I feel like that's not ideal. Running into this using kivy-ios downloaded from github just a couple days ago (Feb 2019). Built with python2 and on macOS 10.13.6

**Comment by Zen-CODE** [comment]
So, with reference to this issue: https://github.com/kivy/kivy-ios/issues/193.

The linked commit fixed the issue, but only removes the "so.o" files from the python site-packages folder. Perhaps this needs to be updated to also clean the app folder? @Dirk-Sandberg Please can you try building with python3 using the latest checkout and see if the problem persists?
