### ISSUE TITLE
Xcode10.1 can not build app 

### ISSUE THREAD

**Issue by tamano123** [kivy/kivy-ios#317]
Hello,
Thank you for all your efforts.

My configuration : Macos 10.13.6 and Xcode 10.1, I have cloned the latest version of kivy-ios 

I got this error when trying to build my project. here's the log of Xcode :

`Ld /Users/macos/Library/Developer/Xcode/DerivedData/project-ftslwhrdtpwrrodapnbtenhepcgp/Build/Intermediates.noindex/project.build/Debug-iphonesimulator/project.build/Objects-normal/i386/project normal i386 (in target: project)
cd /Users/macos/kivy-ios/project-ios
export IPHONEOS_DEPLOYMENT_TARGET=8.1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -L/Users/macos/Library/Developer/Xcode/DerivedData/project-ftslwhrdtpwrrodapnbtenhepcgp/Build/Products/Debug-iphonesimulator -L/Users/macos/kivy-ios/dist/lib -L/Users/macos/kivy-ios/project-ios/../dist/lib -F/Users/macos/Library/Developer/Xcode/DerivedData/project-ftslwhrdtpwrrodapnbtenhepcgp/Build/Products/Debug-iphonesimulator -F/Users/macos/kivy-ios/dist/frameworks -filelist /Users/macos/Library/Developer/Xcode/DerivedData/project-ftslwhrdtpwrrodapnbtenhepcgp/Build/Intermediates.noindex/project.build/Debug-iphonesimulator/project.build/Objects-normal/i386/project.LinkFileList -mios-simulator-version-min=8.1 -Xlinker -object_path_lto -Xlinker /Users/macos/Library/Developer/Xcode/DerivedData/project-ftslwhrdtpwrrodapnbtenhepcgp/Build/Intermediates.noindex/project.build/Debug-iphonesimulator/project.build/Objects-normal/i386/project_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -all_load -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/macos/Library/Developer/Xcode/DerivedData/project-ftslwhrdtpwrrodapnbtenhepcgp/Build/Intermediates.noindex/project.build/Debug-iphonesimulator/project.build/project.app-Simulated.xcent -framework CoreGraphics -framework OpenGLES -framework MobileCoreServices -framework Metal -framework QuartzCore -framework GameController -framework AVFoundation -framework MessageUI -framework Accelerate -framework ImageIO -framework UIKit -framework CoreMotion -framework AudioToolbox -lbz2 -lc++ -lz -lsqlite3 -lsdl2_ttf -lffi -lfreetype -lsdl2 -lsdl2_image -lssl -lpyobjus -lpython3 -lsdl2_mixer -lkivy -lcrypto -lios -Xlinker -dependency_info -Xlinker /Users/macos/Library/Developer/Xcode/DerivedData/project-ftslwhrdtpwrrodapnbtenhepcgp/Build/Intermediates.noindex/project.build/Debug-iphonesimulator/project.build/Objects-normal/i386/project_dependency_info.dat -o /Users/macos/Library/Developer/Xcode/DerivedData/project-ftslwhrdtpwrrodapnbtenhepcgp/Build/Intermediates.noindex/project.build/Debug-iphonesimulator/project.build/Objects-normal/i386/project

ld: warning: directory not found for option '-F/Users/macos/kivy-ios/dist/frameworks'
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libsdl2_ttf.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libsdl2_ttf.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libffi.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libffi.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libfreetype.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libfreetype.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libsdl2.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libsdl2.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libsdl2_image.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libsdl2_image.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libssl.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libssl.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libpyobjus.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libpyobjus.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libpython3.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libpython3.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libsdl2_mixer.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libsdl2_mixer.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libkivy.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libkivy.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libcrypto.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libcrypto.a (3 slices)
ld: warning: ignoring file /Users/macos/kivy-ios/dist/lib/libios.a, missing required architecture i386 in file /Users/macos/kivy-ios/dist/lib/libios.a (3 slices)
Undefined symbols for architecture i386:
"_PyEval_InitThreads", referenced from:
_SDL_main in main.o
"_PyMem_RawMalloc", referenced from:
_SDL_main in main.o
"_PyRun_SimpleFileExFlags", referenced from:
_SDL_main in main.o
"_PyRun_SimpleStringFlags", referenced from:
_load_custom_builtin_importer in main.o
"_PySys_SetArgv", referenced from:
_SDL_main in main.o
"_Py_DecodeLocale", referenced from:
_SDL_main in main.o
"_Py_Finalize", referenced from:
_SDL_main in main.o
"_Py_Initialize", referenced from:
_SDL_main in main.o
"_main", referenced from:
implicit entry/start for main executable
(maybe you meant: _SDL_main)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

thank you

**Comment by Dirk-Sandberg** [comment]
I'm seeing this same exact issue with MacOS 10.13.6 and Xcode 10.1. I tried to use Xcode 9.4.1 as well with the same error. Any ideas?

**Comment by heatherbaroody** [comment]
Me as well, same issue. Help is appreciated.

**Comment by hackalog** [comment]
Yes, @Dirk-Sandberg , @heatherbaroody this should now be fixed (as of https://github.com/kivy/kivy-ios/commit/271e235927ab39cf9f08e0d4f0736414a03392e8). XCode 10.1 seems to have dropped the i386 symbols, so removing that architecture appears to fix the issue.

Please try the latest kivy-ios and let us know if that worked.

**Comment by Dirk-Sandberg** [comment]
@hackalog Yep, grabbed the latest kivy-ios version and no longer ran into this issue. Tried to validate my App on the app store again and ran into #315 unfortunately. Haven't tried fixing it since I hit the error in 315 though.

**Comment by hackalog** [comment]
@Dirk-Sandberg: I left some possible workarounds on #315...

**Comment by heatherbaroody** [comment]
Thank you! I got to the next step too. and running into more problems that I'll see if I can Google first...
