### ISSUE TITLE
Kivy-iOS. Error importing modules and packages from the root directory

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy-ios#320]
There is such a structure of the application:

![2018-12-04 16 18 18](https://user-images.githubusercontent.com/16930280/49460705-0a86d900-f803-11e8-8e04-e896d33754e3.png)

**Source main.py:**

```python
from kivy.app import App
from kivy.uix.button import Button

# This module cannot be imported from the root catalog.
from module_in_home_directory import string_hello

print(string_hello)


class Test(App):
    def build(self):
        return Button()


Test().run()
```

**Source module_in_home_directory.py:**

```python
string_hello = 'Hello World'
```

An error is always returned, no matter what path I add to the sys.path:

```python
Traceback(most recent call last):
    File "/Users/macbookair/Opt/kivy-ios/helloworld-ios/YourApp/main.py", line 4, in < module >
  ModuleNotFoundError: No module named 'module_in_home_directory'
```

All image files, configs, modules are searched here - _**kivy-ios/dist/root/python3/lib**_

![2018-12-04 20 32 09](https://user-images.githubusercontent.com/16930280/49461081-f68fa700-f803-11e8-9488-cd9ea2c91ef6.png)

But should be searched here - _**kivy-ios/helloworld-ios/YourApp**_

![2018-12-04 20 36 42](https://user-images.githubusercontent.com/16930280/49461322-7158c200-f804-11e8-9b46-d04b229c2d83.png)

Before the introduction of the third branch of Python, there was no such problem.

**Comment by mwelzl** [comment]
+1, I'm experiencing this too

**Comment by cruor99** [comment]
A workaround for this, for me, was to add _applibs and the app root to the path, at the top of my main.py.
So:
```
import sys
sys.path.append("_applibs")
sys.path.append(".")```

**Comment by HeaTTheatR** [comment]
It not work!

сб, 29 дек. 2018 г. в 02:54, Kjetil Andre Liknes <notifications@github.com>:

**Comment by HeaTTheatR** [comment]
@cruor99 it not work!

**Comment by HeaTTheatR** [comment]
@cruor99 It work!
