### ISSUE TITLE
xcodebuild: error: invalid option '-exportFormat'

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy-ios#326]
I managed to fix this error - https://github.com/kivy/kivy-ios/issues/318. Apparently - this is a clear mistake in the project!

So!
Create new project:
```python
./toolchain.py create HelloWorld /Users/macbookair/Projects/HelloWorld
```
Open project and delete  section "Run Script":

![2018-12-29 8 21 45](https://user-images.githubusercontent.com/16930280/50533871-120c7a00-0b44-11e9-83e0-e48d4cf36ed6.png)

Next step:

```python
buildozer ios release
```

Get error:

```python
** ARCHIVE SUCCEEDED **

# Creating IPA...
# Run '/usr/bin/xcodebuild -exportArchive -exportFormat IPA -archivePath "/Users/macbookair/Projects/HelloWorld/.buildozer/ios/platform/kivy-ios/helloworld-0.1.intermediates/helloworld-0.1.xcarchive" -exportPath "/Users/macbookair/Projects/HelloWorld/.buildozer/ios/platform/kivy-ios/helloworld-0.1.intermediates/helloworld-0.1.ipa" CODE_SIGN_IDENTITY="iPhone Developer: Alena Troshina (J6PTLM7R57)" ENABLE_BITCODE=NO'
# Cwd /Users/macbookair/Projects/HelloWorld/.buildozer/ios/platform/kivy-ios/helloworld-ios

xcodebuild: error: invalid option '-exportFormat'
```

You can manually create a package from **helloworld-0.1.xcarchive** file 

![2018-12-29 8 34 32](https://user-images.githubusercontent.com/16930280/50533890-b1317180-0b44-11e9-9829-4326bfe35e6d.png)

but maybe there is a way to fix it in the project itself?

**Comment by hackalog** [comment]
I believe this is a buildozer issue. See here: https://github.com/kivy/buildozer/issues/559

**Comment by HeaTTheatR** [comment]
@hackalog Fixed in the very bulldozer:

**buildozer/targets/ios.py:**

![2019-01-05 16 46 30](https://user-images.githubusercontent.com/16930280/50725124-e6702d80-1109-11e9-94cc-f9e83f4fe7be.png)

**Comment by hackalog** [comment]
surely that couldn't have worked. At minimum, you should have gotten a 
```
 -exportOptionsPlist is required when specifying -exportArchive.
```
error
