### ISSUE TITLE
ios build but gives error and quits the app

### ISSUE THREAD

**Issue by ozc** [kivy/kivy-ios#328]
Managed to build kivy and created a simple test app. toolchain create worked flawlessly and created an Xcode project. With some small fixes, like symbolic linking python2 to python on some paths managed to run the app on a physical device (ipad). But it crashes after a black screen is shown.

Tried this on both a venv and a systemwide install. Still getting the same errors on both.

> 2019-01-05 15:50:03.008720+0300 testapp[3614:1866936] [DYMTLInitPlatform] platform initialization successful
> 2019-01-05 15:50:03.276743+0300 testapp[3614:1866741] [framework] CUIThemeStore: No theme registered with id=0
> 2019-01-05 15:50:03.408105+0300 testapp[3614:1866741] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
> 2019-01-05 15:50:03.408237+0300 testapp[3614:1866741] PythonHome is: /var/containers/Bundle/Application/D7B83AA3-9316-40BE-9514-45344446F0B6/testapp.app
> 2019-01-05 15:50:03.409164+0300 testapp[3614:1866741] Initializing python
> Traceback (most recent call last):
>   File "/Users/ozc/Development/kivy-test/kivy-ios/dist/root/python/lib/python2.7/site.py", line 553, in <module>
>   File "/Users/ozc/Development/kivy-test/kivy-ios/dist/root/python/lib/python2.7/site.py", line 535, in main
>   File "/Users/ozc/Development/kivy-test/kivy-ios/dist/root/python/lib/python2.7/site.py", line 268, in addusersitepackages
>   File "/Users/ozc/Development/kivy-test/kivy-ios/dist/root/python/lib/python2.7/site.py", line 243, in getusersitepackages
>   File "/Users/ozc/Development/kivy-test/kivy-ios/dist/root/python/lib/python2.7/site.py", line 233, in getuserbase
>   File "/Users/ozc/Development/kivy-test/kivy-ios/dist/root/python/lib/python2.7/sysconfig.py", line 535, in get_config_var
>   File "/Users/ozc/Development/kivy-test/kivy-ios/dist/root/python/lib/python2.7/sysconfig.py", line 434, in get_config_vars
>   File "/Users/ozc/Development/kivy-test/kivy-ios/dist/root/python/lib/python2.7/sysconfig.py", line 298, in _init_posix
> IOError: invalid Python installation: unable to open /var/containers/Bundle/Application/D7B83AA3-9316-40BE-9514-45344446F0B6/testapp.app/include/python2.7/pyconfig.h (No such file or directory)

**Comment by hackalog** [comment]
As mentioned on the other issue, I can confirm this

**Comment by tito** [comment]
drag and drop the dist/include folder into your Xcode project > resources root folder, and use "reference" folder when asked. It will do the trick until the template is fixed

**Comment by voicers** [comment]
![default](https://user-images.githubusercontent.com/38302724/51012655-354e1500-1599-11e9-9087-d21919349161.png)
@tito 
emmm.....,still exists

**Comment by hackalog** [comment]
Yes. I'm batting 50% too. One project worked, one failed with the missing includes, even with the latest changes.

**Comment by parthya** [comment]
@hackalog Is this the way you added the folder? I am facing the issue as well. 

![screen shot 2019-01-11 at 9 05 56 pm](https://user-images.githubusercontent.com/11842371/51043491-d0b8a780-15e4-11e9-9030-88ef0578bb4c.png)

Curiously, it works with Python3. But the we need 2.7 for the modules.

**Comment by hackalog** [comment]
Oh, I see the hostlibffi recipe has a hardcoded call to "python2.7" in it: https://github.com/kivy/kivy-ios/blob/7ee0d6ad64106b682fcba66cac32622762410fee/recipes/hostlibffi/__init__.py#L45-L46 .  That could explain some of the behavior differences between python 2 and 3 here

**Comment by hackalog** [comment]
@tito could we re-open this?
