### ISSUE TITLE
IOError: invalid Python installation ----pyconfig.h (No such file or directory)

### ISSUE THREAD

**Issue by voicers** [kivy/kivy-ios#330]
I managed to build  kivy-ios and myapp with xcode and  buildozer , while it gives following errors when I load the app with iphoneSimulator:

IOError: invalid Python installation: unable to open /var/containers/Bundle/Application/A1766F94-71E9-46C8-AE80-C6785E691C6F/myapp.app/include/python2.7/pyconfig.h (No such file or directory)

The same errors were given when I load  the app with my Iphone.Anyone knows why it happens and how to fix it?

**Comment by hackalog** [comment]
Yep. I can confirm this.

**Comment by hackalog** [comment]
See also #328 - same issue

**Comment by voicers** [comment]
I've met the same problem bro 😂.

**Comment by tito** [comment]
drag and drop the dist/include folder into your Xcode project > resources root folder, and use "reference" folder when asked. It will do the trick until the template is fixed
