### ISSUE TITLE
toolchain.py build pil fail 

### ISSUE THREAD

**Issue by ssolari** [kivy/kivy-ios#341]
Trying to get pillow to build on python 3.   The build seems to fail due to setuptools.   It just hangs at the last line while trying to install setuptools. 

```
creating 'dist/setuptools-33.1.1-py3.7.egg' and adding 'build/bdist.macosx-10.14-x86_64/egg' to it
removing 'build/bdist.macosx-10.14-x86_64/egg' (and everything under it)
Processing setuptools-33.1.1-py3.7.egg
Removing /Users/sorensolari/Documents/Simpa/code_stuff/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/setuptools-33.1.1-py3.7.egg
Copying setuptools-33.1.1-py3.7.egg to /Users/sorensolari/Documents/Simpa/code_stuff/kivy-ios/dist/hostpython3/lib/python3.7/site-packages
setuptools 33.1.1 is already the active version in easy-install.pth
Installing easy_install script to /Users/sorensolari/Documents/Simpa/code_stuff/kivy-ios/dist/hostpython3/bin
Installing easy_install-3.7 script to /Users/sorensolari/Documents/Simpa/code_stuff/kivy-ios/dist/hostpython3/bin

Installed /Users/sorensolari/Documents/Simpa/code_stuff/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/setuptools-33.1.1-py3.7.egg
Processing dependencies for setuptools==33.1.1
Finished processing dependencies for setuptools==33.1.1
Archive:  setuptools-33.1.1-py3.7.egg
```

There was a similar problem on android and seems like it may have been some recent work to address in python-for-android: https://github.com/kivy/python-for-android/pull/1339
maybe that can be used/helpful to port a solution.

**Comment by GoBig87** [comment]
I'm seeing the same issue

`[DEBUG   ] Processing setuptools-33.1.1-py3.7.egg
[DEBUG   ] Removing /Users/MacUser/PycharmProjects/Fin_App/Fin-Aquatic-Rentals/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/setuptools-33.1.1-py3.7.egg
[DEBUG   ] Copying setuptools-33.1.1-py3.7.egg to /Users/MacUser/PycharmProjects/Fin_App/Fin-Aquatic-Rentals/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/site-packages
[DEBUG   ] setuptools 33.1.1 is already the active version in easy-install.pth
[DEBUG   ] Installing easy_install script to /Users/MacUser/PycharmProjects/Fin_App/Fin-Aquatic-Rentals/.buildozer/ios/platform/kivy-ios/dist/hostpython3/bin
[DEBUG   ] Installing easy_install-3.7 script to /Users/MacUser/PycharmProjects/Fin_App/Fin-Aquatic-Rentals/.buildozer/ios/platform/kivy-ios/dist/hostpython3/bin
[DEBUG   ] 
[DEBUG   ] Installed /Users/MacUser/PycharmProjects/Fin_App/Fin-Aquatic-Rentals/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/setuptools-33.1.1-py3.7.egg
[DEBUG   ] Processing dependencies for setuptools==33.1.1
[DEBUG   ] Finished processing dependencies for setuptools==33.1.1
[INFO    ] Running Shell: /usr/bin/unzip ('setuptools-33.1.1-py3.7.egg',) {'_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[DEBUG   ] Archive:  setuptools-33.1.1-py3.7.egg`

Did you have any luck getting around the issue?

**Comment by GoBig87** [comment]
So I think the issue is this.  When you build hostpython3 it comes with it's own setuptools 39.0.1 and when the toolchain.py tries to unzip the egg file it gets stuck because when I manually try and unzip it I get a warning that these files already exist and if I want to overwrite them.  I made a hack in the host_setuptools recipe with this line

```shprint(unzip,"-o",setuptools_egg_path)```

and used the -o to overwrite all the same files.  It then built the recipee but I'm not sure if it's going to properly work doing it this way...

**Comment by GoBig87** [comment]
The proper way I think to work around this issue is to remove all dependencies to hostpython in your recipes.  I removed them all and built an ipa with it removed.

**Comment by Zen-CODE** [comment]
The new pillow recipe should address this issue.
