### ISSUE TITLE
OSError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] in ./toolchain.py build kivy

### ISSUE THREAD

**Issue by jtailw** [kivy/kivy-ios#343]
Versions

Python: 3.7.1
OS: MacOS Mojave 10.14.1
Kivy: 1.10.1

Hi ,  When I used "./toolchain.py build kivy", I got an "OSError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051)" error : (. How should I handle this SSL error? I am looking forward to yours reply. Thanks very very much!!~

This error has been bothering me for a long time, because I learned programming by myself and consulted other friends without solving this problem. I hope to get your help, thank you very much

![error](https://user-images.githubusercontent.com/6051943/51303401-3509ba00-1a70-11e9-8b22-7d540ebfa5a6.jpg)

**Comment by hackalog** [comment]
Have you tried installing certffi as described here: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error ?

i.e. something like 
```
pip install certifi
/Applications/Python\ 3.6/Install\ Certificates.command
```

See the stackoverflow thread for details.

**Comment by jtailw** [comment]
> Have you tried installing certffi as described here: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error ?
> 
> i.e. something like
> 
> ```
> pip install certifi
> /Applications/Python\ 3.7/Install\ Certificates.command  #modify for your install location
> ```
> See the stackoverflow thread for details.

Another friend helped me solve this problem with the method you provided yesterday. Thank you very much for your help  　^_^
