### ISSUE TITLE
Simplify install for users with conda

### ISSUE THREAD

**Issue by ssolari** [kivy/kivy-ios#345]
## motivation
I love kivy and I think the effort the developers have put in to make a project like this happen is amazing.  There is so much potential.   I have been trying to grapple with getting kivy build for ios and android for a while now and it is for sure a challenge.    The kivy-ios toolchain as well as the android are excellent attempts to help getting kivy deployed, but there seem to be a ton of challenges still. 

The adoption of kivy would dramatically increase if the path to building was made simple and easy. 

## compiling
It seems the original main purpose of the toolchain is to deal with the need to cross-compile python.  For a long time this was a challenge in the python world for libraries that relied on underlying custom C optimizations (like numpy).    Conda has proven to be a very effective solution to cross compile.  Installing optimized blas numpy on any platform is as easy as ```conda install numpy```.   No worry about compiling etc. 

## The idea
   * Users should not have to compile code locally.
   * Use conda and conda recipes (built by developers) to manage.    Users just install specific versions of common packages. 
   * Installation of kivy for ios should be no more complicated than creating a conda environemnet and doing ```conda install ios-python ios-kivy```
      * same purpose as toolchain, but no compiling locally which removes a lot of potential issues. 
   * The conda environment serves as the full repository of binaries that need to be copied.  Since the environment is its own directory it can just be copied.   Aside: If the user has a setup.py for their kivy main project, then it could even be installed too and a small execution wrapper for the actual deployment. 

## solution
It seems there is already a [project ](https://github.com/codelv/conda-mobile) that has started this by the folks building enaml-naitive.    It seems this type of work should be leveraged together.   Why have 2 paths to having a compiled binary of python or kivy or another package? 

Maybe this has been looked into.  I don't know, but I think using conda as the binary package manager for kivy (both ios and android and even desktop) may streamline everything and open the door to wider adoption.

**Comment by Zen-CODE** [comment]
This is a nice idea, and we are open to pull requests for improvement. It is not really a bug or demonstrable problem however, so having an issue open at this high level does not really make sense. I think it would be best addressed on an issue-by-issue bases? Thanks
