### ISSUE TITLE
pycrypto recipe installs in wrong place for python3

### ISSUE THREAD

**Issue by ssolari** [kivy/kivy-ios#346]
pycrypto is hardcoded for python 2

https://github.com/kivy/kivy-ios/blob/8d5c8c243f0eebf3649c216db34f6b097bdd05a9/recipes/pycrypto/__init__.py#L40-L41

for python 3 the lines above need to be
```
dest_dir = join(self.ctx.dist_dir, "root", "python3") 
build_env['PYTHONPATH'] = join(dest_dir, 'lib', 'python3.7', 'site-packages') 
```

I'm not sure how kivy-ios is generally handling the difference in recipes between python2 and python3 but a general check in all recipes for the interpreter to always set the site packages directory correctly and uniformly might be beneficial.

**Comment by Zen-CODE** [comment]
This issue should be resolved via recent changes. Please try the latest checkout and re-open if the problem persists.
