### ISSUE TITLE
No way to clear just the download cache

### ISSUE THREAD

**Issue by hackalog** [kivy/kivy-ios#352]
If I edit a recipe (say to point at a different github repo), I want to clean build *and* cache directory, otherwise my changes will be ignored.

It would be useful to add a `clean` (or `distclean`) flag to also clean the download cache, rather than having to do it manually

**Comment by Zen-CODE** [comment]
Agreed, I've hit this problem myself. `clean` is already taken though, as a command. How about `cleancache`, or `cleancache <recipe>`? Would that work for you?

**Comment by hackalog** [comment]
`clean_cache` would be my preference, if you're asking :) 

Thanks!

**Comment by Zen-CODE** [comment]
Thinking about this, it build is cached, so cleaning just the cache will not help. You would also need to clean the build?

Could you please give a concrete steps indicating what you would like to do, so I can test and confirm any changes will do what you require? Thanks

**Comment by Zen-CODE** [comment]
@hackalog Adding this as an extra option seems over-complicated. Don't you think cleaning the cache should actually be part of the default behaviour for `clean`? The caching seems like unexpected black magic. Cleaning would imply everything is removed, not just the build?

**Comment by hackalog** [comment]
I’m certainly ok with clean meaning clean everything.

**Comment by Zen-CODE** [comment]
Feature added via https://github.com/kivy/kivy-ios/pull/558
