### ISSUE TITLE
symbol(s) not found for architecture armv7 (when  running Archive in Xcode and Python3)

### ISSUE THREAD

**Issue by yanlb** [kivy/kivy-ios#362]
Xcode 10.1 (10B61) - Python 3.7 - Kivy 1.10.1
When a run Archive creation failed build and there are all warnings and errors:

```
ld: warning: directory not found for option '-L/Users/XX/kivy-ios/glomarkhome-ios/../build/lib'
ld: warning: directory not found for option '-F/Users/XX/kivy-ios/dist/frameworks'
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libsdl2_ttf.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libsdl2_ttf.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libpyobjus.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libpyobjus.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libffi.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libffi.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libfreetype.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libfreetype.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libsdl2_image.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libsdl2_image.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libsdl2_mixer.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libsdl2_mixer.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libcrypto.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libcrypto.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libssl.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libssl.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libsdl2.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libsdl2.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libios.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libios.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libkivy.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libkivy.a (2 slices)
ld: warning: ignoring file /Users/XX/kivy-ios/dist/lib/libpython3.a, missing required architecture armv7 in file /Users/XX/kivy-ios/dist/lib/libpython3.a (2 slices)
Undefined symbols for architecture armv7:
  "_PyEval_InitThreads", referenced from:
      _SDL_main in main.o
  "_PyMem_RawMalloc", referenced from:
      _SDL_main in main.o
  "_PyRun_SimpleFileExFlags", referenced from:
      _SDL_main in main.o
  "_PyRun_SimpleStringFlags", referenced from:
      _SDL_main in main.o
      _load_custom_builtin_importer in main.o
  "_PySys_SetArgv", referenced from:
      _SDL_main in main.o
  "_Py_DecodeLocale", referenced from:
      _SDL_main in main.o
  "_Py_Finalize", referenced from:
      _SDL_main in main.o
  "_Py_Initialize", referenced from:
      _SDL_main in main.o
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: _SDL_main)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Any idea?

**Comment by yanlb** [comment]
I delete all this paths from project on Build Settings > Search Paths:

Framework Search Path:  
        /Users/XX/kivy-ios/dist/frameworks

Header Search Paths:
    Debug:
        /Users/XX/kivy-ios/dist/root/python/include
        /Users/XX/kivy-ios/dist/include/common/sdl2
    Release:
        "$(PROJECT_DIR)/../build/include"
        "$(PROJECT_DIR)/../build/python/include"

Library Search Paths: 
    Debug:
        $(inherited)
        /Users/XX/kivy-ios/dist/lib
        $(SRCROOT)/../dist/lib
    Release:
        $(inherited)
        "$(PROJECT_DIR)/../build/lib"
        $(SRCROOT)/../dist/lib
And now this is Errors:

ld: library not found for -lsdl2_ttf
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld /Users/XX/Library/Developer/Xcode/DerivedData/glomarkhome-fefpabxpybmmyndxqoqlbthztldp/Build/Intermediates.noindex/ArchiveIntermediates/glomarkhome/IntermediateBuildFilesPath/glomarkhome.build/Release-iphoneos/glomarkhome.build/Objects-normal/armv7/glomarkhome normal armv7 (in target: glomarkhome)
    cd /Users/XX/kivy-ios/glomarkhome-ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -L/Users/XX/Library/Developer/Xcode/DerivedData/glomarkhome-fefpabxpybmmyndxqoqlbthztldp/Build/Intermediates.noindex/ArchiveIntermediates/glomarkhome/BuildProductsPath/Release-iphoneos -F/Users/XX/Library/Developer/Xcode/DerivedData/glomarkhome-fefpabxpybmmyndxqoqlbthztldp/Build/Intermediates.noindex/ArchiveIntermediates/glomarkhome/BuildProductsPath/Release-iphoneos -filelist /Users/XX/Library/Developer/Xcode/DerivedData/glomarkhome-fefpabxpybmmyndxqoqlbthztldp/Build/Intermediates.noindex/ArchiveIntermediates/glomarkhome/IntermediateBuildFilesPath/glomarkhome.build/Release-iphoneos/glomarkhome.build/Objects-normal/armv7/glomarkhome.LinkFileList -miphoneos-version-min=8.1 -Xlinker -object_path_lto -Xlinker /Users/XX/Library/Developer/Xcode/DerivedData/glomarkhome-fefpabxpybmmyndxqoqlbthztldp/Build/Intermediates.noindex/ArchiveIntermediates/glomarkhome/IntermediateBuildFilesPath/glomarkhome.build/Release-iphoneos/glomarkhome.build/Objects-normal/armv7/glomarkhome_lto.o -Xlinker -final_output -Xlinker /Applications/glomarkhome.app/glomarkhome -fobjc-link-runtime -all_load -framework AudioToolbox -framework ImageIO -framework MessageUI -framework UIKit -framework OpenGLES -framework Metal -framework CoreMotion -framework AVFoundation -framework MobileCoreServices -framework GameController -framework CoreGraphics -framework Accelerate -framework QuartzCore -lc++ -lz -lsqlite3 -lbz2 -lsdl2_ttf -lpyobjus -lffi -lios -lsdl2_mixer -lsdl2_image -lfreetype -lkivy -lpython3 -lcrypto -lssl -lsdl2 -Xlinker -dependency_info -Xlinker /Users/XX/Library/Developer/Xcode/DerivedData/glomarkhome-fefpabxpybmmyndxqoqlbthztldp/Build/Intermediates.noindex/ArchiveIntermediates/glomarkhome/IntermediateBuildFilesPath/glomarkhome.build/Release-iphoneos/glomarkhome.build/Objects-normal/armv7/glomarkhome_dependency_info.dat -o /Users/XX/Library/Developer/Xcode/DerivedData/glomarkhome-fefpabxpybmmyndxqoqlbthztldp/Build/Intermediates.noindex/ArchiveIntermediates/glomarkhome/IntermediateBuildFilesPath/glomarkhome.build/Release-iphoneos/glomarkhome.build/Objects-normal/armv7/glomarkhome

**Comment by yanlb** [comment]
I have started everything from the beginning and I have the same Error an Warnings. I realized that maybe I do not have kivy-ios for armv7 and I have executed: ```./toolchain.py build python3 kivy --arch=armv7 --arch=arm64``` and tell me ```[ERROR ] Architecture armv7 invalid```

**Comment by yanlb** [comment]
I solved my problem and it was really simple. I put on Build Settings > Architectures >Architectures: `$(ARCHS_STANDARD_64_BIT)`

**Comment by hackalog** [comment]
Arm7 is deprecated as of MacOS Mojave, (header files are no longer shipper
with XCode). If you need to target iPhone 5c or earlier, you must check out
an older kivy-ios. (the change was made in January, I believe)

Is there a reason you need to target armv7 specifically?

**Comment by yanlb** [comment]
No, I do not need it at all. I had an Xcode error when trying to generate the ipa file but I have already solved it as I mentioned above.
Thank you very much Hckalog ;)
