### ISSUE TITLE
Unable to switch screens after on_release of button in iOS simulator

### ISSUE THREAD

**Issue by s1113950** [kivy/kivy-ios#365]
Switching screens after login works fine on my Mac (just running my python main.py file), as well as on Android, but when I try and login via iOS I get stuck here:

![image](https://user-images.githubusercontent.com/8314343/53934890-3bbcb280-4059-11e9-91ef-acfe96b71468.png)

I can tell that the login happened because my server gets a response as expected, but the screen is stuck here with the `login` button pressed.

Side note: things are off-center as well when running on the simulator. I'm not sure if that's related but I figured I'd list it here just in case.

I'm running latest xcode on Mac Mojave.

Here's what the console in Xcode says:

```
2019-03-06 21:41:47.676242-0800 piles[10024:4065544]
[framework] CUIThemeStore: No theme registered with
id=0
2019-03-06 21:41:47.755744-0800 piles[10024:4065544]
Available orientation:
KIVY_ORIENTATION=LandscapeLeft LandscapeRight
Portrait PortraitUpsideDown
2019-03-06 21:41:47.755877-0800 piles[10024:4065544]
Initializing python
/Users/robertso/Library/Developer/CoreSimulator/Devices
E3E15AFA-1777-445E-B46F-64FEB987A460/data
Containers/Bundle/Application/21CC1454-FDB5-4F32
AFC2-CC3027BBB608/piles.app/piles:1:
DeprecationWarning: the imp module is deprecated in
favour of importlib; see the module's documentation
for alternative uses
2019-03-06 21:41:47.834214-0800 piles[10024:4065544]
Running main.py: /Users/robertso/Library/Developer
CoreSimulator/Devices/E3E15AFA-1777-445E
B46F-64FEB987A460/data/Containers/Bundle
Application/21CC1454-FDB5-4F32-AFC2-CC3027BBB608
piles.app/YourApp/main.pyc
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (default, Feb  4 2019,
20:11:34) 
[Clang 10.0.0 (clang-1000.11.45.5)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_te
(img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gi
ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2"
graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.
APPLE-17.0.37'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple
Software Renderer'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES
GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed,
single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "<string>", line 39, in load_module
   File "/Users/robertso/kivy-ios/dist/root/python3/lib
python3.7/imp.py", line 342, in load_dynamic
     return _load(spec)
   File "<frozen importlib._bootstrap>", line 696, in
_load
   File "<frozen importlib._bootstrap>", line 670, in
_load_unlocked
   File "<frozen importlib._bootstrap>", line 583, in
module_from_spec
   File "<frozen importlib._bootstrap_external>", line
1043, in create_module
   File "<frozen importlib._bootstrap>", line 219, in
_call_with_frames_removed
 ImportError: dynamic module does not define module
export function (PyInit_markupsafe__speedups)
Got dlopen error on Foundation: dlopen(/System/Library
Frameworks/Foundation.framework/Versions/Current
Foundation, 1): no suitable image found.  Did find:
	/System/Library/Frameworks/Foundation.framework
Versions/Current/Foundation: mach-o, but not
built for iOS simulator
Got fallback dlopen error on Foundation: dlopen(/Groups
System/Library/Frameworks/Foundation.framework
Versions/Current/Foundation, 1): image not found
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is
available
2019-03-06 21:41:52.273654-0800 piles[10024:4065544]
[MC] System group container for
systemgroup.com.apple.configurationprofiles path
is /Users/robertso/Library/Developer/CoreSimulator
Devices/E3E15AFA-1777-445E-B46F-64FEB987A460/data
Containers/Shared/SystemGroup
systemgroup.com.apple.configurationprofiles
2019-03-06 21:41:52.276230-0800 piles[10024:4065544]
[MC] Reading from private effective user settings.
```

I'm running on iphone XR simulator

**Comment by s1113950** [comment]
Update: When I didn't use a mouse and used the trackpad the button seemed to press like normal, but the screen still didn't update (it didn't stay blue). I then could "press" other things on the other screen but the simulator didn't update with the new screen

**Comment by ksgfan** [comment]
I have the same problem on high sierra and Xcode 10.1. What could be wrong? I've tried reinstall kivy-ios and Xcode.

**Comment by hackalog** [comment]
Does it work if you use the software keyboard instead of the hardware one?
(deselect the hardware keyboard in the simulator)

**Comment by ksgfan** [comment]
no, it does not, pressing button does not bring me to the second screen (drawing screen). Interestingly when moving and pressing on the mouse, the app print the coordinates as it should. So technically I am on the second screen, but I see only the first one.

**Comment by ksgfan** [comment]
I've tried running this code on another computer and it still doesn't work. Could someone please try run it und tell me, whether the problem is in the code or on my computers? In python shell it works fine, but after installing on iPad or iPhone the screen does not switch to another!

`
from kivy.app import App
# kivy.require("1.8.0")
from kivy.uix.widget import Widget
from kivy.graphics import Line
from kivy.core.image import Image
from kivy.uix.button import Button
from kivy.clock import Clock

import os
import time

from kivy.config import Config
#Config.set('graphics', 'width', '700')
#Config.set('graphics', 'height', '700')
#Config.write()

from kivy.uix.gridlayout import GridLayout
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.textinput import TextInput
from kivy.uix.label import Label
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen, FadeTransition
from kivy.properties import ObjectProperty
from kivy.properties import StringProperty
from os.path import join

# changing color to white
from kivy.core.window import Window
from kivy.graphics import Color
Window.clearcolor = (1, 1, 1, 1)
# mode rgba
# time_start = time.time() # in class
# timing_ms = time.time() - self.time_start # in method

class MainScreen(Screen):  
        
    username = ObjectProperty(None)
    test_type = ObjectProperty(None)
    test_date = ObjectProperty(None)

    def reset(self):
        self.username.text = ""
        self.test_type.text = ""
        self.test_date.text = ""
        
class SecondScreen(Screen):
    pass     
class AnotherScreen(Screen):
    pass
class ScreenManagement(ScreenManager):
    pass
                                
class DrawInput(Widget):
        
    filename = StringProperty("")
    test_type = StringProperty("")
    now = time.localtime(time.time())
    t = str(now[0]) + "/"+ str(now[1]) + "/" + str(now[2]) + "_"+ str(now[3]) + ":" + str(now[4]) + ":" + str(now[5])

    def btn_save(self):
        Window.screenshot(self.filename+self.test_type+".png")
        
    def on_touch_down(self, touch):
        
        timing_ms = ApplePenApp.get_running_app().sw_seconds
    
                  
        with self.canvas:
            Color(0, 0, 0)
            touch.ud["line"] = Line(points = (touch.x, touch.y))

        if 'pressure' in touch.profile:
            ud['pressure'] = touch.pressure
            #print(touch.pressure)

        
        
    def on_touch_move(self, touch):

        timing_ms = ApplePenApp.get_running_app().sw_seconds


        touch.ud["line"].points += (touch.x, touch.y)

    def on_touch_up(self, touch):     

        timing_ms = ApplePenApp.get_running_app().sw_seconds

presentation = Builder.load_file("applepen_kivy.kv")

class ApplePenApp(App):

    sw_started = False
    sw_seconds = 0
    
    def update_clock(self, nap):
        if self.sw_started:
            self.sw_seconds += nap
        #print(self.sw_seconds)
            
    def start_stop(self):
        self.sw_started = True

    def reset(self):
        if self.sw_seconds:
            self.sw_seconds = 0
        else:
            pass

    def stop_clock(self):
        self.sw_started = False

    def on_start(self):
        Clock.schedule_interval(self.update_clock, 0)

    def build(self):
        return presentation
       
if __name__=="__main__":
    ApplePenApp().run()

`

Kivy
`# File name: main.py
#: import FadeTransition kivy.uix.screenmanager.FadeTransition

ScreenManagement:
    transition: FadeTransition()
    MainScreen:
        id: main
    SecondScreen:
        
    AnotherScreen:
    
<MainScreen>:
    name: "main"
    #define global variables 
    username: username
    test_type: test_type
    test_date: test_date
    
    GridLayout:
        cols:1
        #organise the window
        size: root.width, root.height
         
        GridLayout:
            cols: 2
            
            Label: 
                text: "Username: "
                color: 0.5,0.5, 0.5, 1
                font_size: 30
            TextInput:
                id: username
                multiline: False
                font_size: 30
            Label: 
                text: "Copy/Recall/Recall2: "
                color: 0.5,0.5, 0.5, 1
                font_size: 30
            TextInput:
                id: test_type
                multiline: False
                font_size: 30
            Label: 
                text: "Date: "
                color: 0.5,0.5, 0.5, 1
                font_size: 30
            TextInput:
                id: test_date
                multiline: False
                font_size: 30
                
        Button:
            #color: 0.5,0.5,0.5,1
            font_size: 30
            size_hint: 0.5, 0.5
            text: "Submit"
            on_press: app.root.current = "drawing" if test_type.text == "Copy" or test_type.text == "copy" else "other"
            on_release: root.reset()
        
        Button:
            #color: 0.5,0.5,0.5,1
            font_size: 10
            size_hint: 0.1, 0.1
            text: "Stop App"
            on_press: app.stop()           
    
<SecondScreen>:
    name: "drawing"
    
    on_pre_enter:
        self.ids.drawing.filename = self.manager.ids.main.username.text
    on_pre_enter:
        self.ids.drawing.test_type = self.manager.ids.main.test_type.text
        
    #clean Screen  
    on_pre_enter: drawing.canvas.clear()
    
    #reseting time
    on_pre_enter: app.stop_clock()
    on_pre_enter: app.reset()
             
    FloatLayout:
        
        DrawInput:
            id: drawing
            
        Button:
            #color: 0.5,0.5,0.5,1
            font_size: 30
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.4, "bottom": 1}
            text: "finish"
            #on_press: drawing.btn_save()
            on_release: app.root.current = "main"
                     
        Button:
            id: start_stop
            text: 'Start'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0, "bottom": 1}
            on_press: app.start_stop()
           
        Button:
            id: reset
            text: 'Reset'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.6, "bottom": 1}
            on_press: app.reset()
            
        Button:
            id: stop
            text: 'Stop'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.8, "bottom": 1}
            on_press: app.stop_clock()
            
        Button:
            id: clear
            text: 'Clear'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.2, "bottom": 1}
            on_press: drawing.canvas.clear()
    
        FloatLayout: 
            canvas:
                Color:
                    rgb: 1, 1, 1
                Rectangle:
                    source: "/Users/davidarchibald/Documents/Scripts/penproject/reyfigure.png"
                    size: 350, 250
                    pos: 175, 430
            
<AnotherScreen>:
    name: "other"
    
    on_pre_enter:
        self.ids.other.filename = self.manager.ids.main.username.text
    on_pre_enter:
        self.ids.other.test_type = self.manager.ids.main.test_type.text
    
    #clean Screen  
    on_pre_enter: other.canvas.clear()
    
    #reseting time
    on_pre_enter: app.stop_clock()
    on_pre_enter: app.reset()
    
    FloatLayout:
        DrawInput:
            #
            id: other
        Button:
            #color: 0.5,0.5,0.5,1
            font_size: 30
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.4, "bottom": 1}
            text: "finish"
            #on_press: other.btn_save()
            on_release: app.root.current = "main"
            
        Button:
            id: start_stop
            text: 'Start'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0, "bottom": 1}
            on_press: app.start_stop()
           
        Button:
            id: reset
            text: 'Reset'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.6, "bottom": 1}
            on_press: app.reset()
            
        Button:
            id: stop
            text: 'Stop'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.8, "bottom": 1}
            on_press: app.stop_clock()
            
        Button:
            id: clear
            text: 'Clear'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.2, "bottom": 1}
            # other => clear only DrawInput, not btns
            on_press: other.canvas.clear()
        `

**Comment by ksgfan** [comment]
I've tried running this code on another computer and it still doesn't work. Could someone please try run it und tell me, whether the problem is in the code or on my computers? In python shell it works fine, but after installing on iPad or iPhone the screen does not switch to another!

`
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.graphics import Line
from kivy.core.image import Image
from kivy.uix.button import Button
from kivy.clock import Clock
import os
import time
from kivy.config import Config
from kivy.uix.gridlayout import GridLayout
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.textinput import TextInput
from kivy.uix.label import Label
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen, FadeTransition
from kivy.properties import ObjectProperty
from kivy.properties import StringProperty
from os.path import join
from kivy.core.window import Window
from kivy.graphics import Color
Window.clearcolor = (1, 1, 1, 1)

class MainScreen(Screen):  
        
    username = ObjectProperty(None)
    test_type = ObjectProperty(None)
    test_date = ObjectProperty(None)

    def reset(self):
        self.username.text = ""
        self.test_type.text = ""
        self.test_date.text = ""
        
class SecondScreen(Screen):
    pass     
class AnotherScreen(Screen):
    pass
class ScreenManagement(ScreenManager):
    pass
                                
class DrawInput(Widget):
        
    filename = StringProperty("")
    test_type = StringProperty("")
    now = time.localtime(time.time())
    t = str(now[0]) + "/"+ str(now[1]) + "/" + str(now[2]) + "_"+ str(now[3]) + ":" + str(now[4]) + ":" + str(now[5])

    def btn_save(self):
        Window.screenshot(self.filename+self.test_type+".png")
        
    def on_touch_down(self, touch):
        
        timing_ms = ApplePenApp.get_running_app().sw_seconds
    
                  
        with self.canvas:
            Color(0, 0, 0)
            touch.ud["line"] = Line(points = (touch.x, touch.y))

        if 'pressure' in touch.profile:
            ud['pressure'] = touch.pressure
            #print(touch.pressure)

        
        
    def on_touch_move(self, touch):

        timing_ms = ApplePenApp.get_running_app().sw_seconds


        touch.ud["line"].points += (touch.x, touch.y)

    def on_touch_up(self, touch):     

        timing_ms = ApplePenApp.get_running_app().sw_seconds

presentation = Builder.load_file("applepen_kivy.kv")

class ApplePenApp(App):

    sw_started = False
    sw_seconds = 0
    
    def update_clock(self, nap):
        if self.sw_started:
            self.sw_seconds += nap
        #print(self.sw_seconds)
            
    def start_stop(self):
        self.sw_started = True

    def reset(self):
        if self.sw_seconds:
            self.sw_seconds = 0
        else:
            pass

    def stop_clock(self):
        self.sw_started = False

    def on_start(self):
        Clock.schedule_interval(self.update_clock, 0)

    def build(self):
        return presentation
       
if __name__=="__main__":
    ApplePenApp().run()

`

Kivy
`
# File name: main.py
#: import FadeTransition kivy.uix.screenmanager.FadeTransition

ScreenManagement:
    transition: FadeTransition()
    MainScreen:
        id: main
    SecondScreen:
        
    AnotherScreen:
    
<MainScreen>:
    name: "main"
    #define global variables 
    username: username
    test_type: test_type
    test_date: test_date
    
    GridLayout:
        cols:1
        #organise the window
        size: root.width, root.height
         
        GridLayout:
            cols: 2
            
            Label: 
                text: "Username: "
                color: 0.5,0.5, 0.5, 1
                font_size: 30
            TextInput:
                id: username
                multiline: False
                font_size: 30
            Label: 
                text: "Copy/Recall/Recall2: "
                color: 0.5,0.5, 0.5, 1
                font_size: 30
            TextInput:
                id: test_type
                multiline: False
                font_size: 30
            Label: 
                text: "Date: "
                color: 0.5,0.5, 0.5, 1
                font_size: 30
            TextInput:
                id: test_date
                multiline: False
                font_size: 30
                
        Button:
            #color: 0.5,0.5,0.5,1
            font_size: 30
            size_hint: 0.5, 0.5
            text: "Submit"
            on_press: app.root.current = "drawing" if test_type.text == "Copy" or test_type.text == "copy" else "other"
            on_release: root.reset()
        
        Button:
            #color: 0.5,0.5,0.5,1
            font_size: 10
            size_hint: 0.1, 0.1
            text: "Stop App"
            on_press: app.stop()           
    
<SecondScreen>:
    name: "drawing"
    
    on_pre_enter:
        self.ids.drawing.filename = self.manager.ids.main.username.text
    on_pre_enter:
        self.ids.drawing.test_type = self.manager.ids.main.test_type.text
        
    #clean Screen  
    on_pre_enter: drawing.canvas.clear()
    
    #reseting time
    on_pre_enter: app.stop_clock()
    on_pre_enter: app.reset()
             
    FloatLayout:
        
        DrawInput:
            id: drawing
            
        Button:
            #color: 0.5,0.5,0.5,1
            font_size: 30
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.4, "bottom": 1}
            text: "finish"
            #on_press: drawing.btn_save()
            on_release: app.root.current = "main"
                     
        Button:
            id: start_stop
            text: 'Start'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0, "bottom": 1}
            on_press: app.start_stop()
           
        Button:
            id: reset
            text: 'Reset'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.6, "bottom": 1}
            on_press: app.reset()
            
        Button:
            id: stop
            text: 'Stop'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.8, "bottom": 1}
            on_press: app.stop_clock()
            
        Button:
            id: clear
            text: 'Clear'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.2, "bottom": 1}
            on_press: drawing.canvas.clear()
    
        FloatLayout: 
            canvas:
                Color:
                    rgb: 1, 1, 1
                Rectangle:
                    source: "/Users/davidarchibald/Documents/Scripts/penproject/reyfigure.png"
                    size: 350, 250
                    pos: 175, 430
            
<AnotherScreen>:
    name: "other"
    
    on_pre_enter:
        self.ids.other.filename = self.manager.ids.main.username.text
    on_pre_enter:
        self.ids.other.test_type = self.manager.ids.main.test_type.text
    
    #clean Screen  
    on_pre_enter: other.canvas.clear()
    
    #reseting time
    on_pre_enter: app.stop_clock()
    on_pre_enter: app.reset()
    
    FloatLayout:
        DrawInput:
            #
            id: other
        Button:
            #color: 0.5,0.5,0.5,1
            font_size: 30
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.4, "bottom": 1}
            text: "finish"
            #on_press: other.btn_save()
            on_release: app.root.current = "main"
            
        Button:
            id: start_stop
            text: 'Start'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0, "bottom": 1}
            on_press: app.start_stop()
           
        Button:
            id: reset
            text: 'Reset'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.6, "bottom": 1}
            on_press: app.reset()
            
        Button:
            id: stop
            text: 'Stop'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.8, "bottom": 1}
            on_press: app.stop_clock()
            
        Button:
            id: clear
            text: 'Clear'
            size_hint: 0.2, 0.05
            pos_hint: {"x": 0.2, "bottom": 1}
            # other => clear only DrawInput, not btns
            on_press: other.canvas.clear()
        `

**Comment by ksgfan** [comment]
Could someone please try run this code on Simulator and tell me whether the problem is in the code or on my machine? It runs well in python but in Xcode the main screen still does not switch to the second one! 

https://github.com/ksgfan/ApplePen/tree/master

**Comment by ksgfan** [comment]
got it, I had to change the FadeTransition to NoTransition in the .kv file. Still, any ideas, why FadeTransition does not work?

**Comment by tito** [comment]
I got this two weeks ago. This is because FBO with depthbuffer have an issue on iOS. I don't know what exactly yet, but as soon as a FBO with depthbuffer is instanciated, the app continue to work, except the display is stuck to the last frame before the creation of the FBO.
