### ISSUE TITLE
 toolchain.py build kivy fails (new question)

### ISSUE THREAD

**Issue by Waston-Li** [kivy/kivy-ios#371]
when:

$ git clone git://github.com/kivy/kivy-ios
$ cd kivy-ios
$ ./toolchain.py build kivy

give me this error:
ERROR: Python requirements are missing
To install: pip install -r requirements.txt

When run: pip install -r requirements.txt all Requirements already satisfied
and re run: ./toolchain.py build kivy and giveme the same error.

i don't know  ''Python requirements are missing''  ,i already have the condition

Thanks a lot !

**Comment by AnythingTechPro** [comment]
@Waston-Li Try uninstalling all of the packages in `requirements.txt` then reinstalling them.

**Comment by Waston-Li** [comment]
> @Waston-Li Try uninstalling all of the packages in `requirements.txt` then reinstalling them.

Thanks! I'll try it

**Comment by Waston-Li** [comment]
> @Waston-Li Try uninstalling all of the packages in `requirements.txt` then reinstalling them.



> @Waston-Li Try uninstalling all of the packages in `requirements.txt` then reinstalling them.

failed……

**Comment by sgpy** [comment]
@Waston-Li Are you using venv? Most likely your py interpreter is not able to find installed packages

**Comment by tito** [comment]
What are your env? Which python do you use to run the toolchain? Don't use a virtualenv.
Compare what pip freeze say and requirements.txt.

**Comment by Waston-Li** [comment]
Thank！！！

发自我的 iPhone
