### ISSUE TITLE
iOS KIvy app + openCV error

### ISSUE THREAD

**Issue by TroutCells** [kivy/kivy-ios#375]
I am trying to create an iOS app with Kivy and OpenCV, but following kivy build, xcode outputs the **following error: Import error:dynamic module does not define module export function (PyInit_cv2)**

Extra info: ./toolchain.py pip install opencv-contrib-python installs the packages in the python 2.7 folder even though python 3.7 is the host python.

OpenCV and Kivy work fine in pycharm.

Any help would be greatly appreciated!

I have also tried building Kivy with python2 and a similar error comes up
 https://github.com/kivy/kivy-ios

**Comment by tito** [comment]
There is no opencv recipes in kivy-ios. What you installed may just be binary but not for iOS, and definitively not something that works with kivy-ios.

Somebody need to write a recipe for opencv/kivy-ios first.

**Comment by margauxf** [comment]
I have the exact same issue as TroutCells but I started learning kivy a few weeks before your answer got posted. Would you suggest any workaround?

**Comment by fire17** [comment]
How can write a recipe for a new package?
trying to run pyatv on ios
anyone know's how to compile python including non-pure libraries
i.e ones that can be installed easily with pip
how about DL and install on runtime?
anyone got a clue??
thanks!!

**Comment by simonjuleseric2** [comment]
I would be very interested in a solution as well if someone is still working on this. If there is any documentation on how to create the recipe for kivy ios I would be interested as well.
