### ISSUE TITLE
pip from toolchain.py uses python2 path for python3 builds

### ISSUE THREAD

**Issue by Dirk-Sandberg** [kivy/kivy-ios#378]
Issue:

Using `./toolchain.py pip install module_name` does not add the module properly to kivy-ios projects built with python3

Workaround:

Editing the line in toolchain.py (around line 1500) to use the path from pip3 instead of pip

            pip_path = sh.which("pip") # This was causing issues

            pip_path = sh.which("pip3") # This fixes the issues

Here's a little back and forth about someone who had the same issue:
![Screen Shot 2019-07-18 at 11 16 02 AM](https://user-images.githubusercontent.com/37519914/61481599-7dd1fb00-a94d-11e9-88ea-6dcf8f80fef8.png)

**Comment by tito** [comment]
I guess yes, we should have pip3 (the default should be pip3, not pip2 anymore). But better being explicit in that case.

**Comment by llfkj** [comment]
better: `python -m pip`, and the python/pip versions will necessarily match

**Comment by Zen-CODE** [comment]
This should be resolved with recent changes. Please re-open if not.
