### ISSUE TITLE
KeyError: 'kivy.garden.graph' when using Xcode

### ISSUE THREAD

**Issue by utthawut** [kivy/kivy-ios#379]
KeyError: 'kivy.garden.graph' error shown up on Xcode. I already installed kivy-garden by using command "./toolchain.py pip install kivy-garden)".

[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (default, Jul 29 2019, 08:48:33) 
[Clang 10.0.1 (clang-1001.0.46.4)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)
[INFO   ] [KivyMD      ] KivyMD version: 0.1.2
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 APPLE-17.0.77'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple Software Renderer'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): no suitable image found.  Did find:
	/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation: mach-o, but not built for iOS simulator
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found
 Traceback (most recent call last):
   File "/Users/utthawut/KivyApp/kivy-ios/smarthydro-ios/YourApp/main.py", line 40, in <module>
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 640, in _load_backward_compatible
 **KeyError: 'kivy.garden.graph'**

**Comment by tito** [comment]
How did you install the garden.graph? With the `--app` option?
You don't need `kivy-garden` in the package, it is just a tool to install garden packages.

**Comment by mkrapp** [comment]
Hi, I've had the same problem. I don't understand the details but what works for me is to move (manually) the `graph` directory from `/Users/mariokrapp/Projects/romy/dist/root/python3/lib/python3.8/site-packages/kivy_garden/graph` to `dist/root/python3/lib/python3.8/site-packages/kivy/garden/graph`. Credit to [https://stackoverflow.com/a/60377246/1498309](https://stackoverflow.com/a/60377246/1498309) for the hint.

**Comment by Zen-CODE** [comment]
This seems resolved? Please re-open with @tito 's questions answered if not.

Thanks
