### ISSUE TITLE
numpy 1.16.4 error: targeted OS version does not support use of thread local variables

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/kivy-ios#395]
When running a simple app using the latest (1.16.4) recipe for numpy, I get the following error when trying to runit.

targeted OS version does not support use of thread local variables in __PyArray_SigintHandler for architecture x86_64. This is using XCode 10.3 on 10.14.6. Full log follows:

```
Ld /Users/richard/Library/Developer/Xcode/DerivedData/numpyapp-akvtksfwfvtxtiaweywiflelebyr/Build/Products/Debug-iphonesimulator/numpyapp.app/numpyapp normal x86_64 (in target: numpyapp)
    cd /Users/richard/Repos/kivy-ios/numpyapp-ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -L/Users/richard/Library/Developer/Xcode/DerivedData/numpyapp-akvtksfwfvtxtiaweywiflelebyr/Build/Products/Debug-iphonesimulator -L/Users/richard/Repos/kivy-ios/dist/lib -L/Users/richard/Repos/kivy-ios/numpyapp-ios/../dist/lib -F/Users/richard/Library/Developer/Xcode/DerivedData/numpyapp-akvtksfwfvtxtiaweywiflelebyr/Build/Products/Debug-iphonesimulator -F/Users/richard/Repos/kivy-ios/dist/frameworks -filelist /Users/richard/Library/Developer/Xcode/DerivedData/numpyapp-akvtksfwfvtxtiaweywiflelebyr/Build/Intermediates.noindex/numpyapp.build/Debug-iphonesimulator/numpyapp.build/Objects-normal/x86_64/numpyapp.LinkFileList -mios-simulator-version-min=8.1 -Xlinker -object_path_lto -Xlinker /Users/richard/Library/Developer/Xcode/DerivedData/numpyapp-akvtksfwfvtxtiaweywiflelebyr/Build/Intermediates.noindex/numpyapp.build/Debug-iphonesimulator/numpyapp.build/Objects-normal/x86_64/numpyapp_lto.o -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -all_load -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/richard/Library/Developer/Xcode/DerivedData/numpyapp-akvtksfwfvtxtiaweywiflelebyr/Build/Intermediates.noindex/numpyapp.build/Debug-iphonesimulator/numpyapp.build/numpyapp.app-Simulated.xcent -framework CoreVideo -framework MobileCoreServices -framework MessageUI -framework AVFoundation -framework Accelerate -framework GameController -framework UIKit -framework AudioToolbox -framework CoreMedia -framework QuartzCore -framework CoreGraphics -framework Metal -framework CoreMotion -framework WebKit -framework OpenGLES -framework ImageIO -lc++ -lbz2 -lz -lsqlite3 -lnpysort -lsdl2_ttf -lssl -lfreetype -lpyobjus -lsdl2 -lnpymath -lcrypto -lpillow -lsdl2_image -lnumpy -lffi -lsdl2_mixer -ljpeg -lpython3 -lkivy -lios -Xlinker -dependency_info -Xlinker /Users/richard/Library/Developer/Xcode/DerivedData/numpyapp-akvtksfwfvtxtiaweywiflelebyr/Build/Intermediates.noindex/numpyapp.build/Debug-iphonesimulator/numpyapp.build/Objects-normal/x86_64/numpyapp_dependency_info.dat -o /Users/richard/Library/Developer/Xcode/DerivedData/numpyapp-akvtksfwfvtxtiaweywiflelebyr/Build/Products/Debug-iphonesimulator/numpyapp.app/numpyapp

ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
ld: targeted OS version does not support use of thread local variables in __PyArray_SigintHandler for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Zen-CODE** [comment]
Changing the deployment target to 9.0 fixes the problem.

https://stackoverflow.com/questions/52282646/build-error-targeted-os-version-does-not-support-use-of-thread-local-variables

**Comment by dinesh-rajaveeran** [comment]
@Zen-CODE I get the same error. Changing the deployment target doesn't work for me.
XCode v10.3
Mac OS Mojave- 10.14.6 ()
Kivy - 1.11.1
bumpy - 1.16.4

**Comment by Zen-CODE** [comment]
@dinesh-rajaveeran  Well, it's still showing your IPHONEOS_DEPLOYMENT_TARGET=8.1? You've got change that to 9.0. You  must be changing it in the wrong place? Post again if you don't come right and I'll upload a screenshot of exactly where to change this.

**Comment by dinesh-rajaveeran** [comment]
@Zen-CODE I changed it in here: But still the App is not compiling. Its a TicTacToe app that uses numpy

![image](https://user-images.githubusercontent.com/31453392/80600945-1d530c80-89fb-11ea-9c10-8b0527710ec2.png)

**Comment by Zen-CODE** [comment]
But the error of the text says differently? Does it still say:

    export IPHONEOS_DEPLOYMENT_TARGET=8.1

And when exactly does this occur? When you build the app? Run it? What exact command are you entering?

**Comment by dinesh-rajaveeran** [comment]
<img width="1398" alt="Screen Shot 2020-04-29 at 7 38 35 PM" src="https://user-images.githubusercontent.com/31453392/80657533-dba18080-8a51-11ea-9784-74291421971e.png">

@Zen-CODE  I was able to deploy. I had to change the TARGETS-> deployment targets-> 9.0
Thanks for your help though !

**Comment by Zen-CODE** [comment]
Can't seem to access the screenshot?

**Comment by Zen-CODE** [comment]
Either way, this is more of an Apple/XCode problem that  Kivy one. Perhaps search on the Apple forums?

**Comment by Zen-CODE** [comment]
Okay, thanks, I see the screenshot. But now the error seems to have gone? Or is it still printing 8.1 in the error output?

**Comment by dinesh-rajaveeran** [comment]
It is gone ... @Zen-CODE .. I used the deployment target = 9.0 under "targets". Thanks for your help !
