### ISSUE TITLE
Kivy App not optimised for iPhone X, Xs and Xs Max.

### ISSUE THREAD

**Issue by ccarro03** [kivy/kivy-ios#406]
I've created an app using Kivy which I've successfully packaged for iOS. I can successfully run the app in the Xcode simulator. However, when I run it in the simulators for iPhone X, Xs and Xs Max all the widgets in my app are squished together. See the following pics: 

<img width="339" alt="Screenshot 2019-11-30 at 11 34 20" src="https://user-images.githubusercontent.com/53814578/69899953-6415db00-1365-11ea-9d7e-3066bbc7db8d.png">

And on iPhone X:

<img width="367" alt="Screenshot 2019-11-30 at 11 33 43" src="https://user-images.githubusercontent.com/53814578/69899955-6f690680-1365-11ea-8f4f-3b466227a502.png">

I have already added LaunchImages to my Xcode project, which I had previously been advised would fix the problem, however the scaling is still wrong. Any advice?

**Comment by Dirk-Sandberg** [comment]
The number of pixels / pixel density is different on these phones. Perhaps you're doing some spacing or sizing without using `dp`?

**Comment by Zen-CODE** [comment]
AS @Dirk-Sandberg , this problem is easily explained if you are not using the "dp". Please review the kivy Metrics documentation for a detailed explanation:

    https://kivy.org/doc/stable/api-kivy.metrics.html

If you still feel there is a problem here, please open a new ticket with sample code the demonstrate the problem. Thanks
