### ISSUE TITLE
Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for modplug

### ISSUE THREAD

**Issue by dbrova15** [kivy/kivy-ios#410]
When I try to download an application in Apple Store Connect I get an error "Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for modplug". Who knows how to fix this?
![изображение](https://user-images.githubusercontent.com/20703983/70703142-26f00800-1cd8-11ea-8333-0856debff4d0.png)

I tried the following methods:
Removed unnecessary files from Copy Bundle Resources.
In plist added:

    <key>CFBundleSupportedPlatforms</key>
    <array>
        <string>iPhoneOS</string>
    </array> 

I was looking for .dSYM files in the project. I didn’t find anything.
What else can you do? I've been trying to fix this for two days now.

os: macOS 10.13.6
xcode: Version 10.1 (10B61)

**Comment by dbrova15** [comment]
> When I try to download an application in Apple Store Connect I get an error "Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for modplug". Who knows how to fix this?
> ![изображение](https://user-images.githubusercontent.com/20703983/70703142-26f00800-1cd8-11ea-8333-0856debff4d0.png)
> 
> I tried the following methods:
> Removed unnecessary files from Copy Bundle Resources.
> In plist added:
> 
> ```
> <key>CFBundleSupportedPlatforms</key>
> <array>
>     <string>iPhoneOS</string>
> </array> 
> ```
> 
> I was looking for .dSYM files in the project. I didn’t find anything.
> What else can you do? I've been trying to fix this for two days now.
> 
> os: macOS 10.13.6
> xcode: Version 10.1 (10B61)

I solved the problem. First I deleted the ~ / Library / Developer / Xcode / DerivedData / ModuleCache directory. Then I downloaded kivy-ios again, set up toochain and created a project. And only then I was able to download the application in the Apple Store Connect.

**Comment by Zen-CODE** [comment]
Great. Thanks for posting back.
