### ISSUE TITLE
Help implement the share button. Objective-C with Python Kivy

### ISSUE THREAD

**Issue by dbrova15** [kivy/kivy-ios#411]
I need to add a share button to my application.

I managed to call the ojective-c method from Python code, which calls a shared sheet. But when pressed, an error occurs:

> 2019-12-12 16: 32: 29.023501 + 0200 financialassistant [19525: 1852046] Warning: Attempt to present <UIActivityViewController: 0x7fad561ac000> on <ShareObj: 0x7fad55495ec0> whose view is not in the window hierarchy!
> 2019-12-12 16: 32: 50.136942 + 0200 financialassistant [19525: 1888314] XPC connection interrupted

My objective-C code:
```
@interface ShareObj : UIViewController
    @end

@implementation ShareObj
-(id)init {
    return self;
}

-(void)shareContent{
    NSLog(@"shareButton start");
    NSString * message = @"My too cool Son";
//    UIImage * image = [UIImage imageNamed:@"boyOnBeach"];
    NSArray * shareItems = @[message];
    
    UIActivityViewController * avc = [[UIActivityViewController alloc] initWithActivityItems:shareItems applicationActivities:nil];
    NSLog(@"shareButton 2");
    [self presentViewController:avc animated:YES completion:nil];

}
```
My python code:

```
        if platform == "ios":
            from pyobjus import autoclass

            self.share = autoclass("ShareObj").alloc().init()

    def share_button(self):
        if platform == "ios":
            print("share_button iOS")
            self.share.shareContent()
        else:
            print("share_button python")
```

**Comment by brentpicasso** [comment]
Were you able to figure this out?

**Comment by Zen-CODE** [comment]
Hi.You could do that using PyObjus. But please post the question on the Kivy forum here: https://groups.google.com/forum/#!forum/kivy-users

This issue tracker is reserved for reporting demonstrable faults in kivy-ios. Thanks.

**Comment by dbrova15** [comment]
> 
> 
> Were you able to figure this out?

Yes, I solved this problem, but unfortunately the code was not saved. I remember that the problem was that I did not correctly declare the ShareObj object.

Try following the example of this code:
https://gist.github.com/dbrova15/d377d42075d8ec99dbf7fd95432cab00
