### ISSUE TITLE
Steps to get pandas working?

### ISSUE THREAD

**Issue by krusaderjake** [kivy/kivy-ios#412]
Hi - So I've been able to install everything correctly as defined in the README and start my kivy-ios Xcode project, but I'm stumbling a bit figuring out how to install pandas and how this relates to the numpy build recipe.

1) I've installed the numpy build recipe:
`./toolchain.py build numpy`
... this installs successfully

2) Then I try to install pandas:
`./toolchain.py pip3 install pandas`
... this installs successfully

3) Then I update my Xcode project:
`./toolchain.py update project-ios/`

4) Then the error I get in Xcode console:
`AttributeError: type object 'numpy.float16' has no attribute 'as_integer_ratio'`

5) Then I'm thinking, oh shoot, pandas installed numpy==1.17.4 dependency and I try to switch the version of numpy via pip3 that pandas uses:
`./toolchain.py pip3 install numpy==1.16.4`

6) Different error in Xcode now:
`ImportError: C extension: dynamic module does not define module export function (PyInit_conversion) not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.`

Is there a sequence of steps I need to execute to get pandas working in kivy-ios Xcode project? What are those steps?

**Comment by muslehm** [comment]
Did you manage to get this to work?
I still get "AttributeError: type object 'numpy.float16' has no attribute 'as_integer_ratio'" when I try to run my kivy app on an xcode simulator

**Comment by krusaderjake** [comment]
I did get this to work but things were very slow on the xcode simulator. If I find some time to dig back into that project, I'll see if I can find what I did to get it to work. I recall trying different versions of pandas, then was disappointed when the performance was slow.

**Comment by Zen-CODE** [comment]
You would need a recipe for that, as pandas is not officially support. But please post the question on the Kivy forum here: https://groups.google.com/forum/#!forum/kivy-users

This issue tracker is reserved for reporting demonstrable faults in kivy-ios. Thanks.
