### ISSUE TITLE
Is there any way to interface with Apple HealthKit?

### ISSUE THREAD

**Issue by mbrockman1** [kivy/kivy-ios#413]
I am trying to make an app that connects to and pulls data from the HealthKit database on the device. Has anyone had any success doing this?

**Comment by ethanopp** [comment]
+1 ...ever figure this out?

**Comment by Zen-CODE** [comment]
Hi.You could do that using PyObjus. But please post the question on the Kivy forum here: https://groups.google.com/forum/#!forum/kivy-users

This issue tracker is reserved for reporting demonstrable faults in kivy-ios. Thanks.
