### ISSUE TITLE
Problem with Xcode compilation (libhostlibffi.a)

### ISSUE THREAD

**Issue by Falk21** [kivy/kivy-ios#416]
Xcode 11.3
MacOs10.14.6

audiostream  - Build OK (built at 2019-11-06 10:15:13.419667)
click        - Build OK (built at 2019-12-16 17:14:10.672956)
curly        - Not built
cymunk       - Not built
distribute   - Not built
ffmpeg       - Build OK (built at 2019-12-11 13:29:29.277468)
ffpyplayer   - Build OK (built at 2019-12-11 13:30:27.908338)
flask        - Not built
freetype     - Build OK (built at 2019-11-05 21:12:29.042373)
host_setuptools - Not built
host_setuptools3 - Build OK (built at 2019-12-16 17:14:45.241366)
hostlibffi   - Build OK (built at 2019-11-06 10:18:56.460091)
hostpython2  - Not built
hostpython3  - Build OK (built at 2019-11-05 21:18:11.943148)
ios          - Build OK (built at 2019-11-05 21:26:22.286456)
itsdangerous - Not built
jinja2       - Not built
kivent_core  - Build OK (built at 2019-12-16 17:17:52.929769)
kivy         - Build OK (built at 2019-11-06 10:12:57.991785)
libcurl      - Not built
libffi       - Build OK (built at 2019-11-05 21:13:45.856970)
libjpeg      - Build OK (built at 2019-12-16 17:18:48.454828)
libpng       - Not built
libzbar      - Not built
markupsafe   - Not built
numpy        - Not built
openssl      - Build OK (built at 2019-11-05 21:14:34.258290)
photolibrary - Not built
pil          - Not built
pillow       - Not built
pkgresources - Not built
plyer        - Build OK (built at 2019-12-11 13:32:56.975825)
pycrypto     - Not built
pykka        - Not built
pyobjus      - Build OK (built at 2019-11-06 10:08:28.545049)
python2      - Not built
python3      - Build OK (built at 2019-11-05 21:26:17.034492)
pyyaml       - Not built
sdl2         - Build OK (built at 2019-11-05 21:15:32.028538)
sdl2_image   - Build OK (built at 2019-11-05 21:20:01.815235)
sdl2_mixer   - Build OK (built at 2019-11-05 21:21:32.198125)
sdl2_ttf     - Build OK (built at 2019-11-05 21:22:09.273458)
werkzeug     - Not built
zbarlight    - Not built

Hi try compile my app in xcode to my ipad. 
I got everytime this error. 
For any useful answer thanks in advance:).....

ld: warning: ignoring file /Users/karstenboettger/kivy-ios/dist/lib/libhostlibffi.a, building for iOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_pp_free_context", referenced from:
      _pp_uninit in libavfilter.a(vf_pp.o)
  "_pp_free_mode", referenced from:
      _pp_uninit in libavfilter.a(vf_pp.o)
  "_pp_get_context", referenced from:
      _pp_config_props in libavfilter.a(vf_pp.o)
  "_pp_get_mode_by_name_and_quality", referenced from:
      _pp_init in libavfilter.a(vf_pp.o)
  "_pp_postprocess", referenced from:
      _pp_filter_frame in libavfilter.a(vf_pp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing Recent Issues
Ignoring file /Users/karstenboettger/kivy-ios/dist/lib/libhostlibffi.a, building for iOS-arm64 but attempting to link with file built for macOS-x86_64

Undefined symbol: _pp_free_context

Undefined symbol: _pp_free_mode

Undefined symbol: _pp_get_context

Undefined symbol: _pp_get_mode_by_name_and_quality

Undefined symbol: _pp_postprocess

**Comment by Zen-CODE** [comment]
Please could you:
1. Update your kivy-ios checkout.
2. Clean all recipes and try building again.

If you still get and error, please post the exact error as well as the command you entered. 
Thanks

**Comment by Zen-CODE** [comment]
We can't help without feedback. Feel free to re-open if you have retried with the newer checkout and have fresh information.
