### ISSUE TITLE
KIVY_IMAGE is broke for pil

### ISSUE THREAD

**Issue by GoBig87** [kivy/kivy-ios#425]
The current version of Kivy and 1.11.1 for Kivy-ios are broken for when setting pil as your image provider.

When setting 
`os.environ['KIVY_IMAGE'] = 'pil'`

Yields
`[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/private/var/containers/Bundle/Application/05A86DDE-04F4-4466-8D0F-E455926C425F/fin-aquatic-rentals.app/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.1 (default, Feb 15 2020, 16:10:24) 
[Clang 11.0.0 (clang-1100.0.33.17)]
[INFO   ] [Python      ] Interpreter at "/private/var/containers/Bundle/Application/05A86DDE-04F4-4466-8D0F-E455926C425F/fin-aquatic-rentals.app/fin-aquatic-rentals"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers:  (img_imageio, img_tex, img_dds, img_sdl2, img_ffpyplayer, img_gif, img_pil ignored)
[CRITICAL] [App         ] Unable to get any Image provider, abort.
`

Edit:  So far it looks like setting any image provider causes apps to crash on ios when booting up.

**Comment by Zen-CODE** [comment]
Is `pillow` installed? You should be able to do this via:
    $ python3 toolchain.py build pillow
And lastly, wild but worth a try:
    os.environ['KIVY_IMAGE'] = 'pillow'
Thanks

**Comment by GoBig87** [comment]
Found a work around.  I tried to import PIL right in the beginning of my app and it failed for a PYTHON_EGG_CACHE error.  I had already set it with 

`    root_folder = App().user_data_dir
    CACHE_DIR = os.path.join(root_folder, 'cache')
    os.environ['PYTHON_EGG_CACHE'] = CACHE_DIR`

because it was throwing errors later in my app.  So I moved os.environ['KIVY_IMAGE'] = 'pil' after setting up the PYTHON_EGG_CACHE and it works.  I'm guessing Kivy was trying to import PIL but was failing because the egg cache wasn't set but it was eating the errors in try/excepts.  So the root cause of the issue is that the PYTHON_EGG_CACHE needs to be set for ios.

**Comment by GoBig87** [comment]
Alright well that didn't load PIL as an image provider as I was import Kivy before I set the image provider.  In order to get PIL to load I had to set the PYTHON_EGG_CACHE before importing any Kivy modules.  I did this by

`
HOME_DIR = os.environ['HOME']
CACHE_DIR = os.path.join(HOME_DIR, 'Documents', 'cache')
os.environ['PYTHON_EGG_CACHE'] = CACHE_DIR
os.environ['KIVY_IMAGE'] = 'pil'
`

**Comment by Zen-CODE** [comment]
This seems resolved. Please re-open if misunderstood.
