### ISSUE TITLE
Missing "Purpose" string in Info.plist

### ISSUE THREAD

**Issue by Cheaterman** [kivy/kivy-ios#426]
I think we might have to update the cookiecutter Info.plist. I got the following message when recently submitting an update to an App Store app:

```
Dear Developer,
We identified one or more issues with a recent delivery for your app, "<APP_NAME>" <APP_VERSION> (<APP_BUILD>). Please correct the following issues, then upload again. 
ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy). 
Best regards,
The App Store Team
```

I honestly don't have much idea what to do at this point, but I'll try to fix the problem on my end (by manually editing the plist file until Apple accepts it) and append to this issue.

**Comment by Cheaterman** [comment]
https://stackoverflow.com/a/49439492

This seems to be how to do it. If you're as inept with XCode as I am:
- Change the "mode" of the left navigation bar to "Project navigator" by clicking the folder icon at the top left (labelled "Show the Project navigator").
- Open the "Resources" folder, you should see a file named "<yourapp>-Info.plist", double-click on it.
- At the top there's a dropdown labelled "Information Property list". If you hover over it or select it, a circular "+" button will appear, click it.
- In the dropdown that appears, select (or search) "Privacy - Camera Usage Description".
- In the "Value" field, either type why you need the camera, or type that you don't use it - I'm in the latter case, but Apple knows frameworks and libraries will cause false positives, I expect it to be OK.

Archive your app and submit it to the App Store again, it should work as expected. :-)

**Comment by brentpicasso** [comment]
I just ran into this as well. Was fairly straightforward to fix, but the template should be updated, agreed.

**Comment by yairchu** [comment]
I think that the correct fix may be to also have kivy built without ios camera support, and let the user choose which version they need. Then the version without camera would not need this permission.

**Comment by Zen-CODE** [comment]
There are several good arguments against including this is the template.
1. Not all kivy-ios apps need or use the camera.
2. To include a "generic" purpose in the template would miss the point of providing a purpose: to explain to the user why your particular app wants it.
3. Including a generic "purpose" would almost certainly raise a red flag with Apple, as it's subverting the intent of the feature and could well result is all kivy apps being banned.

For these reason, I don't think adding this to a template is the right approach. Please feel free to reopen or debate this issue if you disagree.

**Comment by Cheaterman** [comment]
I'm fine with that, but we need a counter-proposal. Yair suggested making
camera support actually optional, which would be a great idea? It's either
one or the other, but packaging for iOS is confusing enough for people who
aren't familiar with the ecosystem without adding extra hoops for them to
jump through, IMHO. The very least we should do is to at least document
this?

**Comment by Zen-CODE** [comment]
Agreed. I wish Apple themselves documented this better, as it's an XCode issue really. Yair's suggestion is really nice and it would be great if someone could add that in a PR. I suppose what we lack is a way to distinguish between requests vs. reporting an issue? I think that certainly warrants further investigation as that is an important distinction that is not currently handled.

**Comment by Cheaterman** [comment]
This IMHO is an issue anyway, even though (as with many issues...) a new
feature could address it.

It's totally an XCode issue, and Apple documentation totally sucks (because
apparently you're supposed to watch their conferences to get the
information...) ; nonetheless, in my mind, kivy-ios was really meant to
abstract over these nitty gritty details nobody cares about. So, one way or
the other, we need to make the abstraction less leaky ; either that or we
can just give up and merely document the issue.

FWIW, your arguments against including this in the template are generally
unwarranted ; Apple themselves say (paraphrasing) "it is a valid reason to
state some technologies/libraries you're using require the camera even if
your application doesn't use it".

I'm in favor of including a "generic purpose" - I've been maintaining a few
apps on the App Store for a while, and I can tell you Apple will be careful
enough to check that you're actually not using the camera if you say you
aren't. As to getting all Kivy apps banned from the App Store, I honestly
doubt it. As I said, it's a valid reason (according to them) to say "this
technology I'm using supports the camera but I don't use it".

Le dim. 17 mai 2020 à 13:37, Richard Larkin <notifications@github.com> a
écrit :

**Comment by HeRo002** [comment]
The Apple App Store still complaints that the Info.plist of a Kivy app that does NOT use the camera misses the NSCameraUsageDescription key:

> " ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “geo-esp-training.app” bundle should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.
> 
> Apple Developer Relations"
