### ISSUE TITLE
Build with Custom Package (no recipe)

### ISSUE THREAD

**Issue by fire17** [kivy/kivy-ios#431]
Hi there!
trying to run pyatv on iOS
./toolchain.py build pyatv  -> gives " No recipe named pyatv "
How can write a recipe for a new package?

anyone know's how to compile python including non-pure libraries???
i.e ones that can be installed easily with pip

how about DL and install on runtime?
anyone got a clue??
thanks alot and peaceful times for all!!

**Comment by NameKhan72** [comment]
Hello, 

unfortunately the toolchain needs a recipe for any package that has non-pure-python components. For example numpy uses compiled code and therefore needs a recipe to work.
Any pure python packages can be installed without a recipe through:
./toolchain.py pip install <package_name>

**Comment by Zen-CODE** [comment]
@fire17 Like @NameKhan72  (thanks!) said. You can look here for example recipes. And please feel free to post on the Kivy forums or discord if you have
 problems.
https://github.com/kivy/kivy-ios/tree/master/kivy_ios/recipes
