### ISSUE TITLE
unable to build kivy using toolchain

### ISSUE THREAD

**Issue by alexbuyan** [kivy/kivy-ios#432]
whenI run:
./toolchain.py build python3 kivy

the output is:
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

if I use python 2 and run:
sudo ./toolchain.py build python2 kivy

the output is:
STDOUT:
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
  File "setup.py", line 1102
    def glob_paths(*patterns, excludes=('.pyc', )):
                                     ^
SyntaxError: invalid syntax

  STDERR:

How can I fix this problem and build kivy for my project?

**Comment by misl6** [comment]
Can you please try:
`python3 toolchain.py build python3 kivy` ?

**Comment by alexbuyan** [comment]
@misl6, well, that's worked, thx. Now the problem is there is no requests in my xcodeproj.

**Comment by faybak** [comment]
hello @alexbuyan, i have the issue about 'pyobjus.pyobjus.ObjcException: Unable to find class b'adSwitch''. Did you find any solution please?

**Comment by Zen-CODE** [comment]
Okay, that seems to be a separate issue and no longer an issue building kivy. Please open a new ticket with the instructions on how to reproduce and the full error log.

Thanks
