### ISSUE TITLE
$./toolchain.py build kivy gives error -TypeError: join() argument must be str or bytes, not 'NoneType'

### ISSUE THREAD

**Issue by banana145** [kivy/kivy-ios#433]
when I run: python3 toolchain.py build python3 kivy
the output is：
toolchain.py:93: DeprecationWarning: ChromeDownloader style of invoking requests is deprecated. Use newer urlopen functions/methods
  urlretrieve = ChromeDownloader().retrieve
[INFO    ] Building with 2 processes, where supported
[INFO    ] Want to build ['python3', 'kivy']
[INFO    ] Loaded recipe python3 (depends of ['hostpython3', 'libffi', 'openssl'], optional are [])
[INFO    ] Loaded recipe kivy (depends of ['sdl2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'ios', 'pyobjus', 'python'], optional are [])
[INFO    ] Loaded recipe hostpython3 (depends of [], optional are ['openssl'])
[INFO    ] Loaded recipe libffi (depends of [], optional are [])
[INFO    ] Loaded recipe openssl (depends of [], optional are [])
[INFO    ] Loaded recipe sdl2 (depends of [], optional are [])
[INFO    ] Loaded recipe sdl2_image (depends of ['sdl2'], optional are [])
[INFO    ] Loaded recipe sdl2_mixer (depends of ['sdl2'], optional are [])
[INFO    ] Loaded recipe sdl2_ttf (depends of ['sdl2', 'freetype'], optional are [])
[INFO    ] Loaded recipe ios (depends of ['python'], optional are [])
[INFO    ] Loaded recipe pyobjus (depends of ['python'], optional are [])
[INFO    ] Loaded recipe python (depends of ['python3'], optional are [])
[INFO    ] Loaded recipe freetype (depends of [], optional are [])
[INFO    ] Build order is ['freetype', 'libffi', 'openssl', 'sdl2', 'hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'python', 'ios', 'pyobjus', 'kivy']
[INFO    ] Recipe order is ['freetype', 'libffi', 'openssl', 'sdl2', 'hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'ios', 'pyobjus', 'kivy']
[INFO    ] Include dir added: {arch.arch}/freetype
[INFO    ] Include dir added: {arch.arch}/ffi
[INFO    ] Include dir added: {arch.arch}/openssl
[INFO    ] Include dir added: common/sdl2
[INFO    ] Global: hostpython located at /Users/cjmacos/kivy-ios/dist/hostpython3/bin/python
[INFO    ] Global: hostpgen located at /Users/cjmacos/kivy-ios/dist/hostpython3/bin/pgen
[INFO    ] Include dir added: common/sdl2_image
[INFO    ] Include dir added: common/sdl2_mixer
[INFO    ] Include dir added: common/sdl2_ttf
[DEBUG   ] Cached result: Download freetype. Ignoring
[INFO    ] Extract freetype
[INFO    ] Extract freetype for x86_64
[WARNING ] Error extracting the archive /Users/cjmacos/kivy-ios/.cache/freetype-freetype-2.5.5.tar.bz2
[WARNING ] This is usually caused by a corrupt download. The file will be removed and re-downloaded on the next run.
[WARNING ] /Users/cjmacos/kivy-ios/.cache/freetype-freetype-2.5.5.tar.bz2
Traceback (most recent call last):
  File "toolchain.py", line 1568, in <module>
    ToolchainCL()
  File "toolchain.py", line 1281, in __init__
    getattr(self, args.command)()
  File "toolchain.py", line 1322, in build
    build_recipes(args.recipe, ctx)
  File "toolchain.py", line 1158, in build_recipes
    recipe.execute()
  File "/Users/cjmacos/kivy-ios/toolchain.py", line 728, in execute
    self.extract()
  File "/Users/cjmacos/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/cjmacos/kivy-ios/toolchain.py", line 772, in extract
    self.extract_arch(arch.arch)
  File "/Users/cjmacos/kivy-ios/toolchain.py", line 776, in extract_arch
    dest_dir = join(build_dir, self.archive_root)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
How can I fix this problem and build kivy for my project?Thanks!

**Comment by rasmuskreiner** [comment]
For what its worth. I had the same error on openssl. I managed to solve the issue by manually downloading the library and putting it into the .cache folder. Maybe you could try the same with: freetype-freetype-2.5.5.tar.bz2.

**Comment by banana145** [comment]
> For what its worth. I had the same error on openssl. I managed to solve the issue by manually downloading the library and putting it into the .cache folder. Maybe you could try the same with: freetype-freetype-2.5.5.tar.bz2.

Thanks for your reply, I have solved the issue by using your method.

**Comment by arsakif** [comment]
> For what its worth. I had the same error on openssl. I managed to solve the issue by manually downloading the library and putting it into the .cache folder. Maybe you could try the same with: freetype-freetype-2.5.5.tar.bz2.

Hi, May you please tell me how can I download it?
