### ISSUE TITLE
Having problems with the "python3 toolchain.py build python3 openssl kivy" command

### ISSUE THREAD

**Issue by RustyRyan98** [kivy/kivy-ios#435]
Ive followed all the instructions carefully, ive successfully built kivy but it tells me i have to build the recipes to compile my project. Here is the error i'm running into. please ive been struggling with this for a week. Here is my error

``MT apps/opt.o -c -o apps/opt.o apps/opt.c
[DEBUG   ] clangclangclangclang: : : : warningwarning: : warning: warning: no such sysroot directory: '/SDKs/' [-Wmissing-sysroot]
[DEBUG   ] no such sysroot directory: '/SDKs/' [-Wmissing-sysroot]no such sysroot directory: '/SDKs/' [-Wmissing-sysroot]
[DEBUG   ] 
[DEBUG   ] no such sysroot directory: '/SDKs/' [-Wmissing-sysroot]
[DEBUG   ] apps/bf_prefix.c:10:10: fatal error: 'stdio.h' file not found
[DEBUG   ] apps/apps.c:18:10: fatal error: 'stdio.h' file not found
[DEBUG   ] #include <stdio.h>#include <stdio.h>
[DEBUG   ] 
[DEBUG   ]          ^~~~~~~~~         ^~~~~~~~~
[DEBUG   ] 
[DEBUG   ] In file included from apps/app_rand.c:10:
[DEBUG   ] In file included from apps/apps.h:13:
[DEBUG   ] In file included from ./e_os.h:16:
[DEBUG   ] In file included from include/openssl/e_os2.h:243:
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include/inttypes.h:30:15: fatal error: 
[DEBUG   ]       'inttypes.h' file not found
[DEBUG   ] #include_next <inttypes.h>
[DEBUG   ]               ^~~~~~~~~~~~
[DEBUG   ] In file included from apps/opt.c:9:
[DEBUG   ] In file included from apps/apps.h:13:
[DEBUG   ] In file included from ./e_os.h:16:
[DEBUG   ] In file included from include/openssl/e_os2.h:243:
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include/inttypes.h:30:15: fatal error: 
[DEBUG   ]       'inttypes.h' file not found
[DEBUG   ] #include_next <inttypes.h>
[DEBUG   ]               ^~~~~~~~~~~~
[DEBUG   ] 1 error generated.
[DEBUG   ] 1 error generated.
[DEBUG   ] make[1]: *** [apps/bf_prefix.o] Error 1
[DEBUG   ] make[1]: *** Waiting for unfinished jobs....
[DEBUG   ] 1 error generated.
[DEBUG   ] make[1]: *** [apps/app_rand.o] Error 1
[DEBUG   ] make[1]: *** [apps/opt.o] Error 1
[DEBUG   ] 1 error generated.
[DEBUG   ] make[1]: *** [apps/apps.o] Error 1
[DEBUG   ] make: *** [build_libs] Error 2
Traceback (most recent call last):
  File "toolchain.py", line 1568, in <module>
    ToolchainCL()
  File "toolchain.py", line 1281, in __init__
    getattr(self, args.command)()
  File "toolchain.py", line 1322, in build
    build_recipes(args.recipe, ctx)
  File "toolchain.py", line 1158, in build_recipes
    recipe.execute()
  File "/Users/temitayoadefemi/Desktop/kivy-ios/toolchain.py", line 729, in execute
    self.build_all()
  File "/Users/temitayoadefemi/Desktop/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/temitayoadefemi/Desktop/kivy-ios/toolchain.py", line 837, in build_all
    self.build(arch)
  File "/Users/temitayoadefemi/Desktop/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/temitayoadefemi/Desktop/kivy-ios/toolchain.py", line 811, in build
    self.build_arch(arch)
  File "/Users/temitayoadefemi/Desktop/kivy-ios/recipes/openssl/__init__.py", line 46, in build_arch
    shprint(sh.make, self.ctx.concurrent_make, "build_libs")
  File "/Users/temitayoadefemi/Desktop/kivy-ios/toolchain.py", line 67, in shprint
    for line in cmd:
  File "tools/external/sh.py", line 565, in next
    self.wait()
  File "tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/usr/bin/make -j4 build_libs'

  STDOUT:
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _build_libs
/tmp/tmp_2lmt20v  -I. -Iinclude -fPIC -isysroot /SDKs/ -fno-common -O3 -miphoneos-version-min=8.0 -I/Users/temitayoadefemi/Desktop/kivy-ios/dist/include/arm64/freetype -I/Users/temitayoadefemi/Desktop/kivy-ios/dist/include/arm64/... (4944 more, please see e.stdout)

  STDERR:

**Comment by misl6** [comment]
XCode and MacOS version?

**Comment by RustyRyan98** [comment]
Xcode 10.3 and MacOS Catalina 10.15.3, Thank you

**Comment by RustyRyan98** [comment]
I should note that i put the latest version of openssl in the directory, due to the link to download openssl isnt valid again. that might be the reason for the error. im not sure

**Comment by RustyRyan98** [comment]
I recloned kivy-ios from github, and download openssl from a different source and set the path
