### ISSUE TITLE
My kivy Xcode project is getting a build error "Operation not Permitted"

### ISSUE THREAD

**Issue by RustyRyan98** [kivy/kivy-ios#436]
I receive this error anytime i try to build my kivy xcode app. Please i would appreciate any help. Below is the code. "open /Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib: Operation not permitted". ill appreciate if anyone could assist me as this is my first kivy xcode project. Thank you 

Here is the full error: 

CpResource /Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib /Users/temitayoadefemi/Library/Developer/Xcode/DerivedData/chargie-edqskvsfagirhvaorkvnzwjjcexz/Build/Products/Debug-iphonesimulator/chargie.app/lib (in target: chargie)
    cd /Users/temitayoadefemi/Desktop/kivy-ios/chargie-ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib /Users/temitayoadefemi/Library/Developer/Xcode/DerivedData/chargie-edqskvsfagirhvaorkvnzwjjcexz/Build/Products/Debug-iphonesimulator/chargie.app

error: open /Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib: Operation not permitted

**Comment by gunerguney** [comment]
I would recommend you to watch Erik Sandberg's videos. I encountered with the same error and added -O --no-perms to build phases tab. He mentioned permission error in this video https://www.youtube.com/watch?v=UAi3PG-qN2k

**Comment by RustyRyan98** [comment]
Yeah I watched the video, it was showing a different error before it showed ‘Operation not permitted’. I’ve added “-O --no-perms” before I received that error

**Comment by gunerguney** [comment]
Did you allow the Xcode from mac's security & privacy interface?

**Comment by RustyRyan98** [comment]
How do you do that ?

**Comment by gunerguney** [comment]
open System Preferences, then head to Security & Privacy > Privacy > Accessibility. 

![image](https://user-images.githubusercontent.com/5878041/78938316-ab05a100-7aba-11ea-93c3-4e88537f172b.png)

**Comment by RustyRyan98** [comment]
I appreciate the help bro, but i didnt work.  is there anyway i can use sudo in Xcode to open the file?

**Comment by RustyRyan98** [comment]
Sorry, Not very familiar with xcode

**Comment by RustyRyan98** [comment]
Solved it, gave full disk access to xcode in system preferences
