### ISSUE TITLE
Toolchain unable to download openssl from link (http://www.openssl.org/source/openssl-1.0.2k.tar.gz)

### ISSUE THREAD

**Issue by Joepbaasman** [kivy/kivy-ios#437]
I get the following error when doing ./toolchain.py build python3 kivy openssl:

`[DEBUG   ] ** BUILD SUCCEEDED **
[DEBUG   ] 
[DEBUG   ] 
[INFO    ] Postbuild libffi for arm64
[DEBUG   ] Invoking postbuild_arm64
[DEBUG   ] New State: libffi.build.arm64 at 2020-04-10 11:20:14.458211
[INFO    ] Create lipo library for libffi
[INFO    ] Lipo libffi to /Users/-/Desktop/Programmeren/Venv/kivy-ios/dist/lib/libffi.a
[INFO    ] Make_lipo libffi
[INFO    ] Running Shell: /usr/bin/lipo ('-create', '-output', '/Users/-/Desktop/Programmeren/Venv/kivy-ios/dist/lib/libffi.a', '-arch', 'x86_64', '/Users/-/Desktop/Programmeren/Venv/kivy-ios/build/libffi/x86_64/libffi-3.2.1/build/Release-iphonesimulator/libffi.a', '-arch', 'arm64', '/Users/-/Desktop/Programmeren/Venv/kivy-ios/build/libffi/arm64/libffi-3.2.1/build/Release-iphoneos/libffi.a') {'_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[DEBUG   ] New State: libffi.make_lipo./Users/-/Desktop/Programmeren/Venv/kivy-ios/dist/lib/libffi.a at 2020-04-10 11:20:14.496399
[INFO    ] Install include files for libffi
[INFO    ] Install_include libffi
[DEBUG   ] New State: libffi.install_include at 2020-04-10 11:20:14.501014
[INFO    ] Install frameworks for libffi
[INFO    ] Install_frameworks libffi
[DEBUG   ] New State: libffi.install_frameworks at 2020-04-10 11:20:14.501738
[INFO    ] Install sources for libffi
[INFO    ] Install_sources libffi
[DEBUG   ] New State: libffi.install_sources at 2020-04-10 11:20:14.502515
[INFO    ] Install libffi
[INFO    ] Install libffi
[DEBUG   ] New State: libffi.install at 2020-04-10 11:20:14.503498
[DEBUG   ] New State: libffi.build_all at 2020-04-10 11:20:14.504793
[INFO    ] Download openssl
[INFO    ] Downloading http://www.openssl.org/source/openssl-1.0.2k.tar.gz
Traceback (most recent call last):
  File "./toolchain.py", line 1568, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1281, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1322, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 1158, in build_recipes
    recipe.execute()
  File "/Users/-/Desktop/Programmeren/Venv/kivy-ios/toolchain.py", line 727, in execute
    self.download()
  File "/Users/-/Desktop/Programmeren/Venv/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/-/Desktop/Programmeren/Venv/kivy-ios/toolchain.py", line 762, in download
    self.download_file(self.url.format(version=self.version), fn)
  File "/Users/-/Desktop/Programmeren/Venv/kivy-ios/toolchain.py", line 479, in download_file
    urlretrieve(url, filename, report_hook)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1819, in retrieve
    block = fp.read(bs)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file`

**Comment by RustyRyan98** [comment]
download it from this link https://wiki.unify.com/wiki/openssl-1.0.2k.tar.gz_V1R0 and use "mv" command in terminal to change the path to the required path

**Comment by RustyRyan98** [comment]
Like this "mv openssl-1.0.2f.tar.gz .cache/openssl-openssl-1.0.2f.tar.gz"

**Comment by Joepbaasman** [comment]
> download it from this link https://wiki.unify.com/wiki/openssl-1.0.2k.tar.gz_V1R0 and use "mv" command in terminal to change the path to the required path

**thanks!, this brought me a little closer to solving the issue. But now i'm getting the following error. Looks like the file is missing some parts:** 
`[DEBUG   ] building '_decimal' extension
[DEBUG   ] /var/folders/qd/q0jr2v2x1yjg3t_qc33mhsch0000gn/T/tmpbk341xpm -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/freetype -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/ffi -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/openssl -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_image -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_mixer -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_ttf -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -I./Include -I. -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/include -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c _curses_panel.c -o build/temp.ios-x86_64-3.7/_curses_panel.o
[DEBUG   ] clang: error: no such file or directory: '_testmultiphase.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] clang: error: no such file or directory: 'mmapmodule.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] building '_multiprocessing' extension
[DEBUG   ] building '_bz2' extension
[DEBUG   ] /var/folders/qd/q0jr2v2x1yjg3t_qc33mhsch0000gn/T/tmpbk341xpm -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/freetype -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/ffi -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/openssl -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_image -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_mixer -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_ttf -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -I./Include -I. -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/include -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c _cursesmodule.c -o build/temp.ios-x86_64-3.7/_cursesmodule.o
[DEBUG   ] building 'xxlimited' extension
[DEBUG   ] clang: error: no such file or directory: 'readline.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] /var/folders/qd/q0jr2v2x1yjg3t_qc33mhsch0000gn/T/tmpbk341xpm -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/freetype -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/ffi -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/openssl -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_image -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_mixer -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_ttf -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -DMODULE_NAME="sqlite3" -DSQLITE_OMIT_LOAD_EXTENSION=1 -IModules/_sqlite -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include -I./Include -I. -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/include -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c _sqlite/cache.c -o build/temp.ios-x86_64-3.7/_sqlite/cache.o
[DEBUG   ] building '_lzma' extension
[DEBUG   ] /var/folders/qd/q0jr2v2x1yjg3t_qc33mhsch0000gn/T/tmpbk341xpm -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/freetype -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/ffi -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/openssl -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_image -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_mixer -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_ttf -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -I./Include -I. -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/include -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c _lzmamodule.c -o build/temp.ios-x86_64-3.7/_lzmamodule.o
[DEBUG   ] clang: error: no such file or directory: '_posixsubprocess.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] /var/folders/qd/q0jr2v2x1yjg3t_qc33mhsch0000gn/T/tmpbk341xpm -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/freetype -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/ffi -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/openssl -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_image -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_mixer -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_ttf -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -I./Include -I. -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/include -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c _bz2module.c -o build/temp.ios-x86_64-3.7/_bz2module.o
[DEBUG   ] /var/folders/qd/q0jr2v2x1yjg3t_qc33mhsch0000gn/T/tmpbk341xpm -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/freetype -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/ffi -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/openssl -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_image -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_mixer -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_ttf -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -DPy_LIMITED_API=0x03050000 -I./Include -I. -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/include -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c xxlimited.c -o build/temp.ios-x86_64-3.7/xxlimited.o
[DEBUG   ] creating build/temp.ios-x86_64-3.7/_decimal
[DEBUG   ] clang: error: no such file or directory: '_curses_panel.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] clang: error: no such file or directory: '_dbmmodule.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] creating build/temp.ios-x86_64-3.7/_multiprocessing
[DEBUG   ] /var/folders/qd/q0jr2v2x1yjg3t_qc33mhsch0000gn/T/tmpbk341xpm -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/freetype -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/ffi -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/openssl -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_image -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_mixer -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_ttf -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -IModules/_multiprocessing -I./Include -I. -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/include -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c _multiprocessing/multiprocessing.c -o build/temp.ios-x86_64-3.7/_multiprocessing/multiprocessing.o
[DEBUG   ] clang: error: no such file or directory: '_xxtestfuzz/_xxtestfuzz.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] creating build/temp.ios-x86_64-3.7/_decimal/libmpdec
[DEBUG   ] /var/folders/qd/q0jr2v2x1yjg3t_qc33mhsch0000gn/T/tmpbk341xpm -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/freetype -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/ffi -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/openssl -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_image -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_mixer -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2_ttf -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -DCONFIG_64=1 -DASM=1 -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/Modules/_decimal/libmpdec -I./Include -I. -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/include -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c _decimal/_decimal.c -o build/temp.ios-x86_64-3.7/_decimal/_decimal.o
[DEBUG   ] clang: error: no such file or directory: '_lzmamodule.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] clang: error: no such file or directory: '_cursesmodule.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] clang: error: no such file or directory: '_bz2module.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] clang: error: no such file or directory: '_sqlite/cache.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] clang: error: no such file or directory: 'xxlimited.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] clang: error: no such file or directory: '_multiprocessing/multiprocessing.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] clang: error: no such file or directory: '_decimal/_decimal.c'
[DEBUG   ] clang: error: no input files
[DEBUG   ] 
[DEBUG   ] Python build finished successfully!
[DEBUG   ] The necessary bits to build these optional modules were not found:
[DEBUG   ] _elementtree       _gdbm              _hashlib        
[DEBUG   ] _ssl               _tkinter           _uuid           
[DEBUG   ] nis                ossaudiodev        spwd            
[DEBUG   ] To find the necessary bits, look in setup.py in detect_modules() for the module's name.
[DEBUG   ] 
[DEBUG   ] 
[DEBUG   ] The following modules found by detect_modules() in setup.py, have been
[DEBUG   ] built by the Makefile instead, as configured by the Setup files:
[DEBUG   ] _abc               _asyncio           _bisect         
[DEBUG   ] _blake2            _codecs_cn         _codecs_hk      
[DEBUG   ] _codecs_iso2022    _codecs_jp         _codecs_kr      
[DEBUG   ] _codecs_tw         _contextvars       _crypt          
[DEBUG   ] _csv               _ctypes            _ctypes_test    
[DEBUG   ] _datetime          _heapq             _json           
[DEBUG   ] _lsprof            _md5               _multibytecodec 
[DEBUG   ] _opcode            _pickle            _queue          
[DEBUG   ] _random            _sha1              _sha256         
[DEBUG   ] _sha3              _sha512            _socket         
[DEBUG   ] _struct            _testbuffer        _testcapi       
[DEBUG   ] _testimportmultiple   array              atexit          
[DEBUG   ] audioop            binascii           cmath           
[DEBUG   ] fcntl              grp                math            
[DEBUG   ] parser             pwd                pyexpat         
[DEBUG   ] resource           select             syslog          
[DEBUG   ] termios            time               unicodedata     
[DEBUG   ] zlib                                                  
[DEBUG   ] 
[DEBUG   ] 
[DEBUG   ] Failed to build these modules:
[DEBUG   ] _bz2               _curses            _curses_panel   
[DEBUG   ] _dbm               _decimal           _lzma           
[DEBUG   ] _multiprocessing   _posixsubprocess   _sqlite3        
[DEBUG   ] _testmultiphase    _xxtestfuzz        mmap            
[DEBUG   ] readline           xxlimited                          
[DEBUG   ] 
[DEBUG   ] 
[DEBUG   ] Could not build the ssl module!
[DEBUG   ] Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host().
[DEBUG   ] LibreSSL 2.6.4 and earlier do not provide the necessary APIs, https://github.com/libressl-portable/portable/issues/381
[DEBUG   ] 
[DEBUG   ] running build_scripts
[DEBUG   ] creating build/scripts-3.7
[DEBUG   ] error: file '/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/Tools/scripts/pydoc3' does not exist
[DEBUG   ] make: *** [sharedmods] Error 1
Traceback (most recent call last):
  File "./toolchain.py", line 1568, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1281, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1322, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 1158, in build_recipes
    recipe.execute()
  File "/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/toolchain.py", line 729, in execute
    self.build_all()
  File "/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/toolchain.py", line 837, in build_all
    self.build(arch)
  File "/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/toolchain.py", line 811, in build
    self.build_arch(arch)
  File "/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/recipes/python3/__init__.py", line 122, in build_arch
    shprint(sh.make, self.ctx.concurrent_make)
  File "/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/toolchain.py", line 67, in shprint
    for line in cmd:
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/usr/bin/make -j16'

  STDOUT:
Makefile:1865: warning: overriding commands for target `Modules/_math.o'
Makefile:605: warning: ignoring old commands for target `Modules/_math.o'
/var/folders/qd/q0jr2v2x1yjg3t_qc33mhsch0000gn/T/tmpbk341xpm -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/freetype -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/ffi -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/x86_64/openssl -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_venv/kivy-ios/dist/include/common/sdl2 -I/Users/joepraithel/Desktop/Programmeren/Venv/Kivy_ven... (298615 more, please see e.stdout)

  STDERR:

`
