### ISSUE TITLE
Cant create kivy-ios project, getting error code. FileNotFoundError: [Errno 2] No such file or directory: '/Users/temitayoadefemi/Desktop/kivy-ios/yest1-ios/./icon.png'

### ISSUE THREAD

**Issue by RustyRyan98** [kivy/kivy-ios#438]
Cant create kivy-ios project, getting error code. FileNotFoundError: [Errno 2] No such file or directory: '/Users/temitayoadefemi/Desktop/kivy-ios/yest1-ios/./icon.png' please i need help

**Comment by misl6** [comment]
Can you please attach some code for reproducing the issue + MacOS and XCode versions?

**Comment by RustyRyan98** [comment]
I recloned kivy-ios and built kivy and the recipes again and it solved it
