### ISSUE TITLE
unable to build python3 using toolchain.py

### ISSUE THREAD

**Issue by ranimRR** [kivy/kivy-ios#441]
Hi
 I am using macOS Catalina 10.15.3 and Xcode 11.4 and I have  an issue when using
`python3 toolchain.py build python3 openssl kivy`

The issue:
`
[DEBUG   ] checking build system type... x86_64-apple-darwin19.3.0
[DEBUG   ] checking host system type... aarch64-apple-darwin13
[DEBUG   ] checking for aarch64-apple-darwin13-gcc... /var/folders/c9/dt7knwhx21jgz2wy49bb9xw80000gn/T/tmpdqc6j9qf
[DEBUG   ] checking whether the C compiler works... yes
[DEBUG   ] checking for C compiler default output file name... a.out
[DEBUG   ] checking for suffix of executables... 
[DEBUG   ] checking whether we are cross compiling... yes
[DEBUG   ] checking for suffix of object files... o
[DEBUG   ] checking whether we are using the GNU C compiler... yes
[DEBUG   ] checking whether /var/folders/c9/dt7knwhx21jgz2wy49bb9xw80000gn/T/tmpdqc6j9qf accepts -g... yes
[DEBUG   ] checking for /var/folders/c9/dt7knwhx21jgz2wy49bb9xw80000gn/T/tmpdqc6j9qf option to accept ISO C89... unsupported
[DEBUG   ] checking how to run the C preprocessor... /lib/cpp
[DEBUG   ] configure: error: in `/Users/ranimfaraj/Desktop/kivy-ios/build/freetype/arm64/freetype-2.5.5/builds/unix':
[DEBUG   ] configure: error: C preprocessor "/lib/cpp" fails sanity check
[DEBUG   ] See `config.log' for more details
[DEBUG   ] make: *** [setup] Error 1
Traceback (most recent call last):
  File "toolchain.py", line 1568, in <module>
    ToolchainCL()
  File "toolchain.py", line 1281, in __init__
    getattr(self, args.command)()
  File "toolchain.py", line 1322, in build
    build_recipes(args.recipe, ctx)
  File "toolchain.py", line 1158, in build_recipes
    recipe.execute()
  File "/Users/ranimfaraj/Desktop/kivy-ios/toolchain.py", line 729, in execute
    self.build_all()
  File "/Users/ranimfaraj/Desktop/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/ranimfaraj/Desktop/kivy-ios/toolchain.py", line 837, in build_all
    self.build(arch)
  File "/Users/ranimfaraj/Desktop/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/ranimfaraj/Desktop/kivy-ios/toolchain.py", line 811, in build
    self.build_arch(arch)
  File "/Users/ranimfaraj/Desktop/kivy-ios/recipes/freetype/__init__.py", line 29, in build_arch
    "--enable-shared=no")
  File "/Users/ranimfaraj/Desktop/kivy-ios/toolchain.py", line 67, in shprint
    for line in cmd:
  File "tools/external/sh.py", line 565, in next
    self.wait()
  File "tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/Users/ranimfaraj/Desktop/kivy-ios/build/freetype/arm64/freetype-2.5.5/configure CC=/var/folders/c9/dt7knwhx21jgz2wy49bb9xw80000gn/T/tmpdqc6j9qf LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld CFLAGS=-O3 -miphoneos-version-min=8.0 -I/Users/ranimfaraj/Desktop/kivy-ios/dist/include/arm64/freetype -I/Users/ranimfaraj/Desktop/kivy-ios/dist/include/arm64/ffi -I/Users/ranimfaraj/Desktop/kivy-ios/dist/include/arm64/openssl -I/Users/ranimfaraj/Desktop/kivy-ios/dist/include/common/sdl2 -I/Users/ranimfaraj/Desktop/kivy-ios/dist/include/common/sdl2_image -I/Users/ranimfaraj/Desktop/kivy-ios/dist/include/common/sdl2_mixer -I/Users/ranimfaraj/Desktop/kivy-ios/dist/include/common/sdl2_ttf -I/Users/ranimfaraj/Desktop/kivy-ios/dist/include/arm64 LDFLAGS=-arch arm64 -L/Users/ranimfaraj/Desktop/kivy-ios/dist/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/usr/lib -miphoneos-version-min=8.0 --prefix=/ --host=aarch64-apple-darwin13 --without-png --without-bzip2 --without-fsspec --without-harfbuzz --without-old-mac-fonts --enable-static=yes --enable-shared=no'

  STDOUT:

FreeType build system -- automatic system detection

The following settings are used:

  platform                    unix
  compiler                    cc
  configuration directory     ./builds/unix
  configuration rules         ./builds/unix/unix.mk

If this does not correspond to your system or settings please remove the file
`config.mk' from this directory then read the INSTALL file for help.

Otherwise, simply type `/Applications/Xcode.app/Contents/Developer/usr/bin/make' again to build the library,
or `/Applications/Xcode.app/Contents/Developer/usr/bin/make refdoc' to build the API reference (this needs python >= 2.6).

Generating modules list in ./objs/ftmodule.h...
* module: truetype  (Windows/Mac font files with extension *.ttf or ... (3145 more, please see e.stdout)

  STDERR:

`

**Comment by misl6** [comment]
I think that some logs are missing.
Can you please do a clean build and post the logs again?

**Comment by ranimRR** [comment]
Thank you @misl6 it is somehow fixed,
