### ISSUE TITLE
Update doc : support iOS with python 3

### ISSUE THREAD

**Issue by yahya-abou-imran** [kivy/kivy-ios#442]
Hi everyone!

From [the doc](https://kivy.org/doc/stable/guide/packaging-ios.html) it says:

> Note
> 
> Currently, packages for iOS can only be generated with Python 2.7. Python 3.4+ support is on the way.
> 

But [here](https://github.com/kivy/kivy-ios/blob/master/README.md) you can see:

> You can select between Python 2.7 or Python 3.7 by specifying the recipes python2 or python3 when building.

It is worth an update!

**Comment by AndreMiras** [comment]
Thanks for the heads up, feel free to pull request it

**Comment by Zen-CODE** [comment]
@yahya-abou-imran Thanks. Yes, that happens because the docs have been updated, but the changes will only be seen on the main page when the next stable release is made. Hopefully soon. :-)
