### ISSUE TITLE
./Toolchain.py create can't find compiled python file

### ISSUE THREAD

**Issue by ghost** [kivy/kivy-ios#444]
When I try to make a xcode project with toolchain it gives me the error that it didn't find any compiled python files. I'm sure however that my folder is set correct. Can anyone help with this issue?
<img width="248" alt="Schermafbeelding 2020-04-14 om 14 11 27" src="https://user-images.githubusercontent.com/63453799/79223550-db9e5f80-7e59-11ea-893d-786bfb046168.png">

**Comment by Zen-CODE** [comment]
Pleas post the exact command you entered and the complete error message.

**Comment by Zen-CODE** [comment]
We need feedback in order to help.
