### ISSUE TITLE
Pandas - Kivy-ios

### ISSUE THREAD

**Issue by ranimRR** [kivy/kivy-ios#447]
Hi 
Does pandas now works with Kivy-ios ? Because I am having an issue with numpy with pandas?

**Comment by Zen-CODE** [comment]
Hi. You would need a recipe for that as pandas is not officially supported. But please post the question on the Kivy forum here: https://groups.google.com/forum/#!forum/kivy-users

This issue tracker is reserved for reporting demonstrable faults in kivy-ios. Thanks.
