### ISSUE TITLE
python3 toolchain.py build python3 kivy fails - zlib

### ISSUE THREAD

**Issue by hoba87** [kivy/kivy-ios#457]
trying to compile kivy gives me an error regarding zlib:

macOS 10.14.6
Xcode 11.3.1
host python 3.7.4
kivy 1.11.1
kivy-ios: latest

I've tried setting LDFLAGS to system zlib and to zlib installed with homebrew (both 1.2.11), with no success.

> [DEBUG   ] clang -Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -L/Users/user/repositories/kivy-ios/dist/hostlibffi/usr/local/lib -lsqlite3 -lffi -L/Users/user/repositories/kivy-ios/dist/hostlibffi/usr/local/lib   -Wl,-stack_size,1000000  -framework CoreFoundation -o python.exe Programs/python.o libpython3.8.a -ldl   -framework CoreFoundation -lz
>                          
> [DEBUG   ] clang -Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -L/Users/user/repositories/kivy-ios/dist/hostlibffi/usr/local/lib -lsqlite3 -lffi -L/Users/user/repositories/kivy-ios/dist/hostlibffi/usr/local/lib   -Wl,-stack_size,1000000  -framework CoreFoundation -o Programs/_testembed Programs/_testembed.o libpython3.8.a -ldl   -framework CoreFoundation -lz
>                          
> [DEBUG   ] ld: library not found for -lz
> [DEBUG   ] ld: library not found for -lz
> [DEBUG   ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
> [DEBUG   ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
> [DEBUG   ] make: *** [Programs/_testembed] Error 1
> [DEBUG   ] make: *** Waiting for unfinished jobs....
> [DEBUG   ] make: *** [python.exe] Error 1
> Traceback (most recent call last):
>   File "toolchain.py", line 1553, in <module>
>     ToolchainCL()
>   File "toolchain.py", line 1275, in __init__
>     getattr(self, args.command)()
>   File "toolchain.py", line 1316, in build
>     build_recipes(args.recipe, ctx)
>   File "toolchain.py", line 1153, in build_recipes
>     recipe.execute()
>   File "/Users/user/repositories/kivy-ios/toolchain.py", line 736, in execute
>     self.build_all()
>   File "/Users/user/repositories/kivy-ios/toolchain.py", line 85, in _cache_execution
>     f(self, *args, **kwargs)
>   File "/Users/user/repositories/kivy-ios/toolchain.py", line 831, in build_all
>     self.build(arch)
>   File "/Users/user/repositories/kivy-ios/toolchain.py", line 85, in _cache_execution
>     f(self, *args, **kwargs)
>   File "/Users/user/repositories/kivy-ios/toolchain.py", line 818, in build
>     self.build_arch(arch)
>   File "/Users/user/repositories/kivy-ios/toolchain.py", line 868, in build_arch
>     getattr(self, build)()
>   File "/Users/user/repositories/kivy-ios/recipes/hostpython3/__init__.py", line 63, in build_x86_64
>     _env=build_env)
>   File "/Users/user/repositories/kivy-ios/toolchain.py", line 67, in shprint
>     for line in cmd:
>   File "tools/external/sh.py", line 565, in next
>     self.wait()
>   File "tools/external/sh.py", line 500, in wait
>     self.handle_command_exit_code(exit_code)
>   File "tools/external/sh.py", line 516, in handle_command_exit_code
>     raise exc(self.ran, self.process.stdout, self.process.stderr)
> sh.ErrorReturnCode_2: 
> 
>   RAN: '/usr/bin/make -C /Users/user/repositories/kivy-ios/build/hostpython3/x86_64/Python-3.8.2 -j4'
> 
>   STDOUT:
> clang -Qunused-arguments -fcolor-diagnostics -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -arch x86_64 -mmacosx-version-min=10.12 -I/Users/user/repositories/kivy-ios/dist/hostlibffi/usr/local/include --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -arch x86_64 -mmacosx-version-min=10.12 -I/Users/user/repositories/kivy-ios/dist/hostlibffi/usr/local/include  -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-funct... (134785 more, please see e.stdout)
> 
>   STDERR:
>

**Comment by misl6** [comment]
You followed all the requirements section (https://github.com/kivy/kivy-ios#requirements) instructions?

**Comment by hoba87** [comment]
Yes, I've followed the instructions, and I am able to compile and open a non-python/kivy app in the simulator and iPhone. 
zlib is present in following directories:
/usr/lib/libz.dylib
/usr/local/Cellar/zlib/1.2.11/lib/libz.dylib
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libz.dylib

**Comment by hoba87** [comment]
executing
LDFLAGS=-L/usr/local/Cellar/zlib/1.2.11/lib/ /usr/bin/make -C /Users/holgerfranzi/Desktop/Holger/repositories/kivy-ios/build/hostpython3/x86_64/Python-3.8.2 -j4

gives me 

> clang -Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -L/Users/holgerfranzi/Desktop/Holger/repositories/kivy-ios/dist/hostlibffi/usr/local/lib -L/usr/local/Cellar/zlib/1.2.11/lib/   -Wl,-stack_size,1000000  -framework CoreFoundation -o python.exe Programs/python.o libpython3.8                         Foundation -lz
> clang -Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -L/Users/holgerfranzi/Desktop/Holger/repositories/kivy-ios/dist/hostlibffi/usr/local/lib -L/usr/local/Cellar/zlib/1.2.11/lib/   -Wl,-stack_size,1000000  -framework CoreFoundation -o Programs/_testembed Programs/_testembed.o                         ramework CoreFoundation -lz
> ld: library not found for -lz
> ld: library not found for -lz
> clangclang: : errorerror: : linker command failed with exit code 1 (use -v to see invocation)linker command failed with exit code 1 (use -v to see invocation)
>

**Comment by hoba87** [comment]
It gets more strange: Executing both clang commands manually in the build/hostpython/x86_64/Python-3.8.2 directory works (without any additional LDFLAGS) and running make again then finishes successfully. 

However executing python3 toolchain.py build kivy then tries again to compile hostpython3 because the build status is not set to built, so that does not help me.

**Comment by hoba87** [comment]
it seems, that not using a virtual env was the problem...
