### ISSUE TITLE
Kivy 2.0 not installing certifi for requests

### ISSUE THREAD

**Issue by JohnPapps** [kivy/kivy-ios#458]
Using the latest version of kivy-ios, `8416d46fd4f70da155f62640443c30cf71a0e52f` which is using Kivy 2.0 and Python 3.8, UrlRequest does not work as `certifi` is not installed
```
lib/python3.8/site-packages/kivy/network/urlrequest.py", line 220, in __init__
     import certifi
 ModuleNotFoundError: No module named 'certifi'
```
This is showing in the Xcode console output when running my app in the simulator at the point when I try to use UrlRequest.

**Comment by JohnPapps** [comment]
Environment: macOS Mojave
Python 3.8.2 inside conda environment
Followed instructions in readme to create Xcode project
No obvious errors.
Open the project, then run in Simulator
App works until it makes a network request using UrlRequest when it crashes with the tail of the stacktrace shown above.
Nothing special in the request:
```self.req = UrlRequest(url, on_success=success, on_error=error)```

**Comment by JohnPapps** [comment]
Workaround, (big thanks to @inclement) is to install certifi manually:
```$ python3 toolchain.py pip install certifi```

**Comment by misl6** [comment]
That should be fixed via https://github.com/kivy/kivy-ios/pull/455

**Comment by Zen-CODE** [comment]
This issue should now be resolved with recent changes. Please update your checkout to the latest version and re-open if the issue persists.

Thanks
