### ISSUE TITLE
How to get kivy working with the python 3.8 toolchain installation?

### ISSUE THREAD

**Issue by JoepR2001** [kivy/kivy-ios#504]
I finally managed to get kivy-ios working and running in xcode. But when i try to install kivy it doesn't work with the python 3.8 setup. I used the line 

'sudo ./toolchain.py pip3 install kivy'

**Comment by AndreMiras** [comment]
Hi @JoepR2001 
Support questions should go on Discord, not in the bug tracker. Also there're a couple of things you could improve to get better support:

-  "it doesn't work" doesn't really say anything for developers so people would have hard time helping providing only that
- don't sudo anything from Python ever
- don't clone kivy-ios but use `pip install kivy-ios` as described in the README of the project (not the current online kivy docs)
