### ISSUE TITLE
Hardcoded site-packages Python version references

### ISSUE THREAD

**Issue by AndreMiras** [kivy/kivy-ios#512]
**Versions**

* Python : N/A
* MacOS version : N/A
* XCode Version : N/A
* Cython version : N/A

**Describe the bug**
Recipes often have hardcoded references to Python versions, for instance:

- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/netifaces/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/distribute/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/pycrypto/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/jinja2/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/host_setuptools/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/markupsafe/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/itsdangerous/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/werkzeug/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/pillow/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/zbarlight/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/pyyaml/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/click/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/pil/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/kivent_core/__init__.py
- https://github.com/kivy/kivy-ios/blob/1.1.2/kivy_ios/recipes/flask/__init__.py

This is a problem because some recipes may then not work with Python 3.7 or 3.8 while it should work with both.

**To Reproduce**
```sh
grep -r 'python3.[78]' kivy_ios/recipes/
```

**Expected behavior**
Instead we would like these to dynamically use the target Python version.

**Comment by Zen-CODE** [comment]
@AndreMiras Do you have a suggested approach to solving this? Perhaps a first step would be to import a version number as a constant from a central py file? Seems cleaner than an env variable....

**Comment by AndreMiras** [comment]
I imagine it could be retrieved dynamically from the compiled host python version.
So we could have maybe an helper function that would return that path dynamically and use it in all the places. I think that could be a good start.
Also I'm suspecting setting the `PYTHONPATH` may not actually be needed for most of the recipes, this should be fairly easy to find out.

**Comment by misl6** [comment]
PR #601 inadvertently fixes this issue.

Keeping it open until We merge it.

**Comment by AndreMiras** [comment]
Merged, thanks for the heads up
