### ISSUE TITLE
issue with switching between the textinputs

### ISSUE THREAD

**Issue by nskrypnik** [kivy/kivy-ios#52]
If you have e.g. two textinputs and choose one for typing something and the just touch the second one to type text there the second device looses the focus then. It seems like the race condition, cause first textinputs gets the focus for half of second or less and then loses it for some reasons.
##

**Comment by Zen-CODE** [comment]
Thanks all. Major reworks of the FocusBehavior would almost certainly have fixed this. A quick test in 1.9.1 seems to confirm this is fixed. Please create a new ticket if you find otherwise.
