### ISSUE TITLE
Predictive keyboard dont work on kivy ios

### ISSUE THREAD

**Issue by RustyRyan98** [kivy/kivy-ios#528]
i just deployed an app and i realised when typing on a text input the keyboard doesnt predict the next text and i was wondering if this was bug ?

**Comment by Zen-CODE** [comment]
For question on kivy on kivy-ios, please post or ask on the kivy forums or discord channel:

    https://groups.google.com/forum/#!forum/kivy-users

If you find a demonstrable and clear bug, clear post here with code to reproduce the issue. Predictive text is not explicitly supported, so you might need to dig a little more to see how easy that might be to add.

Thanks
