### ISSUE TITLE
Assertion failed when building XCode project

### ISSUE THREAD

**Issue by liu00222** [kivy/kivy-ios#535]
**Versions**

* Python : 3.8
* MacOS version : 10.15.5 Catalina
* XCode Version : 11.6
* Cython version : 0.29.17

**Describe the bug**

The python code runs well when I directly use command "python3 main.py". However, when I converted it to an XCode project and tried to run, some bugs occurred. You can check the log in the later 'Logs' section. 

The version of numpy I used to write my python3 code is 1.19.0. 

I really have no idea about why this keeps happening and how I can solve it. 

**To Reproduce**

The command I used to generate the XCode project: 

```
python3 -m venv venv
pip3 install kivy-ios
xcode-select --install
brew install autoconf automake libtool pkg-config
brew link libtool

toolchain build python3 numpy kivy
toolchain pip3 install https://github.com/nskrypnik/kivy3/zipball/master

toolchain create someapp ~/Desktop/work/CRAI/dev
```

Then, I changed the permission of the folder "someapp-ios" to "read & write" for anyone and applied to all the files in the folder. Next: 

```
open someapp-ios/someapp.xcodeproj
```

Then, I ran the XCode project and got the issue mentioned in the previous section. 

**Expected behavior**

I would expect the program to run successfully in the XCode simulator. 

**Logs**

```
2020-07-26 20:56:30.162287-0500 someapp[44344:10217148] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2020-07-26 20:56:30.162458-0500 someapp[44344:10217148] Initializing python
2020-07-26 20:56:30.307292-0500 someapp[44344:10217148] Running main.py: /Users/admin/Library/Developer/CoreSimulator/Devices/CB9537FB-AF9F-4989-8F79-F4CEDA6C3E31/data/Containers/Bundle/Application/73C5D7BD-0840-41EE-BDA8-900CEC5CEBF2/someapp.app/YourApp/main.pyc
[INFO   ] [Kivy        ] v2.0.0rc1, git-Unknown, 20200726
[INFO   ] [Kivy        ] Installed at "/Users/admin/Library/Developer/CoreSimulator/Devices/CB9537FB-AF9F-4989-8F79-F4CEDA6C3E31/data/Containers/Bundle/Application/73C5D7BD-0840-41EE-BDA8-900CEC5CEBF2/someapp.app/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.2 (default, Jul 26 2020, 15:12:31) 
[Clang 11.0.3 (clang-1103.0.32.62)]
[INFO   ] [Python      ] Interpreter at "/Users/admin/Library/Developer/CoreSimulator/Devices/CB9537FB-AF9F-4989-8F79-F4CEDA6C3E31/data/Containers/Bundle/Application/73C5D7BD-0840-41EE-BDA8-900CEC5CEBF2/someapp.app/someapp"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 APPLE-17.10.22'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple Software Renderer'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 /Users/admin/Library/Developer/CoreSimulator/Devices/CB9537FB-AF9F-4989-8F79-F4CEDA6C3E31/data/Containers/Bundle/Application/73C5D7BD-0840-41EE-BDA8-900CEC5CEBF2/someapp.app/lib/python3.8/site-packages/numpy/ma/core.py:4466: SyntaxWarning: "is" with a literal. Did you mean "=="?
   if self.shape is ():
Assertion failed: (PyBytes_Check(__pyx_v_name)), function __pyx_pf_4kivy_8graphics_6vertex_12VertexFormat_4__init__, file kivy/graphics/vertex.c, line 3047.
(lldb) 
```

**Screenshots**

![Screen Shot 2020-07-27 at 1 25 42 PM](https://user-images.githubusercontent.com/42081599/88577496-b995ab00-d00c-11ea-9936-a1fa5b029c89.png)

**Additional context**
None

**Comment by Zen-CODE** [comment]
I suspect this is a kivy3D issue, which is not officially supported on iOS. Please try a simply app without Kivy3d just using numpy?

**Comment by liu00222** [comment]
Thanks for your reply! I tried the [Rotating Monkey Hear](https://kivy.org/doc/stable/examples/gen__3Drendering__main__py.html) example and it ran perfectly on iOS. Is it possible to make some 3D objects on my own (without using kivy3D) and make them work on iOS? I just need some simple ones like spheres and cubes, and the change of positions of the view camera.

**Comment by Zen-CODE** [comment]
Great. Yes, you can use the Monkey head example to see how to import 3D obj models. And use Blender to create those obj files.

Then I am going to close this ticket? Perhaps raise a ticket on the Kivy3D site asking if there are plans to update it (it's looks like it's a cython version issue), or submit a PR to fix it if you're feeling brave? :-)

Thanks

**Comment by liu00222** [comment]
It works now. Thanks for your reply!
