### ISSUE TITLE
simulator does not show texture

### ISSUE THREAD

**Issue by kgeoffrey** [kivy/kivy-ios#536]
Hi I'm trying to display a wrapped texture in Xcode simulator. The same code works well on MacOS and Windows, but in Xcode Simulator I can only see a black square the size of the texture.
I get the following log from Simulator:

Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): no suitable image found.  Did find:
	/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation: mach-o, but not built for iOS simulator
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found

Thanks

**Comment by Zen-CODE** [comment]
That's to do with the application image, not the image you see on screen. Please post the complete log or sample code to reproduce the issue.

**Comment by Zen-CODE** [comment]
Closing this issue as it appears to be inaccurate. 

@kgeoffrey Please feel free to re-open if you have logs demonstrating the issue. Thanks.
