### ISSUE TITLE
ModuleNotFoundError: No module named 'sh'

### ISSUE THREAD

**Issue by Python3-8** [kivy/kivy-ios#538]
I got an iMac and upgraded it to High Sierra so that I could package my Kivy game for iOS. I `git clone`d the `kivy-ios` repo and ran `pip install -r requirements.txt`. Then I ran `python3 toolchain.py build kivy`. I get the following error: `ModuleNotFoundError: No module named 'sh'`. I did install the requirements and I remember seeing `sh==1.12.14` in the `requirements.txt` file. Can someone please tell me what's wrong?

**Comment by moridinamael** [comment]
Might need to use pip3 instead of pip, depending on your environment.

**Comment by Python3-8** [comment]
I actually fixed it by recloning the repo. Now I'm trying to build my app on an iPhone. I just forgot to close this issue.
