### ISSUE TITLE
Virtual keyboard comes up immediately app starts

### ISSUE THREAD

**Issue by RustyRyan98** [kivy/kivy-ios#542]
Virtual keyboard comes up immediately app starts, tried various methods to fix this

**Comment by RustyRyan98** [comment]
The IOS Virtual keyboard comes up immediately apps starts. ive tried various methods to fix this

**Comment by tshirtman** [comment]
does it happen in a minimal app (a simple label?) if not, please provide a minimal example showing the issue.

**Comment by RustyRyan98** [comment]
No i tried a minimal app and it doesnt happen

**Comment by tshirtman** [comment]
it's probably an issue in your code, try to provide i minimal application showing the issue, usually people understand where they mistake is when they do that.

**Comment by RustyRyan98** [comment]
The App is about 10,000 lines of code, so i really dont know where to start to debug. What do you think are the possible causes ?

**Comment by tshirtman** [comment]
Maybe a TextInput that has the focus by default, or maybe you use request_keyboard improperly to bind to key events.

Just make a copy of your program, and start removing everything you can until the bug disappear, then add back what you just removed to confirm it's the cause, if you still don't understand, continue removing other things until you can't remove anything else without making the issue disappear.

**Comment by RustyRyan98** [comment]
Thank you bro, would do that
