### ISSUE TITLE
Images don't display correctly

### ISSUE THREAD

**Issue by Python3-8** [kivy/kivy-ios#543]
So I'm making this game and it works really well on Android:
![Android](https://user-images.githubusercontent.com/66139317/89742645-2bd0ab80-da61-11ea-9efc-38d3d206d704.png)

But if I install it to an iPhone using Xcode, I get this:
![iOS](https://user-images.githubusercontent.com/66139317/89742718-f8425100-da61-11ea-893f-287e8e185e9c.png)

Most of the viruses are pure white and I can barely see the buttons on the screen. Even the background is white. Any help is appreciated. Thanks in advance!

**Comment by tshirtman** [comment]
please share a code example showing the issue, as small as possible, a number of people have built kivy apps on ios and didn't report that, so it's probably something you do, and it won't be easy to guess what it would be otherwise.

**Comment by Python3-8** [comment]
Do you mean I should share my code? I'll leave a link to it if you want.

**Comment by Python3-8** [comment]
Okay, I'm getting the code ready. I'll post the link once I'm done.

**Comment by tshirtman** [comment]
ideally it should be as small as possible, if you can just try to display an image in a way that doesn't work (but works on android), that would be nice.

**Comment by Python3-8** [comment]
Oh no, I just finished creating a ZIP of my whole code. I'm sorry. But here's the file: [gameissue.zip](https://pyzard.herokuapp.com/Other/gameissue.zip).

**Comment by Python3-8** [comment]
Should I remove the file and upload just the part where I add the virus widgets?

**Comment by tshirtman** [comment]
code is not that big, i wonder if it's just a matter of the number of images (and their size), you are trying to display at the same time, maybe try reduce the bigger textures and to display less virus at the same time.

**Comment by tshirtman** [comment]
not sure if it's a bug in kivy or ios being more strict on usage.

**Comment by Python3-8** [comment]
Oh, thanks. So I just removed `gameissue.zip` from my website and now I was about to upload just the part that you asked for. And is there any way I can fix this?

**Comment by tshirtman** [comment]
i can't really know from there, i gave you directions to dig into, i don't think it's a kivy or kivy-ios bug, it looks like your management of images needs to be more optimized, feel free to come on discord to ask for help, it's better for user support.

**Comment by Python3-8** [comment]
Okay. So should I try compressing the files as much as I can?

**Comment by Python3-8** [comment]
It's fixed anyway. All I had to do was rebuild the app.
