### ISSUE TITLE
ModuleNotFoundError: no module name kivy

### ISSUE THREAD

**Issue by jschannaCV** [kivy/kivy-ios#544]
Hi,
When I try running the code below and use the instructions here to produce an ios app, I run into a ModuleNotFoundError: no module name kivy (line 1) and the app closes abruptly.

`from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.animation import Animation
from hoverable import HoverBehavior
from kivy.uix.image import Image
from kivy.uix.behaviors import ButtonBehavior
import json, glob
from datetime import datetime
from pathlib import Path
import random

Builder.load_file("design.kv")

class LoginScreen(Screen):
    def sign_up(self):
        self.manager.current = "sign_up_screen"
        self.manager.transition.direction = "up"
    def login(self, user, passw):
        with open("users.json") as file:
            users = json.load(file)
        if user in users and users[user]["password"]==passw:
            self.manager.transition.direction = "left"
            self.manager.current = "login_screen_success"
        else:
            self.ids.login_wrong.text = "Check again. Password or username wrong."

    def go_to_reset(self):
        self.manager.current = "forgot_password"
        self.manager.transition.direction = "down"

class RootWidget(ScreenManager):
    pass

class SignUpScreen(Screen):
    def add_user(self, uname, pword):
        with open("users.json") as file:
            users = json.load(file)
        users[uname] = {"username": uname, "password": pword, "created":
            datetime.now().strftime("%Y-%M-%D %H-%S-%M")}

        with open("users.json", "w") as file:
            json.dump(users, file)

        self.manager.current = "sign_up_screen_success"
        self.manager.transition.direction = "left"

    def back(self):
        self.manager.current = "login_screen"
        self.manager.transition.direction = "down"

class SignUpScreenSuccess(Screen):
    def go_to_login(self):
        self.manager.transition.direction = "left"
        self.manager.current = "login_screen"

class LoginScreenSuccess(Screen):
    def log_out(self):
        self.manager.transition.direction = "right"
        self.manager.current = "login_screen"

    def get_quote(self, feel):
        feel = feel.lower()
        available_feelings = glob.glob("quotes/*txt")
        available_feelings = [Path(filename).stem for filename in available_feelings]

        if feel in available_feelings:
            with open(f"quotes/{feel}.txt") as file:
                quotes = file.readlines()
            self.ids.quote.text = random.choice(quotes)
        else:
            self.ids.quote.text = "Try another emotion, hombre"

class ForgotPassword(Screen):
    def back(self):
        self.manager.current = "login_screen"
        self.manager.transition.direction = "up"
    def reset_password(self, uname1, pword2):
        with open("users.json")as file:
            users = json.load(file)
        users[uname1] = {"username": uname1, "password": pword2, "created":
            datetime.now().strftime("%Y-%M-%D %H-%S-%M")}
        with open("users.json", "w") as file:
            if users[uname1]["username"] == uname1:
                users[uname1]["password"].replace(pword2, pword2)
                json.dump(users, file)
                self.manager.transition.direction = "left"
                self.manager.current = "forgot_password_success"
            else:
                self.ids.no_user.text = "Username not found. Try again or sign up again."

class ForgotPasswordSuccess(Screen):
    def log_in_reset(self):
        self.manager.transition.direction = "left"
        self.manager.current = "login_screen"

class ImageButton(ButtonBehavior, HoverBehavior, Image):
    pass

class MainApp(App):
    def build(self):
        return RootWidget()

if __name__ == "__main__":
    MainApp().run()`

'<LoginScreen>:
    GridLayout:
        cols: 1
        GridLayout:
            cols: 1
            padding: 15, 15
            spacing: 20, 20
            Label:
                text: "User Login"
                font_size: "20sp"
            TextInput:
                id: username
                hint_text: "Username"
            TextInput:
                id: password
                password: True
                hint_text: "Password"
            RelativeLayout:
                Button:
                    text: "Login"
                    size_hint: 0.3, 0.5
                    on_press: root.login(root.ids.username.text, root.ids.password.text)
                    pos_hint: {"center_x": 0.5, "center_y": 0.6}
            Label:
                id: login_wrong
                text: ""
        GridLayout:
            cols: 2
            size_hint: 0.2, 0.2
            padding: 10, 10
            spacing: 10, 0
            Button:
                text: "Forgot password?"
                background_color: 1,1,1,0
                opacity: 1 if self.state == "normal" else 0.5
                color: 0.1, 0.7, 1, 1
                on_press: root.go_to_reset()
            Button:
                text: "Sign Up"
                background_color: 1,1,1,0
                opacity: 1 if self.state == "normal" else 0.5
                color: 0.1, 0.7, 1, 1
                on_press: root.sign_up()

<SignUpScreen>:
    GridLayout:
        cols: 1
        GridLayout:
            cols: 1
            padding: 15, 15
            spacing: 20, 20
            Label:
                text: "Sign up"
                font_size: "20sp"
            TextInput:
                id: username
                hint_text:"Username"
            TextInput:
                id: password
                hint_text: "Password"
        GridLayout:
            cols: 2
            size_hint: 0.2, 0.2
            padding: 10, 10
            spacing: 10, 0
            Button:
                text: "Back"
                on_press: root.back()
                background_color: 1,1,1,0
                opacity: 1 if self.state == "normal" else 0.5
                color: 0.1, 0.7, 1, 1
            Button:
                text: "Submit"
                on_press: root.add_user(root.ids.username.text, root.ids.password.text)
                background_color: 1,1,1,0
                opacity: 1 if self.state == "normal" else 0.5
                color: 0.1, 0.7, 1, 1

<SignUpScreenSuccess>:
    GridLayout:
        cols: 1
        Label:
            text: "Sign Up Successful!"
            font_size: "20sp"
        Button:
            text: "Login Page"
            on_press: root.go_to_login()
            background_color: 1,1,1,0
            opacity: 1 if self.state == "normal" else 0.5
            color: 0.1, 0.7, 1, 1
            pos_hint: {"center_x": 0.5, "center_y": 0}

<LoginScreenSuccess>:
    GridLayout:
        cols: 1
        padding: 30, 30
        spacing: 30, 30
        RelativeLayout:
            ImageButton:
                on_press: root.log_out()
                source: "logout_hover.png" if self.hovered else "logout_nothover.png"
                size_hint: 0.35, 0.35
                pos_hint: {"center_x": 0.93, "center_y": 0.8}
        Label:
            text: "How do you feel?"
        TextInput:
            id: feeling
            hint_text: "Things to try: happy, sad, unloved"
        Button:
            text: "Consider this"
            on_press: root.get_quote(root.ids.feeling.text)
        ScrollView:
            Label:
                id: quote
                text: ""
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

<ForgotPassword>
    GridLayout:
        cols: 1
        GridLayout:
            cols: 1
            padding: 15, 15
            spacing: 20, 20
            Label:
                text: "Reset Password"
                font_size: "20sp"
            TextInput:
                id: username
                hint_text: "Enter username"
            TextInput:
                id: password
                password: True
                hint_text: "Enter new password"
            Label:
                id: no_username
                text: ""
        GridLayout:
            cols: 2
            size_hint: 0.2, 0.2
            padding: 10, 10
            spacing: 10, 0
            Button:
                text: "Back"
                background_color: 1,1,1,0
                opacity: 1 if self.state == "normal" else 0.5
                color: 0.1, 0.7, 1, 1
                on_press: root.back()
            Button:
                text: "Reset"
                background_color: 1,1,1,0
                opacity: 1 if self.state == "normal" else 0.5
                color: 0.1, 0.7, 1, 1
                on_press: root.reset_password(root.ids.username.text, root.ids.password.text)

<ForgotPasswordSuccess>
    GridLayout:
        cols: 1
        Label:
            text: "Sign Up Successful!"
            font_size: "20sp"
            size_hint: 0.2, 0.2
        Button:
            text: "Login Page"
            on_press: root.log_in_reset()
            size_hint: 0.2, 0.2

<RootWidget>:
    LoginScreen:
        name: "login_screen"
    SignUpScreen
        name: "sign_up_screen"
    SignUpScreenSuccess
        name: "sign_up_screen_success"
    LoginScreenSuccess:
        name: "login_screen_success"
    ForgotPassword
        name: "forgot_password"
    ForgotPasswordSuccess
        name: "forgot_password_success"'

I followed the instructions in this repo. Could someone please share what could be going wrong?

Many thanks,
Jaspal

**Comment by Python3-8** [comment]
Did you run `toolchain build kivy` before you created your Xcode project?

**Comment by Python3-8** [comment]
Or if you cloned the repo, did you run `python3 toolchain.py build kivy`?

**Comment by jschannaCV** [comment]
> Did you run `toolchain build kivy` before you created your Xcode project?

Yes

**Comment by jschannaCV** [comment]
> Or if you cloned the repo, did you run `python3 toolchain.py build kivy`?

I did not run this, I just ran the code that was recommended to me by the repo.

**Comment by Python3-8** [comment]
Can you please tell me **exactly** what you were doing? Because I've never had this problem before.

**Comment by Python3-8** [comment]
Kivy uses spaces instead of tabs, so you can try to replace the code with 4 spaces per indent.

**Comment by Python3-8** [comment]
> Hi,
> 
> Thank you very much for the help. I tried the method above and got through most of it without problems, but couldn't get past the issue below.
> 
> When I tried:
> `try: with open(filename, 'wb') as filename_: filename_.write(requests.get(url).content) except: ...`
> It did not work.
> 
> I got the following error:
> `filename_.write(requests.get(url).content) ^ TabError: inconsistent use of tabs and spaces in indentation`
> 
> Do you know what I might be doing wrong?
> 
> Many thanks,
> Jaspal

Kivy uses spaces instead of tabs, so you can try to replace the code with 4 spaces per indent. I'm glad to know that you're trying my method.

**Comment by Zen-CODE** [comment]
Hi. I am closing this issue as there is no demonstrable issue with kivy-ios. The errors above are clearly installation and coding errors. If you feel there is a valid issue, please open a new ticket with runnable code that demonstrates the issue.

Thanks

**Comment by Python3-8** [comment]
> @jschannaCV:
> In the python file, you have to get the indentation right. After replacing the code, the indentation in every line has to be exactly as before.
> 
> @Python3-8: Thanks a lot for your explanations, they cleared up a lot of confusion for me.
> **NEW EDIT:**
> After some playing around, I still haven't got it to work and I've observed some very strange behavior:
> If I make the edits suggested by you and run `./toolchain.py build kivy`, the process errors out with the message
> 
> ```
> requests.exceptions.InvalidSchema: No connection adapters were found for 'ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz'
> ```
> 
> In fact, according to [this answer](https://stackoverflow.com/questions/11768214/python-download-a-file-from-an-ftp-server), the requests-package doesn't support ftp-links. How did you get this to work?
> 
> Moreover, when I then try to run `./toolchain.py build kivy` again, I get a different error, saying that somewhere the `os.path.join` method was getting a wrong argument:
> 
> ```
> TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
> ```
> 
> This error won't go away anymore unless I completely start over and clone the repo again.

So first you run `./toolchain.py build kivy` *without* editing the file. Then you edit the file and run the command again. These errors occurred for me too when I was doing this wrong.
