### ISSUE TITLE
can't see icon when launching app on Xcode simulator

### ISSUE THREAD

**Issue by faybak** [kivy/kivy-ios#546]
**Versions**

* Python :3.8
* MacOS version :10.15.3
* XCode Version :11.6
* Cython version :

**Describe the bug**
I tried to update icon with the python file "update_icon.py" and I looked for light icons from material design webfonticon. but don't work because of dependency of some icon which don't exist on light icon. So I reput the icon as before. But when I want to see how the app work on iOS simulator its not show any icon. But on pycharm when I load the app I can see all icon. And its not saying any error so I can't know where is the problem 

**To Reproduce**
// REPLACE ME: Add your `toolchain.py ....` command or a complete explanation of what you did so We can reproduce your error.

**Expected behavior**
// REPLACE ME: A clear and concise description of what you expected to happen.

**Logs**
```
// REPLACE ME: Paste the build output containing the error
```

**Screenshots**

**Additional context**

**Comment by Zen-CODE** [comment]
XCode requires you to set the application icon using it's toolset. This is something Kivy cannot do or change as it's a deliberate decision by Apple. To change the icon, please read here:

    https://stackoverflow.com/questions/28170520/ios-how-to-set-app-icon-and-launch-images
