### ISSUE TITLE
Xcode error "ld: library not found for -lkivy clang: error: linker command failed with exit code 1 (use -v to see invocation)"

### ISSUE THREAD

**Issue by RustyRyan98** [kivy/kivy-ios#547]
Python : 3.7
MacOS version: 10.15 Catalina
XCode Version : 11.6

Deployed a kivy app for ios, i renamed the project and added the logos via Xcode. When i suddenly try to build it i receive this error code which is quite strange as i have checked whether the library is in the link binaries section in xcode settings and i still receive the error. Here is the error code ```ld: library not found for -lkivy
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

Here is the full traceback 

```
Ld /Users/temitayoadefemi/Library/Developer/Xcode/DerivedData/Merri-ayovizwyxgrpxqeguibdmturpfax/Build/Products/Debug-iphonesimulator/merri.app/merri normal x86_64 (in target 'merri' from project 'merri')
    cd /Users/temitayoadefemi/Desktop/kivy-ios/merri-ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios8.1-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk -L/Users/temitayoadefemi/Library/Developer/Xcode/DerivedData/Merri-ayovizwyxgrpxqeguibdmturpfax/Build/Products/Debug-iphonesimulator -L/Users/temitayoadefemi/Desktop/kivy-ios/dist/lib -L/Users/temitayoadefemi/Desktop/kivy-ios/merri-ios/../dist/lib -F/Users/temitayoadefemi/Library/Developer/Xcode/DerivedData/Merri-ayovizwyxgrpxqeguibdmturpfax/Build/Products/Debug-iphonesimulator -F/Users/temitayoadefemi/Desktop/kivy-ios/dist/frameworks -filelist /Users/temitayoadefemi/Library/Developer/Xcode/DerivedData/Merri-ayovizwyxgrpxqeguibdmturpfax/Build/Intermediates.noindex/merri.build/Debug-iphonesimulator/merri.build/Objects-normal/x86_64/merri.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/temitayoadefemi/Library/Developer/Xcode/DerivedData/Merri-ayovizwyxgrpxqeguibdmturpfax/Build/Intermediates.noindex/merri.build/Debug-iphonesimulator/merri.build/Objects-normal/x86_64/merri_lto.o -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -all_load -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/temitayoadefemi/Library/Developer/Xcode/DerivedData/Merri-ayovizwyxgrpxqeguibdmturpfax/Build/Intermediates.noindex/merri.build/Debug-iphonesimulator/merri.build/merri.app-Simulated.xcent /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk/usr/lib/AppleConvergedTransport.tbd -framework MessageUI -framework ImageIO -framework Photos -framework CoreMedia -framework QuartzCore -framework Accelerate -framework CoreMotion -framework OpenGLES -framework CoreVideo -framework WebKit -framework MobileCoreServices -framework CoreGraphics -framework UIKit -framework AVFoundation -framework GameController -framework AudioToolbox -framework Metal -lz -lc++ -lbz2 -lsqlite3 -lios -weak-lkivy -lsdl2_ttf -lpyobjus -lcrypto -lpython3 -lffi -lsdl2_mixer -lssl -lsdl2 -lsdl2_image -lfreetype -Xlinker -dependency_info -Xlinker /Users/temitayoadefemi/Library/Developer/Xcode/DerivedData/Merri-ayovizwyxgrpxqeguibdmturpfax/Build/Intermediates.noindex/merri.build/Debug-iphonesimulator/merri.build/Objects-normal/x86_64/merri_dependency_info.dat -o /Users/temitayoadefemi/Library/Developer/Xcode/DerivedData/Merri-ayovizwyxgrpxqeguibdmturpfax/Build/Products/Debug-iphonesimulator/merri.app/merri

ld: library not found for -lkivy
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Ill appreciate if someone can help me with this

**Comment by Zen-CODE** [comment]
It's probably due to the renaming of the project. Try recreating it?

**Comment by RustyRyan98** [comment]
it keeps happening, ill reinstall kivy-ios and after some time it happens again

**Comment by Zen-CODE** [comment]
When exactly does this error occur? When you try and run the project in XCode or when you are building? We need more detail to help here.

1. Which method are you using? Are you cloning the repo,  or installing via `pip install  kivy-ios`?
2. Are you able to build everything without error? ie. what is the output of `python toolchain.py build kivy python3`?
3. Are you sure you are issuing the `python toolchain.py create <project> <path>` pointing to a valid folder that contains you `main.py` file?

**Comment by RustyRyan98** [comment]
it happens after about two days after the project has been built when i try to build it in xcode, now its showing me this error ```Library` not found for -lpython3````

**Comment by RustyRyan98** [comment]
I have to now to reclone kivy-ios and create the project again

**Comment by Zen-CODE** [comment]
It looks like you builds are being removed. By sure to clone the repo and have your project code and clone in separate paths, and one's in you user folder....

Good luck, and keep us posted....

**Comment by RustyRyan98** [comment]
Sorry can you explain that in detail, don't really understand

**Comment by Zen-CODE** [comment]
Just follow the instructions here: https://github.com/kivy/kivy-ios
And make sure that is in a separated folder to you app code. ie. you kivy-ios installation is not inside your code folder where your application code is. Clear enough?

**Comment by RustyRyan98** [comment]
Yeah that’s how I’ve always done it 
    	
    	

    	Get Outlook for iOS
    
  




On Wed, Sep 2, 2020 at 2:23 PM +0100, "Richard Larkin" <notifications@github.com> wrote:















Just follow the instructions here: https://github.com/kivy/kivy-ios

And make sure that is in a separated folder to you app code. ie. you kivy-ios installation is not inside your code folder where your application code is. Clear enough?

**Comment by Zen-CODE** [comment]
And so what error are you getting now? There is nothing that you have reported than does not seem like an installation problem? Please post full logs and steps if you still have problems.

**Comment by RustyRyan98** [comment]
Ill do it again and ill get back to you

**Comment by Julian-Code14** [comment]
Did you get a Solution?

**Comment by RustyRyan98** [comment]
Yeah I just did it again and it just happened to work. Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Zen-CODE** [comment]
Great stuff! Thanks @RustyRyan98
