### ISSUE TITLE
Problem while building kivy

### ISSUE THREAD

**Issue by Valenwe** [kivy/kivy-ios#549]
I followed all steps in the kivy tutorial [https://kivy.org/doc/stable/guide/packaging-ios.html](url)

But I can't do this line: "./toolchain.py build kivy". It first said that there was a syntax error in toolchain.py, then after adding "#!/usr/bin/python3" to it, it says "sh.CommandNotFound: xcrun". 

PS: I'm in Ubuntu

**Comment by Zen-CODE** [comment]
Please retry, posting the exact commands you entered and a full copy of the output.

**Comment by Zen-CODE** [comment]
Kivy-ios requires a Mac. Sorry, that's an Apple enforced requirement.
