### ISSUE TITLE
cannot build libjpeg and pil

### ISSUE THREAD

**Issue by dcorio** [kivy/kivy-ios#55]
I'm on OSX 10.8.4 with an up-to-date version of kivy-ios.
I noticed that the project has been updated to correctly compile PIL but the build script downloads and installs libjpeg6b that seems cannot be compiled on 10.8.4.

I'm the only one having this kind of problem?

Anyway, the real problem is with PIL.

It compiles correctly but when building the project with XCode, it says:

      __encode_to_file in libpil.a(_imaging.so.o)
      ld: symbol(s) not found for architecture armv7
      clang: error: linker command failed with exit code 1 (use -v to see invocation)

is this an issue or i made something wrong?

**Comment by tito** [comment]
PIL has been rewritten with the new toolchain, this should not be an issue anylmore.
