### ISSUE TITLE
The plyer project needs attention, filechooser for iOS isn’t working again

### ISSUE THREAD

**Issue by RustyRyan98** [kivy/kivy-ios#561]
I commented on the plyer project repository about the filechooser not working as before. It was working perfectly now it shows a pyobjus error, please I would appreciate if this can be looked into. It’s delaying a critical project for me. Thank you kivy team.

**Comment by tshirtman** [comment]
please don't duplicate issues, if it's a plyer issue, it should be in plyer issues, and remember you can help solving it by making a pull request on plyer, as you are the one impacted by it, you might be the best person to solve it.
