### ISSUE TITLE
Python3 does not build with toolchain build python3

### ISSUE THREAD

**Issue by StevenWilson9** [kivy/kivy-ios#583]
**Describe the bug**
Python3 does not build with `toolchain build python3`

I am following the steps here: [https://kivy.org/doc/stable/guide/packaging-ios.html](https://kivy.org/doc/stable/guide/packaging-ios.html) However when running `toolchain create pingpong ~/Documents/My_Python_Scripts/MyLiftingStats/PingPong/` I get the following error:
```
    [INFO    ] Include dir added: {arch.arch}/freetype
    [INFO    ] Include dir added: {arch.arch}/hostlibffi
    [INFO    ] Include dir added: {arch.arch}/ffi
    [INFO    ] Include dir added: {arch.arch}/openssl
    [INFO    ] Include dir added: common/sdl2
    [ERROR   ] No python recipe compiled!
    [ERROR   ] You must have compiled at least python3
    [ERROR   ] recipe to be able to create a project.
```
If I run: `toolchain status` it appears not built. `python3      - Not built`

If I run `toolchain build python3`it and search for 'warning:' it seems to point to 3 groups of warning messages. One of which is:
```
[DEBUG   ] configure: WARNING: libintl.h: present but cannot be compiled
[DEBUG   ] configure: WARNING: libintl.h:     check for missing prerequisite headers?
[DEBUG   ] configure: WARNING: libintl.h: see the Autoconf documentation
[DEBUG   ] configure: WARNING: libintl.h:     section "Present But Cannot Be Compiled"
[DEBUG   ] configure: WARNING: libintl.h: proceeding with the compiler's result
[DEBUG   ] configure: WARNING:     ## --------------------------------------- ##
[DEBUG   ] configure: WARNING:     ## Report this to https://bugs.python.org/ ##
[DEBUG   ] configure: WARNING:     ## --------------------------------------- ##
```

**Logs**
[https://gist.github.com/StevenWilson9/3c3a2efde37e17b2755b11c8c19a58d5](https://gist.github.com/StevenWilson9/3c3a2efde37e17b2755b11c8c19a58d5)

**Versions**
* Python : python3    3.8.2
* MacOS version : 11.1
* XCode Version : 12.3
* Cython version : 0.29.19

**Additional context**
When running` toolchain build python3 openssl kivy` and `toolchain status`, openssl and kivy do  not show up either.
I get the same result whether doing it in or outside of a virtual environment with `. venv/bin/activate`

**Comment by misl6** [comment]
Hi @StevenWilson9 , that issue that I see in logs was solved by PR https://github.com/kivy/kivy-ios/pull/581, We expect to ship these fixes into release `1.2.1`.

Meanwhile, you can use the latest master, and not the pypi version.

I'm closing it as resolved, but feel free to reopen or to join us on discord if needed.
