### ISSUE TITLE
Videoplayer build error with GStream

### ISSUE THREAD

**Issue by 1l0** [kivy/kivy-ios#60]
My workflow and the unsolved error.

Create Xcode project with videoplayer.py renamed into main.py.
> kivy/examples/widgets/videoplayer.py -> main.py

On Xcode, add GStreamer framework.
> GStreamer.framework

Then, build error occurs, so add following more.
>AssetsLibrary.framework
>CoreVideo.framework
>CoreMedia.framework
>AVFoundation.framework
>libiconv.dylib
>libresolv.9.dylib

And, rename main extension to .mm
>main.m -> main.mm

finally! ...error remains. Many duplicate symbols that conflicted between Kivy and Gstreamer.

One of those is like this.
```duplicate symbol _ps_table_funcs in:
    /Users/admin/Library/Developer/GStreamer/iPhone.sdk/GStreamer.framework/GStreamer(libfreetype_a_armv7_-psaux.o)
    /Users/admin/kivy-ios/build/lib/libfreetype.a(psaux.o)```
    
End lines of the log here.
```507 dublicate symbols for architecture armv7
Linker command failed with exit code 1```

**Comment by tito** [comment]
We have a ffmpeg video player now, using ffpyplayer :)
