### ISSUE TITLE
toolchain problem

### ISSUE THREAD

**Issue by EricPolizzy** [kivy/kivy-ios#615]
I have been trying to compile and follow the given instruction of Kivy-ios on my OS BigSur (V.11.3) using the folliwng  code: 

sudo python toolchain.py python3 openssl kivy

However, I constantly receive the following error. 

```

Traceback (most recent call last):

  File "toolchain.py", line 1, in <module>

    from kivy_ios.toolchain import main

  File "/Users/CDF5/Desktop/App/kivy-ios/kivy_ios/toolchain.py", line 1350

    logger.info(f"Adding {custom_recipe_path} to custom recipes paths")


```

I'd be great if you could let me where the problem is.

**Comment by misl6** [comment]
Considering that is failing on a f-string, I suppose that you're using python3 < 3.6, is that right?

**Comment by EricPolizzy** [comment]
Thanks for your response @misl6 . I'm using python 3.9 actually

**Comment by misl6** [comment]
Ok, looks good. Can you please try to add the whole build log?

**Comment by EricPolizzy** [comment]
d-172-25-143-111:kivy-ios CDF5$ ls

CHANGELOG.md		README.md		requirements.txt	tests			tox.ini

LICENSE			kivy_ios		setup.py		toolchain.py

d-172-25-143-111:kivy-ios CDF5$ sudo python toolchain.py python3 openssl kivy

Password:

Traceback (most recent call last):

  File "toolchain.py", line 1, in <module>

    from kivy_ios.toolchain import main

  File "/Users/CDF5/Desktop/App/kivy-ios/kivy_ios/toolchain.py", line 1350

    logger.info(f"Adding {custom_recipe_path} to custom recipes paths")
                                                                                                               ^
SyntaxError: invalid syntax

**Comment by EricPolizzy** [comment]
> Ok, looks good. Can you please try to add the whole build log?



> ```
> d-172-25-143-111:kivy-ios CDF5$ ls
> CHANGELOG.md		README.md		requirements.txt	tests			tox.ini
> LICENSE			kivy_ios		setup.py		toolchain.py
> 
> d-172-25-143-111:kivy-ios CDF5$ sudo python toolchain.py python3 openssl kivy
> Password:
> Traceback (most recent call last):
>   File "toolchain.py", line 1, in <module>
>     from kivy_ios.toolchain import main
>   File "/Users/CDF5/Desktop/App/kivy-ios/kivy_ios/toolchain.py", line 1350
>     logger.info(f"Adding {custom_recipe_path} to custom recipes paths")
>                                                                                                                ^
> SyntaxError: invalid syntax
> ```

**Comment by EricPolizzy** [comment]
> Ok, looks good. Can you please try to add the whole build log?

```
d-172-25-143-111:kivy-ios CDF5$ ls
CHANGELOG.md		README.md		requirements.txt	tests			tox.ini
LICENSE			kivy_ios		setup.py		toolchain.py

d-172-25-143-111:kivy-ios CDF5$ sudo python toolchain.py python3 openssl kivy
Password:
Traceback (most recent call last):
  File "toolchain.py", line 1, in <module>
    from kivy_ios.toolchain import main
  File "/Users/CDF5/Desktop/App/kivy-ios/kivy_ios/toolchain.py", line 1350
    logger.info(f"Adding {custom_recipe_path} to custom recipes paths")
                                                                                                               ^
SyntaxError: invalid syntax

```

**Comment by EricPolizzy** [comment]
@misl6 please let me know if you need any further details to be provided. Thanks!

**Comment by PrabhuTeja89** [comment]
I too received the same error below(OS BigSur (V.11.4). Python version 3.7.9. Appreciate your help on this. 

MacBook-Air kivy-ios % ls
CHANGELOG.md		README.md		requirements.txt	tests			toolchain.pyc
LICENSE			kivy_ios		setup.py		toolchain.py		tox.ini

MacBook-Air kivy-ios % sudo python ./toolchain.py build python3 kivy
Traceback (most recent call last):
  File "./toolchain.py", line 1, in <module>
    from kivy_ios.toolchain import main
  File "/Users/Prabhu/python_git/kivy-ios/kivy_ios/toolchain.py", line 1350
    logger.info(f"Adding {custom_recipe_path} to custom recipes paths")
                                                                     ^
SyntaxError: invalid syntax

**Comment by AndreMiras** [comment]
Yeah mostlike your Python version doesn't support f-string.
Make sure you're up to date.
Also I see you use `sudo python`, this is discouraged.
Last is you seem to use the old way of running the toolchain, also not recommended.
See how it's being installed & used in the README for instance

**Comment by misl6** [comment]
I'm closing this issue cause as stated by @AndreMiras it should be related to an unsupported Python version.
Feel free to reopen if the issue persists.
