### ISSUE TITLE
Permission denied while opening app-dir

### ISSUE THREAD

**Issue by Moazzam125** [kivy/kivy-ios#636]
**Versions**

* Python : 3.9.6
* MacOS version : 10.14.6
  * Virtualization: vSphere 6.5
* XCode Version : 11.3.1
* Cython version : 0.29.17

**Description**
In accordance to README.md on kivy-ios 1.2.1
I started, 
1. xcode 11.3.1 from Apple developer site
2. installed xcode command line tools
3. installed homebrew
4. brew installed autoconfig automake ....
5. install kivy-ios, cython from pip
6. toolchain builds kivy (& dependencies) on ~/Documents/testapp BY `$ toolchain build kivy --arch=x86_64`
7. created xcode proj on ~/Documents/testapp | app src-dir; ~/Documents/testapp-kivy
8. xcode builds succeed, failed on running app on simulator(iOS 13.3).

**Expected behavior**
As xcode builds, it should run on simulator (x86_64) only

**Screenshots**
![Screenshot from 2021-08-29 12-18-55](https://user-images.githubusercontent.com/62427787/131242596-f5b35431-0ad3-42c5-ae88-029882d530d1.png)
![Screenshot from 2021-08-29 12-19-37](https://user-images.githubusercontent.com/62427787/131242598-47ffa08c-5877-4381-952e-85e371a89e7b.png)

**Comment by misl6** [comment]
As discussed with the user on Discord, is unlikely a `kivy-ios` issue.
Apart upgrading the quite old environment (MacOS version, Xcode version), I suggested to check if he used `sudo` during build time, and to avoid it.

I'm closing the issue, but @Moazzam125 feel free to ask for additional support on Discord.
