### ISSUE TITLE
leverage conda to create the host* packages 

### ISSUE THREAD

**Issue by cav71** [kivy/kivy-ios#655]
**Is your feature request related to a problem? Please describe.**
If I understand the toolchain.py  logic, quite few recipes are related to build host* packages (eg. hostpython, host_setuptools, hostlibffi, hostopenssl).
Leveraging conda, this allows to use the most updated ready-to-use host tools for a variety of platform, simplifying the process (and switching to full python3 along the way).

**Describe the solution you'd like**
This is a walk-through to have a host environment to build the cross compiled python toolchain:
1. install the conda root (from https://github.com/conda-forge/miniforge)
2. creates a new conda virtual environment
3. activate and use the new conda virtual environment
4. clean it up

**Install the conda root** (done only once):
```
curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh -o conda.sh
sh conda.sh -b -p $(pwd)/host
```
> There are packages for Windows and Linux

**Creates a new conda environment**
This is the same as `python -m venv host/envs/kivy` and it is done only once:
```
export PATH=$(pwd)/host/bin:$PATH
$(pwd)/host/bin/conda create -p $(pwd)/host/envs/kivy python
```
**Activate the new conda environment**
```
source $(pwd)/host/etc/profile.d/conda.sh
conda activate $(pwd)/host/envs/kivy
conda install autoconf automake cython m4 setuptools
```

**Completely clean it up**
```
rm -rf $(pwd)/host
```

**Comment by Julian-O** [comment]
There is no call to action here. Closing as not a feature request.

If you think this is in error, please let us know what the requested action is.
