### ISSUE TITLE
Build python3 with _bz2 compression module

### ISSUE THREAD

**Issue by CMengich** [kivy/kivy-ios#657]
Hello,

I am working on building a kivy-ios app that includes working with bzip files. Python3 built with the current recipe, does not include the _bz2 module.

The error below is raised, by the file in dist/root/python3/lib/python3.9/bz2.py when the xcode project is run.

`ModuleNotFoundError: No module named '_bz2'` 

How can I build python3 with bz2, or get passed this issue?
Thanks in advance for any help.

**Comment by misl6** [comment]
Is this happening on a real iOS device or on an iOS Simulator?

**Comment by CMengich** [comment]
only attempted on iOS Simulator so far..

**Comment by misl6** [comment]
Additional info:
The issue is confirmed also on a real iOS device.

**Comment by misl6** [comment]
@CMengich I've just posted PR #658 that should fix this issue. (I tested it on a real iOS device)
Can you give it a try?

**Comment by CMengich** [comment]
@misl6 Thanks for the help! I can confirm, that solved it.

**Comment by CMengich** [comment]
One other question, now finding the error below:

`No module named 'mmap'`

Which I understand is also a module in python. How would I go about adding it to the build?

**Comment by CMengich** [comment]
Hi @misl6 

The app also needs the mmapmodule, which is also not included in the python3 build. When I uncomment below, in the ModulesSetup:

`# mmap mmapmodule.c`

And build python3, the error below arises:

`[DEBUG   ] ./Modules/mmapmodule.c:548:18: error: implicit declaration of function 'mremap' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
[DEBUG   ]         newmap = mremap(self->data, self->size, new_size, 0);`

Is there a way to bypass this? Or run the build with implicit-function-declaration, set to warning for this particular module?
Thanks in advance for any help.

**Comment by misl6** [comment]
@CMengich I'm not sure that `mremap` function is available on macOS and iOS, so we probably need to dig into it a little deeper and patch what is needed.

Considering that is a separate issue, can you open a new one instead?
