### ISSUE TITLE
Kivy Xcode "Unable to open main.py"

### ISSUE THREAD

**Issue by NicFolk** [kivy/kivy-ios#661]
<img width="1435" alt="Screen Shot 2021-11-26 at 6 48 48 PM" src="https://user-images.githubusercontent.com/95112788/143665791-58ccd147-a5f6-45a4-8b7a-c3fdffc0b862.png">

I recently created a Kivy project, running it successfully in terminal. I then packaged it for iOS, following all the instructions on the Kivy website. I did not run into any errors there, but once I opened the Xcode project that I created through packaging, it would not run. The first error I got was a PhaseScriptExecution build error, which I fixed by adding "-O --no-perms" to the Build Phases -> Run Script section. Now, when I try building, the build succeeds but I get the error above and ultimately my app fails to open. Can someone help me figure out what is going on? Thanks in advance

**Comment by karimkhanvi** [comment]
Hi @NicFolk Can you reply how did you solve this problem ?
