### ISSUE TITLE
freetype recipe version 2.5.5 has been removed from remote repo

### ISSUE THREAD

**Issue by mabboud1994** [kivy/kivy-ios#662]
With the latest version of kivy-ios, the builder try to download the recipe 'freetype 2.5.5' which is no more presents in remote repo of freetype releases.

So when i try toolchain build freetype i got this message:
"value error: read of closed file"

i fixed this issue by manually editing the class FreeTypeRecipe and adding an existing version of freetype.

**Comment by misl6** [comment]
Hi @mabboud1994,
The issue has already been fixed on `master` branch. (See #632 ad #629)
