### ISSUE TITLE
Error Loading Image

### ISSUE THREAD

**Issue by NicFolk** [kivy/kivy-ios#664]
I recently created a Kivy app and after some difficulties, I managed to get in running (partially) in an Xcode simulator. The main issue I have is that I want to attach an image to my app, but when I run my app in the Xcode simulator, it returns "[ERROR ] [Image ] Error loading <Images/opening_image.webp>". Inside the "YourApp" folder in my project-ios, there is a folder labeled Images and an image inside that folder labeled "opening_image.webp", so I think the path is correct. Does anyone know how to fix this and do you need more information?
<img width="1437" alt="Screen Shot 2021-12-02 at 7 15 06 PM" src="https://user-images.githubusercontent.com/95112788/144538955-0b932193-db15-4af6-a9b1-8648d5da02cd.png">

**Comment by NicFolk** [comment]
OK, so I believe I have narrowed the issue down to [INFO ] [Image ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil ignored). Does anyone know how to get the code not to ignore these providers.

**Comment by misl6** [comment]
Hi @NicFolk,
Into your `main.m` file, you should have, around line `39` a `putenv("KIVY_IMAGE=imageio,tex,gif");`, here you can change your default options.

PS: Maybe you could be interested to: https://github.com/kivy/kivy-ios/pull/656

I'm closing this issue cause it looks like a support request, but feel free to re-open if needed.

**Comment by NicFolk** [comment]
Thank you, that fixed the issue
