### ISSUE TITLE
libzbar recipe missing libiconv dependency

### ISSUE THREAD

**Issue by RobertFlatt** [kivy/kivy-ios#676]
**Versions**

* Python : 3.9.9
* MacOS version : 11.6.3
* XCode Version : 13.2.1
* Cython version :0.29.28
* kivy-ios : master

**Describe the bug**
The "play" step in Xcode fails with a link error.

**To Reproduce**
```
toolchain distclean
toolchain build python3 kivy
toolchain build libzbar
toolchain create xxx yyy
open xxx-ios/xxx.xcodeproj
"press play"
```

**Expected behavior**

The failed link apperars due to an unknown missing assembler library. This should be included in the xcodeproj files, as is the case for other library dependencies.

**Logs**
```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _qr_code_data_list_extract_text in libzbar.a(libzbar_la-qrdectxt.o)
     (maybe you meant: _SDL_iconv_open, _SDL_iconv_close , _SDL_iconv_string , _SDL_iconv )
  "_iconv_close", referenced from:
      _qr_code_data_list_extract_text in libzbar.a(libzbar_la-qrdectxt.o)
     (maybe you meant: _SDL_iconv_close)
  "_iconv_open", referenced from:
      _qr_code_data_list_extract_text in libzbar.a(libzbar_la-qrdectxt.o)
     (maybe you meant: _SDL_iconv_open)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Additional context**
A Google search suggests "adding Accelerate"
Looking in the `project.pbxproj` file we see `Accelerate` exists in the same group as `libkivy.a` 
However the  "Accelerate" option does not appear to exist on Xcode 13 UI. 
Speculation : Perhaps the library name has changed?

**Comment by RobertFlatt** [comment]
Further investigation indicates a missing `libzbar` recipe dependency on `libiconv` which presumably accounts for the message `Undefined symbols for architecture x86_64:
  "_iconv"`

The dependency can be seen in the p4a recipe:
```
https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/libzbar/__init__.py#L15 
```
But not in the kivy-ios recipe:
```
https://github.com/kivy/kivy-ios/blob/master/kivy_ios/recipes/libzbar/__init__.py#L12
```

There is no kivy-ios `libiconv` recipe. So possibly the issue is a missing Xcode link flag?

**Comment by misl6** [comment]
Did you try to add `libiconv.tbd` from "Frameworks, Libraries and Embedded Content" in Xcode?

PS: if this fixes the issue, please don't close the issue, cause `kivy-ios` should add by itself the library when creating/updating the Xcode project.

**Comment by RobertFlatt** [comment]
Thank you, that linked.

**Comment by Neizvestnyj** [comment]
> 
It does not work for me 
![Screenshot 2022-03-26 at 00 34 17](https://user-images.githubusercontent.com/40869738/160203813-14d26c7f-5a44-4204-b64f-3e5fcd26bb0b.png)

**Comment by RobertFlatt** [comment]
I had to poke at xcode a few times to do what one press should have done :(

Also I saw this next https://github.com/kivy/kivy-ios/issues/681

**Comment by RobertFlatt** [comment]
The magic technique in Xcode is to search for `libiconv.tbd` , click on it to select it, then double click. It will then appear in the list. Do NOT click on `add` this does not work.
