### ISSUE TITLE
zbarlite recipe has hardcoded python version

### ISSUE THREAD

**Issue by RobertFlatt** [kivy/kivy-ios#677]
https://github.com/kivy/kivy-ios/blob/master/kivy_ios/recipes/zbarlight/__init__.py#L27

**Comment by Julian-O** [comment]
Is this still a problem? The link no longer points to a relevant line.

**Comment by RobertFlatt** [comment]
Looks like references to python3.7 were removed here https://github.com/kivy/kivy-ios/blob/v2023.08.24/kivy_ios/recipes/zbarlight/__init__.py

**Comment by Julian-O** [comment]
@RobertFlatt: I interpreted that as "bug fixed", so I am closing as complete.

If I misinterpreted, please let us know.
