### ISSUE TITLE
Error when running app: dyld: lazy symbol binding failed: Symbol not found

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/kivy-ios#68]
Running on MacOSX 10.8.5, kivy-ios checkout redone this morning, the application builds but fails on launching on the iPad with (iOS 6.1):
------------------
dyld: Symbol not found: ___sincos_stret
  Referenced from: /var/mobile/Applications/34A13332-C292-4087-A4A0-E8F83D40CECC/SpeedTest.app/SpeedTest
  Expected in: /usr/lib/libSystem.B.dylib
------------------

I have a strong feeling that this issue is related to the one Mathieu fixed this morning.

https://github.com/kivy/kivy-ios/commit/71a81a69243535575ebe83f51de1815eb01d4a8a

I would guess this as almost all of the searches I do on the error discuss versioning in Mac 10.* vs. 10.8 libraries.

http://www.ncl.ucar.edu/Support/talk_archives/2013/2677.html

https://groups.google.com/forum/#!topic/wx-users/HhFsyo8MS7k

http://bugs.mysql.com/bug.php?id=67133

My Python version is 2.7.2 which has a bug Mathieu found dubugging the above-mentioned issue.

http://bugs.python.org/issue9516

**Comment by tito** [comment]
The latest version might be ok for that, but it need someone with an old device. Will close it, if it happen again from a fresh build on the latest kivy-ios, please reopen.
