### ISSUE TITLE
App Store Connect Operation Error Invalid Bundle Structure - The binary file '*myapp*.app/lib/python3.9/site-packages/google/protobuf/pyext/_message.cpython-39-darwin.so' is not permitted.

### ISSUE THREAD

**Issue by faybak** [kivy/kivy-ios#702]
-->

**Versions**

* Python :3.9
* MacOS version :12.1
* XCode Version :13.1
* Cython version :

**Describe the bug**
 I wanted to distribute my app on apple store, I made the validation process and after that I have this two error

don't understand why because before I used the same python library to distribute another application.

what I did different to before is I try to use firebase push notification with pod but not work so a removed it 
I use firebase for my database so I install Pyrebase for the request. Like Pyrebase didn't install well i put the folder from GitHub directly on my source folder et install cloud after that to make it work well. but its not the problem because I already used this configuration on other application
**To Reproduce**
// REPLACE ME: Add your `toolchain.py ....` command or a complete explanation of what you did so We can reproduce your error.

**Expected behavior**
normaly it have to run validation without issue but don't understand why

**Logs**

 App Store Connect Operation Error
Invalid Bundle Structure - The binary file '$myapp$.app/lib/python3.9/site-packages/google/protobuf/pyext/_message.cpython-39-darwin.so' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure.

App Store Connect Operation Error
Invalid Bundle Structure - The binary file '$myapp$.app/lib/python3.9/site-packages/google/protobuf/internal/_api_implementation.cpython-39-darwin.so' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure.

**Comment by akshayaurora** [comment]
Seems like you are including protobuf in your app,  I guess you compile protobuf using a local recipe.

I suggest you just include the pure python generated files from protobuf instead of the whole protobuf.

**Comment by pythonsus** [comment]
use the protobuf recipe form https://github.com/kivy/python-for-android/tree/develop/pythonforandroid/recipes
