### ISSUE TITLE
build stop on libffi-3.2.1

### ISSUE THREAD

**Issue by weixingsun** [kivy/kivy-ios#703]
I got an issue when building ios binary, simply follow steps on the home page:
just saw the fix 695 has been patched , any help / comments will be appreciated !

**Versions**

* Python :
* MacOS version : 10.14.6
* XCode Version : 11.1
* Python Version : 3.10.4
* Cython version : 0.29.28

**To Reproduce**
$ toolchain build python3 kivy

**Logs**
```
[build.log](https://github.com/kivy/kivy-ios/files/8619124/build.log)

```

thanks

**Comment by misl6** [comment]
That seems a different issue than the one described in #694.

How did you installed `kivy-ios` ?
`macOS 10.14.6` and `XCode 11` are quite old, did you tried to build it on a newer macOS version?

**Comment by weixingsun** [comment]
with everything cleaned up, and the log shown the error of freetype , and here is the exactly same cmd as below:

cd /Users/aimeewang/app/bitrocket/.buildozer/android/platform/build-arm64-v8a/build/other_builds/freetype/arm64-v8a__ndk_target_21/freetype
aimeewang@AimeeAir freetype % /Users/aimeewang/app/bitrocket/.buildozer/android/platform/build-arm64-v8a/build/other_builds/freetype/arm64-v8a__ndk_target_21/freetype/configure --with-harfbuzz=no --with-png=no --prefix=/Users/aimeewang/app/bitrocket/.buildozer/android/platform/build-arm64-v8a/build/other_builds/freetype/arm64-v8a__ndk_target_21/freetype --enable-shared --without-bzip2 --disable-static --host=aarch64-linux-android --with-zlib=yes

FreeType build system -- automatic system detection

The following settings are used:

  platform                    unix
  compiler                    cc
  configuration directory     ./builds/unix
  configuration rules         ./builds/unix/unix.mk

If this does not correspond to your system or settings please remove the file
`config.mk' from this directory then read the INSTALL file for help.

Otherwise, simply type `/Applications/Xcode.app/Contents/Developer/usr/bin/make' again to build the library,
or `/Applications/Xcode.app/Contents/Developer/usr/bin/make refdoc' to build the API reference (this needs python >= 2.6).

cd builds/unix; \
	        ./configure  '--with-harfbuzz=no' '--with-png=no' '--prefix=/Users/aimeewang/app/bitrocket/.buildozer/android/platform/build-arm64-v8a/build/other_builds/freetype/arm64-v8a__ndk_target_21/freetype' '--enable-shared' '--without-bzip2' '--disable-static' '--host=aarch64-linux-android' '--with-zlib=yes'
checking build system type... x86_64-apple-darwin20.6.0
checking host system type... aarch64-unknown-linux-android
checking for aarch64-linux-android-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... unsupported
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/Users/aimeewang/app/bitrocket/.buildozer/android/platform/build-arm64-v8a/build/other_builds/freetype/arm64-v8a__ndk_target_21/freetype/builds/unix':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
make: *** [setup] Error 1
aimeewang@AimeeAir freetype %

**Comment by camachat** [comment]
I got the other error:
objc[43270]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1dd7b1eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10625c4f8). One of the two will be used. Which one is undefined.
