### ISSUE TITLE
App crashes on physical devices when using buttons.

### ISSUE THREAD

**Issue by momomomomos** [kivy/kivy-ios#706]
**Versions**

* Python : 3.10.2
* MacOS version : 12.3
* XCode Version : 13.3.1

**Describe the bug**
I start the test on a emulator, I'll get the logs of info you do when starting a kivy app, and it all works smoothly. When I attempt to do this on my ios 14.2 phone, it gives me the logs, then says dlopen fallback error. Despite this, it still opens the app. The text input works, but all the buttons do not. After you click a button, it will say ```(name) was compiled with optimization - stepping may behave oddly; variables may not be available.​ ``` 

**To Reproduce**
Create a toolchain app, run it. My app does use audio, if that changes anything. Also iphone 7 and below isn't available in xcode. Maybe there isn't support with it.

**Expected behavior**
My app doesn't crash when hitting buttons.

**Logs**
```
(Name) was compiled with optimization - stepping may behave oddly; variables may not be available.​ 
```

**Comment by akshayaurora** [comment]
@momomomomos can you please post the backtrace.

**Comment by momomomomos** [comment]
Please disregard, I just had sound and didn't add the right frameworks

**Comment by momomomomos** [comment]
I would like to let anybody reading know that this was solved by me using avf audio framework. What was happening was that i was playing audio when the button was clicked but i did not have an audio framework to support it so the app had crashed
