### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_PIL__imaging)

### ISSUE THREAD

**Issue by pythonsus** [kivy/kivy-ios#711]
**Versions**

* Python : 3.9.9
* MacOS version :12.4 monterey
* XCode Version :13.4
* Cython version :0.29.17

**Describe the bug**
ImportError: dynamic module does not define module export function (PyInit_PIL__imaging)

**To Reproduce**
// REPLACE ME: Add your `toolchain.py ....` command or a complete explanation of what you did so We can reproduce your error.

**Expected behavior**
importError: dynamic module does not define module export function (PyInit_PIL__imaging)

**Logs**
```

```

**Screenshots**

**Additional context**

**Comment by misl6** [comment]
Hi @pythonsus,

Did you seen: https://github.com/kivy/kivy-ios/issues/644 ?
If `kivymd` is in your requirements, you may be interested in the following workaround: https://github.com/kivy/kivy-ios/issues/644#issuecomment-996143345

**Comment by pythonsus** [comment]
is tehrer python 3.10 support?

**Comment by misl6** [comment]
> is tehrer python 3.10 support?

Python 3.10 support is available on `kivy-ios` `master` branch. Can we mark this issue as resolved and a duplicate of #644 ?

**Comment by pythonsus** [comment]
yes
