### ISSUE TITLE
Build iOS project always fails at 2nd script 

### ISSUE THREAD

**Issue by saminapoleon** [kivy/kivy-ios#713]
Hi All,

          build ios project always fails with below issue:
Listing '/Users/sami/kivy-ios/my-p-05-ios/YourApp/venv/share/glew'...
Listing '/Users/sami/kivy-ios/my-p-05-ios/YourApp/venv/share/glew/bin'...
Listing '/Users/sami/kivy-ios/my-p-05-ios/YourApp/venv/share/sdl2'...
Listing '/Users/sami/kivy-ios/my-p-05-ios/YourApp/venv/share/sdl2/bin'...
Command PhaseScriptExecution failed with a nonzero exit code

the script as below

/Users/sami/kivy-ios/dist/hostpython3/bin/python -m compileall -f -b "$PROJECT_DIR"/YourApp

any ideas how to solve this issue?

Thanks

**Comment by misl6** [comment]
Hi @saminapoleon , can you post the whole build log?

**Comment by saminapoleon** [comment]
Hi @misl6 

[Build target my-p-05_2022-06-05T00-41-39.txt](https://github.com/kivy/kivy-ios/files/8839634/Build.target.my-p-05_2022-06-05T00-41-39.txt)

**Comment by misl6** [comment]
This is a failure that happens during package time (On XCode or on the CLI), and not during the `toolchain build ...` / `toolchain create ..` I am right?

**Comment by saminapoleon** [comment]
@misl6 

yes this happened after toolchain creation when I press play to from Xcode to build IOS

**Comment by misl6** [comment]
Looks like is including your `venv` folder, which should not be added to the iOS package.

In XCode, under the "Build Phases" Tab , there's a (Run script phase) rsync command, which is syncing your app folder.

If you want to keep your `venv` folder, without syncing it into the package, you should exlude it via `--exclude` into this rsync command.

I'm closing the issue as a `support` one, but feel free to join us on Discord!

**Comment by saminapoleon** [comment]
but if I excluded another issue will appear could not open main.py

**Comment by saminapoleon** [comment]
@misl6 

after excluding

my-p-06[5449:183385] Running main.py: (null)
2022-06-05 05:39:35.695339-0700 my-p-06[5449:183385] Unable to open main.py, abort.
2022-06-05 05:39:35.701519-0700 my-p-06[5449:183385] Leaving

**Comment by saminapoleon** [comment]
Dears,

     the issue not solved yet...


thanks
