### ISSUE TITLE
Proposal of versioning numbering method change for the next release

### ISSUE THREAD

**Issue by misl6** [kivy/kivy-ios#729]
- `kivy-ios` releases currently use `semantic versioning` (last release was `1.3.0`). (`MAJOR.MINOR.PATCH`)
- Like `python-for-android`, many changes in `kivy-ios` are driven by XCode / iOS / macOS updates.
- More often we're encouraging users on our support channels to use the latest changes available on the `master` branch in order to avoid issues they're encountering with the released version of `kivy-ios`.
- `semantic versioning` doesn't allow us to release a minor release if it only contains patches.
- Managing (and releasing) multiple minor versions at the same time, in order to contain the needed patches is hard.

Considering these points, the proposal is to change the versioning numbering method change for the next release.

The most obvious idea is to use the `calendar versioning <https://calver.org/>` ( `YYYY.0M.DD` ), as it's the same versioning method that `python-for-android` started using 3 years ago, for a similar reason.

**Comment by AndreMiras** [comment]
I have nothing against it :+1:

**Comment by misl6** [comment]
Fixed via #734
