### ISSUE TITLE
`ImportError` subprocess

### ISSUE THREAD

**Issue by Neizvestnyj** [kivy/kivy-ios#730]
```py
from kivy.app import App
from kivy.uix.button import Button
from subprocess import Popen, PIPE, STDOUT, TimeoutExpired

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()
```

```bash
toolchain build python3 kivy openssl
```

```bash
single mode, not docked
Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file)
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file)
 Traceback (most recent call last):
   File "/Users/neizvestnyj/PycharmProjects/<APP>/ios/test/test-ios/YourApp/main.py", line 5, in <module>
 ImportError: cannot import name 'Popen' from 'subprocess' (unknown location)**
 ```

**Comment by Neizvestnyj** [comment]
> Hi @Neizvestnyj !
> 
> Did you seen: https://github.com/kivy/kivy-ios#why-does-the-python-multiprocesssubprocess-module-not-work ?

I use subprocess to execute command in command line. On Python IDE for ios its work. What should I use instead of subprocess Popen, communicate, run? Any examples?

**Comment by misl6** [comment]
> > Hi @Neizvestnyj !
> > Did you seen: https://github.com/kivy/kivy-ios#why-does-the-python-multiprocesssubprocess-module-not-work ?
> 
> I use subprocess to execute command in command line. On Python IDE for ios its work. What should I use instead of subprocess Popen, communicate, run? Any examples?

It highly depends on what are you trying to achieve.

I'm closing the issue as a support one, but feel free to ping me on Discord 😄
