### ISSUE TITLE
[BUG] Kivy Ios on mac os monterey arm64 simulator

### ISSUE THREAD

**Issue by jhay06** [kivy/kivy-ios#740]
Hi , would like to request help 

when building kivy apps  on a simulator on mac os monterey with arm64/applesilicon in rosetta x86_64 environment,  apps is too slow , 

Speed rating 👎   , 

then i tried to build in native arm64 but as soon as i hit play in xcode , it does not build 
![image](https://user-images.githubusercontent.com/5191437/183282027-81d9d493-8812-4767-a2aa-4b51f3eb8448.png)

how i can run kivy apps in native speed ?

**Comment by jhay06** [comment]
mac os monterey with apple silicon doesn't use i386 simulator app ,it is using arm64  so i think the slow experience is due to app was built in i386 simulator instead of arm64 simulator .

**Comment by jhay06** [comment]
any updates ?

**Comment by misl6** [comment]
Closing in favor of #751
