### ISSUE TITLE
dynamic module does not define module export function (PyInit__sqlite3)

### ISSUE THREAD

**Issue by hui0613** [kivy/kivy-ios#743]
i want to use sqlite3 in pyhton, when i run the program, the following error occurs, what do i need to do
<img width="1279" alt="Snipaste_2022-08-23_18-10-53" src="https://user-images.githubusercontent.com/45350664/186133263-f127e834-dc6a-465b-8291-ab517a3ebfef.png">

**Versions**

* Python : 3.8
* MacOS version : 12.2.1 ( M1 )
* XCode Version : 13.1
* Cython version :  0.29.32

**Comment by misl6** [comment]
Hi @hui0613 
What's your `kivy-ios` version?

**Comment by hui0613** [comment]
@misl6  How should I check the version of `kivy-ios` ? I just installed `kivy-ios` yesterday by following the steps below. Am I missing something ?

<img width="798" alt="Snipaste_2022-08-24_09-25-47" src="https://user-images.githubusercontent.com/45350664/186297416-808f0b85-1e85-4fba-b164-3d9d6ed50749.png">

**Comment by hui0613** [comment]
Is there a solution to this problem？

**Comment by misl6** [comment]
> I just installed kivy-ios yesterday by following the steps below

We're now targeting Python 3.9.9, but from your logs seems your app is referring to Python 3.8, is the `xcodeproj` been generated with a previous version of `kivy-ios` ?

Also, does not seem to follow our usual structure. Did you make any custom changes?

**Comment by hui0613** [comment]
> > 我昨天按照以下步骤安装了 kivy-ios
> 
> 我们现在的目标是 Python 3.9.9，但从您的日志看来，您的应用程序指的是 Python 3.8，是否`xcodeproj`使用以前版本的`kivy-ios`?
> 
> 此外，似乎没有遵循我们通常的结构。您是否进行了任何自定义更改？


Yes, I need to use `kivy-ios` to provide the runtime environment, and the UI still uses swift or object-c. When I create the project using `toolchain create <title> <path>`, I can successfully import `sqlite3`, I will understand the structure of this project and make changes accordingly. thank you very much

**Comment by misl6** [comment]
Yeah, we had an issue previously with `sqlite3` that has been later fixed.
Closing the issue as support.
