### ISSUE TITLE
Unknown class `<BoxShadow>`

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy-ios#758]
There is a bug in `Kivy-iOS` (I assume it's a bug). You can't use the `Kivy` of `master` version because the `BoxShadow` class was not found. This is strange, because looking at the logs I see that it is the `master` version of the `Kivy framework` that is being used:

![Снимок экрана 2023-01-15 в 14 40 23](https://user-images.githubusercontent.com/16930280/212538865-1fa18227-66e1-49b3-86b6-3dc64020b25a.png)

![Снимок экрана 2023-01-15 в 14 44 34](https://user-images.githubusercontent.com/16930280/212538871-3c83d165-e6a7-4086-bfd7-d63ef376649b.png)

**Comment by misl6** [comment]
Did you cleaned the `.cache` folder (The one that stores the previous packages downloads) before the build?

**Comment by HeaTTheatR** [comment]
@misl6 No. Now I'm trying to do it and test it again...

**Comment by HeaTTheatR** [comment]
Cleaning up previous builds helped.
