### ISSUE TITLE
create-xcode-project.sh creates unusable project

### ISSUE THREAD

**Issue by yep** [kivy/kivy-ios#77]
Compiling a test project does not work. Here's how to reproduce.

If I run `tools/create-xcode-project.sh test test`, open the project with `open app-test/test.xcodeproj` and then build the project it produces an error.

The `run script` build phase fails. It runs a bash script which executes `../tools/populate-project.sh test test`.

Here's the corresponding script output:

```
+ try rsync -av --delete test/ /PATH/TO/KIVY/REPOSITORY/kivy-ios/app-test/YourApp
+ rsync -av --delete test/ /PATH/TO/KIVY/REPOSITORY/kivy-ios/app-test/YourApp
building file list ... rsync: link_stat "/PATH/TO/KIVY/REPOSITORY/kivy-ios/app-test/test/." failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-42/rsync/main.c(992) [sender=2.6.9]
+ exit -1
Command /bin/sh failed with exit code 255
```

setup: osx 10.9, xcode 5.0.2, homebrew, used pip and not easy_install to install cython.

**Comment by tito** [comment]
the project creation has been rebuild from a fresh new template, this issue should be resolved.
