### ISSUE TITLE
Asset validation failed Invalid bundle structure. The “theweatherreporterapp.app/lib/python3.9/site-packages/charset_normalizer/md__mypyc.cpython-39-darwin.so” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: eb2a7a62-515c-459b-a222-5330e609551d)

### ISSUE THREAD

**Issue by pythonsus** [kivy/kivy-ios#773]
**Versions**

* Python :3.10.2 and python3.9.12
* MacOS version :13.1
* XCode Version :14.2
* Cython version :0.29.33

**Describe the bug**
when acrhive to app store connect getting Asset validation failed
Invalid bundle structure. The “theweatherreporterapp.app/lib/python3.9/site-packages/charset_normalizer/md__mypyc.cpython-39-darwin.so” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: eb2a7a62-515c-459b-a222-5330e609551d)

**To Reproduce**
 use kivy install git and pip then toolchain build python3 kivy pillow then toolchain pip install pyowm,kivymd then toolchain create then remove libfreetype.a file then archive to app store connect then get Asset validation failed
Invalid bundle structure. The “theweatherreporterapp.app/lib/python3.9/site-packages/charset_normalizer/md__mypyc.cpython-39-darwin.so” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: eb2a7a62-515c-459b-a222-5330e609551d)

**Expected behavior**
app should go to testfilght

**Logs**
```
Asset validation failed
Invalid bundle structure. The “theweatherreporterapp.app/lib/python3.9/site-packages/charset_normalizer/md__mypyc.cpython-39-darwin.so” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: eb2a7a62-515c-459b-a222-5330e609551d)
```

**Screenshots**

**Additional context**

**Comment by misl6** [comment]
You should use the following to remove the broken dependency ( I guess you now installed `chardet` as an alternative ) : 

`toolchain pip uninstall charset-normalizer -y`

**Comment by pythonsus** [comment]
ok

**Comment by pythonsus** [comment]
will try

**Comment by pythonsus** [comment]
[DEBUG   ] Found existing installation: charset-normalizer 3.0.1
[DEBUG   ] Not uninstalling charset-normalizer at /Users/suhaan/Documents/kivy-ios/dist/root/python3/lib/python3.9/site-packages, outside environment /Users/suhaan/Documents/kivy-ios/venv
[DEBUG   ] Can't uninstall 'charset-normalizer'. No files were found to uninstall.

**Comment by pythonsus** [comment]
nvm fixed had to start a new env
