### ISSUE TITLE
sh.CommandNotFound: /Users/suhaan/Documents/weatherappkivy/dist/hostpython3/bin/pip3

### ISSUE THREAD

**Issue by pythonsus** [kivy/kivy-ios#775]
**Versions**

* Python :3.10.2,3.9.11
* MacOS version :13.1
* XCode Version :14.2
* Cython version :0.29.33

**Describe the bug**
when running toolchain build python3 kivy getting sh.CommandNotFound: /Users/suhaan/Documents/weatherappkivy/dist/hostpython3/bin/pip3

**To Reproduce**
pip install and git method of kivy-ios then toolchain build python3 kivy

**Expected behavior**
kivy and python3 build should work

**Logs**
```
sh.CommandNotFound: /Users/suhaan/Documents/weatherappkivy/dist/hostpython3/bin/pip3
```

**Screenshots**

**Additional context**

**Comment by misl6** [comment]
Hi @pythonsus !

Can you please post the full output?

**Comment by pythonsus** [comment]
i fixed by add anoter exe file from my env i copied it
