### ISSUE TITLE
[color] markup tags seem to have red-blue reversed

### ISSUE THREAD

**Issue by markusdf** [kivy/kivy-ios#78]
It appears that labels with markup=True have the red \* blue color component reversed when the app is run inside an iOS (in this case 7.04, iPhone 5) environment. Same data, same [color] codes, different output.

iPhone (wrong): 
![image](https://f.cloud.github.com/assets/5422580/1749820/59c443d4-6543-11e3-9e4e-620cd6e32eca.png)

Windows & OSX (correct):
![image](https://f.cloud.github.com/assets/5422580/1749821/90244da2-6543-11e3-8542-45c9434cf73c.png)

the codes used are [color="ff0000"], [color="ffa500"], [color="00ff00"]
##

**Comment by Zen-CODE** [comment]
Can't reproduce this. Colors appears fine in my tests (running in iOS 9.2 simulator). Please can you perhaps try with a newer Kivy/kivy-ios. Perhaps it's been fixed already?
