### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by pythonsus** [kivy/kivy-ios#783]
**Versions**

* Python : 3.9
* MacOS version :13.2
* XCode Version :14.2
* Cython version :0.29.3

**Describe the bug**
// when running xcode getting Command PhaseScriptExecution failed with a nonzero exit code

**To Reproduce**
// use kivy ios with development version then toolchain build python3 kivy pillow then toolchain pip install pyowm SpeechRecognition requests kivymd then create project.After that run the xcode file and get Command PhaseScriptExecution failed with a nonzero exit code
.

**Expected behavior**
//Build should work

**Logs**
Command PhaseScriptExecution failed with a nonzero exit code

// Command PhaseScriptExecution failed with a nonzero exit code

**Screenshots**

**Additional context**

**Comment by misl6** [comment]
Hi @pythonsus ,

Can you please provide the full XCode console output?

**Comment by pythonsus** [comment]
If I click reveal in project navigator nothing comes

**Comment by pythonsus** [comment]
here is a screenshot 
<img width="266" alt="Screenshot 2023-03-18 at 9 23 40 AM" src="https://user-images.githubusercontent.com/91991802/226108922-024df515-2ff0-4313-aa9a-967ec252c03e.png">

**Comment by pythonsus** [comment]
i got nothing

**Comment by pythonsus** [comment]
Look at #793
