### ISSUE TITLE
Pyaudio

### ISSUE THREAD

**Issue by pythonsus** [kivy/kivy-ios#785]
**Is your feature request related to a problem? Please describe.**
When I try to install pyaudio using toolchain pip install pyaudio it does not work and says no module named pyaudio

**Describe the solution you'd like**
A recipe for pyaudio

**Describe alternatives you've considered**

**Additional context**

**Comment by pythonsus** [comment]
nvm it works i am very srry

**Comment by olamicreas** [comment]
> nvm it works i am very srry

How did you make it work?
