### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by pythonsus** [kivy/kivy-ios#793]
**Versions**

* Python :3.10 or 3.9 tried both
* MacOS version :13.3.1 ventura
* XCode Version :14.3 or 14.2
* Cython version :0.29.3

**Describe the bug**
When running my xcode project getting Command PhaseScriptExecution failed with a nonzero exit code.

**To Reproduce**
make env, install kivy-ios with development version, toolchain build python3 kivy pillow,toolchain pip --no-deps kivymd,toolchain pip install geopy requests scipy sounddevice, toolchain pip install git+https://github.com/openai/whisper.git ,toolchain create WeatherPsychic /Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/, open weatherpsychic-ios/weatherpsychic.xcodeproj, and run and get Command PhaseScriptExecution failed with a nonzero exit code.When clicking on it nothing appears same if say reveal in project navigator.After Sometime the error comes. 

**Expected behavior**
program to work

**Logs**
```
Command PhaseScriptExecution failed with a nonzero exit code
```

**Screenshots**

**Additional context**
Code:
```
from kivymd.app import MDApp
from kivymd.uix.dialog import MDDialog
from kivymd.uix.label import MDLabel
from kivymd.uix.screen import MDScreen
from kivymd.uix.button import MDRectangleFlatButton, MDFlatButton
import whisper
import sounddevice as sd
from scipy.io.wavfile import write
import os 
from kivy.lang import Builder
from kivymd.uix.textfield import MDTextField
from kivy.config import Config
from kivy.uix.image import Image
from kivymd.uix.button import MDIconButton
import requests


token='serect'
city_helper ="""
MDTextField:
    hint_text: "Enter city name with country or state"
    helper_text: "eg: Rock Hill,us or 29730, US"
    helper_text_mode: "on_focus"
    pos_hint: {'center_x':0.35,'center_y':0.8}
    size_hint_x: None
    width:680
    icon_right: "weather-partly-cloudy"
    mode:"fill"
    
    on_text_validate: self.s
   
    
 


"""
from geopy.geocoders import Nominatim
def cptizefirtword(word):
    result = ""
    for i in word:
        if i.isupper():
            result=result+" "+i.upper()
        else:
            result=result+i
    return result[1:]
def get_location_info(lat, long):
    geolocator = Nominatim(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36')
    location = geolocator.reverse(f"{lat}, {long}")
    address = location.raw['address']
    city = address.get('city', '')
    state = address.get('state', '')
    country = address.get('country', '')
    
    if not city:
        return f"{state}, {country}"
    
    return f"{city}, {state}, {country}"

#5386fe8b412f65c8fe185582a8a170a7

def citytocords(cityname):

    geolocator = Nominatim(user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36") 
    c=geolocator.geocode(cityname)
    long=c.longitude
    lat=c.latitude
    return f"{lat},{long}"


# Search for current weather in London (Great Britain) and get details

def get_weather( latitude: float, longitude: float, language: str = "en", timezone: str = "America/New_York",
                    dataSets: list[str] = ["currentWeather", "forecastDaily"]) -> dict:
       
        url = f"https://weatherkit.apple.com/api/v1/weather/{language}/{latitude}/{longitude}"
        headers = {
            "Authorization": f"Bearer {token}"
        }
        params = {
            "timezone": timezone,
            "dataSets": ",".join(dataSets)
        }
        response = requests.get(url, headers=headers, params=params)

        return response.json()

class Weatherapp(MDApp):
    def has_numbers(self,inputString):
        return any(char.isdigit() for char in inputString)
    def build(self):
        self.screen = MDScreen()
        I=Image(source='apple.png',pos_hint={'center_x':0.125,'center_y':0.1})
        I1=MDLabel(text='Weather',pos_hint={'center_x':0.65,'center_y':0.1},font_style='H4')
        self.l1 = MDLabel(text='Weather Psychic',pos_hint={'center_x':0.6,'center_y':0.86},font_style='H4')
        self.l2 = MDLabel(text='', pos_hint={'center_x': 0.825, 'center_y': 0.57})
        self.l3 = MDLabel(text='', pos_hint={'center_x': 0.8, 'center_y': 0.44})
        self.l4 = MDLabel(text='', pos_hint={'center_x': 0.8, 'center_y': 0.38})
        #self.l6 =MDLabel(text='Alerts:', pos_hint={'center_x': 0.525, 'center_y': 0.45})
        self.l5 = MDLabel(text='[b][/b]', pos_hint={'center_x': 0.8, 'center_y': 0.65},markup=True,font_style='H1')
        self.l7 = MDLabel(text='',pos_hint={'center_x': 0.8, 'center_y': 0.53},bold=True,font_style='H5')
        self.l8 = MDLabel(text='',pos_hint={'center_x': 0.8, 'center_y': 0.48},bold=True,font_style='H5')
        self.l9 = MDLabel(text='', pos_hint={'center_x': 0.8, 'center_y': 0.41})
        self.city = MDTextField(hint_text= "city,ctry or zipcode,ctry",
    helper_text= "eg: Rock Hill,us or 29730,us",
    helper_text_mode= "on_focus",
    pos_hint= {'center_x':0.35,'center_y':0.78},
    size_hint_x= None,
    width=680,
    
    mode="fill")#Builder.load_string(city_helper)
        #tool=Builder.load_string(ts)
        #keyboard=VKeyboard(on_key_up=self.keyup)
        IB1=MDIconButton(icon="microphone",pos_hint={"center_x": 0.03, "center_y": 0.78},on_release=self.record)
        c1= MDRectangleFlatButton(text='Celsius',pos_hint={'center_x':0.2,'center_y':0.3},on_release=self.c)
        d1= MDRectangleFlatButton(text='Dark Theme',pos_hint={'center_x':0.55,'center_y':0.2},on_release=self.d)
        l1= MDRectangleFlatButton(text='White Theme',pos_hint={'center_x':0.22,'center_y':0.2},on_release=self.l)
        b1 = MDRectangleFlatButton(text='Search',pos_hint={'center_x':0.73,'center_y':0.78},on_release=self.showresults)
        f1 = MDRectangleFlatButton(text='Fahrenheit',pos_hint={'center_x':0.55,'center_y':0.3},on_release=self.f)
        clear1 = MDRectangleFlatButton(text='Clear Text',pos_hint={'center_x':0.55,'center_y':0.15},on_release=self.clear)
        self.screen.add_widget(I)
        self.screen.add_widget(self.city)
        self.screen.add_widget(self.l1)
        self.screen.add_widget(self.l7)
        self.screen.add_widget(I1)
        self.screen.add_widget(d1)
        self.screen.add_widget(l1)
        self.screen.add_widget(b1)
        self.screen.add_widget(c1)
        self.screen.add_widget(f1)
        self.screen.add_widget(IB1)
        self.screen.add_widget(clear1)
        #self.screen.add_widget(keyboard)
        self.screen.add_widget(self.l2)
        self.screen.add_widget(self.l3)
        self.screen.add_widget(self.l4)
        self.screen.add_widget(self.l5)
        self.screen.add_widget(self.l8)
        self.screen.add_widget(self.l9)
        #screen.add_widget(tool)
        return self.screen
    def c(self,obj):
        try:
            
            geolocator = Nominatim(user_agent="Mozilla/5.0 (X11; CrOS aarch64 15236.80.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.125 Safari/537.36") 
            c=geolocator.geocode(self.city.text)
            long=c.longitude
            lat=c.latitude
            print(lat,long)
            # url = f"https://weatherkit.apple.com/api/v1/weather/en/{lat}/{long}"
            # response = requests.get(url, headers=headers, params=params)
            # w=response.json()
            w=get_weather(lat,long)
            hum=w['currentWeather']['humidity']
            wd=w['currentWeather']['windDirection']   
            ds=w['currentWeather']['conditionCode']
            t=round(w['currentWeather']['temperature'])
            mint=round(w['forecastDaily']['days'][0]['temperatureMin'])
            maxt=round(w['forecastDaily']['days'][0]['temperatureMax'])
            ww=w['currentWeather']['windSpeed']
            
            fl=round(w['currentWeather']['temperatureApparent'])
            hum=str(hum).strip('0')
            hum=hum.strip('.')
            #self.l1.text=f"{get_location_info(lat=lat,long=long)}"
            self.l2.text = f'{ds}'
            #self.l6.text = f'Alerts:{alert(c[0],c[1])}'
            self.l3.text = f'Wind Speed: {round(ww/1.609)} mph Wind Degree: {wd} '
            self.l4.text = f'Humidity: {hum}%'
            self.l5.text = f'[b]{t}°[/b]'
            self.l7.text = f'H:{maxt} L:{mint}'
            self.l8.text=f"Feels Like:{fl}°"
            
           
        except:
            self.dialog = MDDialog(title='Error',
                                    text='Please enter a city,country name or try again in 60 seconds', size_hint=(0.8, 1),
                                   buttons=[MDFlatButton(text='Close', on_release=self.close_dialog),
                                             ]
                                    )
            #self.dialog.open()
    def d(self,i):
        self.theme_cls.theme_style="Dark"
    def l(self,i):
        self.theme_cls.theme_style="Light"
    # def s(self, value):
    #      if value:
    #             print('MDTextField clicked')
    #             c=self.city.text.split(',')
    #             print(c)
                
    #             list_of_tuples = reg.ids_for(c[0], matching='like')
    #             #print(list_of_tuples) 
    #             stufflike=[]
    #             latl=[]
    #             lonl=[]
    #             for i in range(len(list_of_tuples)):
    #                 stufflike.append(list_of_tuples[i][4])
    #                 stufflike.append(list_of_tuples[i][5])
                
    #             #print(stufflike)
    #             #print(self.city.text)

    #             for index, element in enumerate(stufflike):
    #                 if index % 2 == 0:
    #                     latl.append(element)
    #                 else:
    #                     lonl.append(element)
    #             #print(len(latl),len(lonl))
    #             cities=[]

    #             for i in range(len(latl)):
    #                 cities.append(get_location_info(latl[i],lonl[i]))
    #             print(cities)
                
    def showresults(self,obj):
        
        try:
            geolocator = Nominatim(user_agent="Mozilla/5.0 (X11; CrOS aarch64 15236.80.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.125 Safari/537.36") 
            c=geolocator.geocode(self.city.text)
            long=c.longitude
            lat=c.latitude
            print(lat,long)
            # url = f"https://weatherkit.apple.com/api/v1/weather/en/{lat}/{long}"
            # response = requests.get(url, headers=headers, params=params)
            # w=response.json()
            # print(w)
            w=get_weather(lat,long)
            hum=w['currentWeather']['humidity']
            
            wd=w['currentWeather']['windDirection']   
            ds=w['currentWeather']['conditionCode']
            
            ds=cptizefirtword(str(ds))
            t=round(w['currentWeather']['temperature']*1.8+32)
            mint=round(w['forecastDaily']['days'][0]['temperatureMin']*1.8+32)
            maxt=round(w['forecastDaily']['days'][0]['temperatureMax']*1.8+32)
            ww=round(w['currentWeather']['windSpeed'])
            fl=round(w['currentWeather']['temperatureApparent']*1.8+32)
            hum=str(hum).strip('0')
            hum=hum.strip('.')
            self.l1.text=f"{get_location_info(lat=lat,long=long)}"
            self.l2.text = f'{ds}'
            #self.l6.text = f'Alerts:{alert(c[0],c[1])}'
            self.l3.text = f'Wind Speed: {round(ww/1.609)} mph'
            self.l4.text = f'Humidity: {hum}%'
            self.l5.text = f'[b]{t}°[/b]'
            self.l7.text = f'H:{maxt} L:{mint}'
            self.l8.text=f"Feels Like:{fl}°"
            self.l9.text=f'Wind Degree: {wd}'
        except:
            self.dialog = MDDialog(title='Error',
                                    text='Please enter a city,country name or try again in 60 seconds', size_hint=(0.8, 1),
                                   buttons=[MDFlatButton(text='Close', on_release=self.close_dialog),
                                             ]
                                    )
            self.dialog.open()
    # def keyup(self,keyboard,keycode,*args):
    #     if isinstance(keycode,tuple):
    #         keycode=keycode[1]
    #     t=self.city.text
    #     if keycode=="spacebar":
    #         keycode=" "
    #     if keycode=="backspace":
    #         t=t[:-1]
    #         keycode=''
    #     if keycode=='enter':
    #         keycode=''
    #         self.showresults('f')
        
            
        
        #self.city.text=f"{t}{keycode}"
    def f(self,obj):
        
        try:
            geolocator = Nominatim(user_agent="Mozilla/5.0 (X11; CrOS aarch64 15236.80.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.125 Safari/537.36") 
            c=geolocator.geocode(self.city.text)
            long=c.longitude
            lat=c.latitude
            print(lat,long)
            # url = f"https://weatherkit.apple.com/api/v1/weather/en/{lat}/{long}"
            # response = requests.get(url, headers=headers, params=params)
            # w=response.json()
            # print(w)
            w=get_weather(lat,long)
            hum=w['currentWeather']['humidity']
            
            wd=w['currentWeather']['windDirection']   
            ds=w['currentWeather']['conditionCode']
            
            ds=cptizefirtword(str(ds))
            t=round(w['currentWeather']['temperature']*1.8+32)
            mint=round(w['forecastDaily']['days'][0]['temperatureMin']*1.8+32)
            maxt=round(w['forecastDaily']['days'][0]['temperatureMax']*1.8+32)
            ww=round(w['currentWeather']['windSpeed'])
            fl=round(w['currentWeather']['temperatureApparent']*1.8+32)
            hum=str(hum).strip('0')
            hum=hum.strip('.')
            #self.l1.text=f"{get_location_info(lat=lat,long=long)}"

            self.l2.text = f'{ds}'
            #self.l6.text = f'Alerts:{alert(c[0],c[1])}'
            self.l3.text = f'Wind Speed: {round(ww/1.609)} mph'
            self.l4.text = f'Humidity: {hum}%'
            self.l5.text = f'[b]{t}°[/b]'
            self.l7.text = f'H:{maxt} L:{mint}'
            self.l8.text=f"Feels Like:{fl}°"
            self.l9.text=f'Wind Degree: {wd}'
        except:
            self.dialog = MDDialog(title='Error',
                                    text='Please enter a city,country name or try again in 60 seconds', size_hint=(0.8, 1),
                                   buttons=[MDFlatButton(text='Close', on_release=self.close_dialog),
                                             ]
                                    )
            self.dialog.open()
    def close_dialog(self, obj):
        self.dialog.dismiss()
    def record(self,j):
        
        try:


            fs = 44100
            
            duration = 3 
            myrecording = sd.rec(int(duration * fs), samplerate=fs, channels=1)
            sd.wait() 
            write('output.wav', fs, myrecording) 
            model = whisper.load_model("base")
            result = model.transcribe("output.wav",fp16=False)
            res=str(result["text"]).strip('.')
            self.city.text=res
            os.remove('output.wav')
        except:
            self.dialog = MDDialog(title='Error',
                                    text='Please try again.It only last for 3 seconds.If you spam it, it might not work.', size_hint=(0.8, 1),
                                   buttons=[MDFlatButton(text='Close', on_release=self.close_dialog),
                                             ]
                                    )
            self.dialog.open()
    def clear(self,j):
        self.city.text=''

Weatherapp().run()
```

**Comment by pythonsus** [comment]
<img width="278" alt="Screenshot 2023-04-18 at 7 50 18 PM" src="https://user-images.githubusercontent.com/91991802/232928805-6952582c-d2ea-498a-a667-e3bec9eae8b1.png">

**Comment by pythonsus** [comment]
Showing Recent Messages
Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/graph/plot_napoleon_russian_campaign.py'...

Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/graph/plot_roget.py'...

Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/graph/plot_triad_types.py'...

Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/graph/plot_words.py'...

Listing '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/subclass'...

Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/subclass/plot_antigraph.py'...

Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/subclass/plot_printgraph.py'...

Listing '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/man'...

Listing '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/man/man1'...

Command PhaseScriptExecution failed with a nonzero exit code

**Comment by pythonsus** [comment]
this is the last logs

**Comment by misl6** [comment]
> Showing Recent Messages Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/graph/plot_napoleon_russian_campaign.py'...
> 
> Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/graph/plot_roget.py'...
> 
> Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/graph/plot_triad_types.py'...
> 
> Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/graph/plot_words.py'...
> 
> Listing '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/subclass'...
> 
> Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/subclass/plot_antigraph.py'...
> 
> Compiling '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/doc/networkx-3.1/examples/subclass/plot_printgraph.py'...
> 
> Listing '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/man'...
> 
> Listing '/Users/suhaan/Documents/Suhaans_mac_python_programs/weatherapp/kivy-ios/weatherpsychic-ios/YourApp/share/man/man1'...
> 
> Command PhaseScriptExecution failed with a nonzero exit code

Hi @pythonsus !

Unfortunately this doesn't look enough to say why it's failing.
Is the `share/doc/networkx-3.1` folder supposed to be here?

**Comment by pythonsus** [comment]
it is one of the modules

**Comment by pythonsus** [comment]
do you want full logs

**Comment by pythonsus** [comment]
fixed that issue by changing numpy version for recipe to 1.23.5 and building numpy but now got a torch issue

**Comment by pythonsus** [comment]
Warning: Error creating LLDB target at path '/Users/suhaan/Library/Developer/Xcode/DerivedData/weatherpsychic-helntvkgjatnupgdpnfwkavfqabl/Build/Products/Debug-iphonesimulator/weatherpsychic.app'- using an empty LLDB target which can cause slow memory reads from remote devices.
2023-04-22 17:39:24.633005-0400 weatherpsychic[73050:6376689] Could not load the "icon.png" image referenced from a nib in the bundle with identifier "com.weather.suhaan"
2023-04-22 17:39:24.836729-0400 weatherpsychic[73050:6376689] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2023-04-22 17:39:24.836838-0400 weatherpsychic[73050:6376689] Initializing python
<string>:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
2023-04-22 17:39:24.994550-0400 weatherpsychic[73050:6376689] Running main.py: /Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/YourApp/main.pyc
[INFO   ] [Logger      ] Record log in /Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Data/Application/40940BF8-7E56-4847-8158-1EF36A02B720/Documents/.kivy/logs/kivy_23-04-22_2.txt
[INFO   ] [Kivy        ] v2.2.0.dev0
[INFO   ] [Kivy        ] Installed at "/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.10 (main, Apr 22 2023, 15:06:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]
[INFO   ] [Python      ] Interpreter at "/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/weatherpsychic"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-02-21 (installed at "/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/lib/python3.10/site-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_tex, img_sdl2 (img_dds, img_ffpyplayer, img_pil ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
2023-04-22 17:39:25.587844-0400 weatherpsychic[73050:6376689] You need UIApplicationSupportsIndirectInputEvents in your Info.plist for mouse support
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 APPLE-20.5.2'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple Software Renderer'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/suhaan/Library/Developer/Xcode/DerivedData/weatherpsychic-helntvkgjatnupgdpnfwkavfqabl/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file, no dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Users/suhaan/Library/Developer/Xcode/DerivedData/weatherpsychic-helntvkgjatnupgdpnfwkavfqabl/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/C/Foundation' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (no such file, no dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (no such file)
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/suhaan/Library/Developer/Xcode/DerivedData/weatherpsychic-helntvkgjatnupgdpnfwkavfqabl/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file)
 Traceback (most recent call last):
   File "/Users/suhaan/Documents/kivy-ios/weatherpsychic-ios/YourApp/main.py", line 7, in <module>
   File "/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/lib/python3.10/site-packages/whisper/__init__.py", line 8, in <module>
     import torch
   File "/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/lib/python3.10/site-packages/torch/__init__.py", line 228, in <module>
     _load_global_deps()
   File "/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/lib/python3.10/site-packages/torch/__init__.py", line 187, in _load_global_deps
     raise err
   File "/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/lib/python3.10/site-packages/torch/__init__.py", line 168, in _load_global_deps
     ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
   File "/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/lib/python310.zip/ctypes/__init__.py", line 374, in __init__
 OSError: dlopen(/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/lib/python3.10/site-packages/torch/lib/libtorch_global_deps.dylib, 0x000A): tried: '/Users/suhaan/Library/Developer/Xcode/DerivedData/weatherpsychic-helntvkgjatnupgdpnfwkavfqabl/Build/Products/Debug-iphonesimulator/libtorch_global_deps.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection/libtorch_global_deps.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/lib/python3.10/site-packages/torch/lib/libtorch_global_deps.dylib' (no such file), '/Users/suhaan/Library/Developer/CoreSimulator/Devices/C2B4BBCD-B7D8-4325-9BF0-B3394EF6A277/data/Containers/Bundle/Application/2B3DFA10-A6FE-413C-8E0E-A8763CA5CEB6/weatherpsychic.app/lib/python3.10/site-packages/torch/lib/libtorch_global_deps.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
2023-04-22 17:39:26.327511-0400 weatherpsychic[73050:6376689] Application quit abnormally!
2023-04-22 17:39:26.357925-0400 weatherpsychic[73050:6376689] Leaving
2023-04-22 17:39:28.864301-0400 weatherpsychic[73050:6376689] [client] Timed out waiting for the exit barrier block. activeSendTransactions=0

**Comment by misl6** [comment]
`torch` is not a plain python package and will need a recipe to build.

Can you please open a feature request instead?
