### ISSUE TITLE
No log output

### ISSUE THREAD

**Issue by JohnyMoSwag** [kivy/kivy-ios#81]
Hello, I'm not able to enable logging to xcode console.  Here is a copy of my main.m file https://gist.github.com/JohnyMoSwag/8818048 with kivy_no_console commented out as directed here http://kivy.org/docs/guide/packaging-ios.html   I tried using xcode 4 and 5.

**Comment by tito** [comment]
Tested and works, please reopen if this happen again with the new toolchain / xcode 6.

**Comment by JohnyMoSwag** [comment]
Thank you
