### ISSUE TITLE
Python uses wrong flags

### ISSUE THREAD

**Issue by tcaduser** [kivy/kivy-ios#860]
**Versions**

* Python :
* MacOS version :
* XCode Version :
* Cython version :

**Describe the bug**

When building my PR #859 the Python 3.10 build fails and causes my checks to fail.   I strongly believe this is due to the fact that the randomly generated compiler name contains "icc" and this is triggering the use of "-fp-model:strict" in the build flags.

Please have kivy-ios reject a compiler containing "icc" and just start over:

compiler:

/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpyicccjzp

error:

```
2023-09-10T17:11:58.8591440Z [DEBUG   ] clangclang: : error: error: unknown argument: '-fp-model'unknown argument: '-fp-model'
2023-09-10T17:11:58.8594220Z [DEBUG   ] 
2023-09-10T17:11:58.8595130Z [DEBUG   ] clang: error: unknown argument: '-fp-model'
2023-09-10T17:11:58.8596370Z [DEBUG   ] clangclang: : error: error: no such file or directory: 'strict'no such file or directory: 'strict'
2023-09-10T17:11:58.8597430Z [DEBUG   ] 
2023-09-10T17:11:58.8597950Z [DEBUG   ] clang: error: no such file or directory: 'strict'
```

**To Reproduce**
// REPLACE ME: Add your `toolchain.py ....` command or a complete explanation of what you did so We can reproduce your error.

**Expected behavior**
// REPLACE ME: A clear and concise description of what you expected to happen.

**Logs**
```
// REPLACE ME: Paste the build output containing the error
```

**Screenshots**

**Additional context**
If it is no bother, please trigger new checks for my PR request.

**Comment by tcaduser** [comment]
more context here:
https://github.com/kivy/kivy-ios/issues/860

**Comment by tcaduser** [comment]
more context here:
https://gitlab.kitware.com/paraview/paraview/-/issues/20872

**Comment by misl6** [comment]
Ouch! That should have been painful to discover.
However, there's a pending PR on CPython upstream (where this fix belongs): https://github.com/python/cpython/pull/96399

Taking care of it is definitely not a responsibility of a toolchain like `kivy-ios`.

(I'm changing the issue title, so it's more findable)
