### ISSUE TITLE
Toolchain python version mismatch

### ISSUE THREAD

**Issue by Siamaster** [kivy/kivy-ios#869]
* Python : 3.9.18 (I think)
* MacOS version : Sonoma 14.0
* XCode Version : 15.0
* Cython version : Cython?

Probably not a bug but I'm stuck, I hope it's okay that I ask here.
I've got some instructions that used to build with xcode 14. When I tried to run them I encountered this:
When I activate venv and run python -v I get 3.9.18 but when I run toolchain recipes I "Using the bundled version for recipe "python3"     python 3.10.10.
The whole thing ends up not running because of this. First I need to change the header search path to point to 3.10 but after than I get linker error in xcode.
Should it by the way be possible to build on xcode 15 with ios 17?

**Comment by misl6** [comment]
> When I activate venv and run python -v I get 3.9.18 but when I run toolchain recipes I "Using the bundled version for recipe "python3" python 3.10.10.

This is absolutely fine. The Python version in your virtualenv can be completely different from the Python version that the toolchain is going to build (ATM `3.10.10`).

> Should it by the way be possible to build on xcode 15 with ios 17?

Yes! XCode 15 and iOS 17 are fully supported.
