### ISSUE TITLE
Add pdf2docx recipe

### ISSUE THREAD

**Issue by alihassan143** [kivy/kivy-ios#883]

**Comment by Julian-O** [comment]
[pdf2docx](https://github.com/dothinking/pdf2docx/) appears to be a pure Python solution. Why do you think you need a recipe for it?

**Comment by alihassan143** [comment]
@Julian-O  i want to write converter for my app that can convert the pdf files to docx without any third party library

**Comment by akshayaurora** [comment]
All pure python packages can be specified in buildozer.spec as a requirement or directly with kivy-ios or p4a, they should be installed using pip without any issues.
