### ISSUE TITLE
Got dlopen error on Foundation

### ISSUE THREAD

**Issue by CrackedCode7** [kivy/kivy-ios#896]
**Versions**

* Python : 3.12.2
* MacOS version : 14.2.1
* XCode Version : 15.1
* Cython version : 3.0.0

**Describe the bug**
My App was able to run on both the simulator and my own iOS device until I added Images to my .kv file. Now I am getting this error within Xcode. Is there a reason Foundation would not be included in the Frameworks when building with toolchain?

**To Reproduce**
Create a new project using toochain create projectname /path/to/project.
Set up main.py and AppName.kv file to show a single image on the screen.
Open Xcode project and run with either the simulator or build to a local device.

**Expected behavior**
I expect that when building the Foundation framework would be included by toolchain be default if needed.

**Logs**
```
Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/_redacted_/Library/Developer/Xcode/DerivedData/testproj-cxgmtbdxuvtcqwfrfxvdqrfvdjvy/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file),
```

**Comment by sumanthanumolu** [comment]
did this resolved, I am having exact same issue:

Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/jahna/Library/Developer/Xcode/DerivedData/villagers_goods-bmgxikubanqmwuhetawxtarwzhzu/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (no such file),

**Comment by HeRo002** [comment]
I always see this error message, when I deploy a Python-Kivy app on iOS using Xcode on my Mac. Also after I reinstalled MacOS from scratch a few months ago. 
But what is the significance of this error? And why is it not a bug, but a "support issue"?
Here is my version of the error:

Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/private/preboot/Cryptexes/OS/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file, not in dyld cache)
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/private/preboot/Cryptexes/OS/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file)

**Comment by HeRo002** [comment]
This is the conclusion ChatGPT gives me on the issue:

Conclusion

The error is likely benign if your app works as expected. However, it may point to a minor configuration or compatibility issue that could become more significant in the future. Addressing it preemptively by ensuring proper framework linking and up-to-date tools can help maintain long-term stability.
