### ISSUE TITLE
build x86 version for simulator too

### ISSUE THREAD

**Issue by revolunet** [kivy/kivy-ios#9]
Because i don't always have the physical devices to test it on, it would be great to be able to test the apps on the xcode simulator.

It shouldnt be difficult to create a separate `x86` build in the `build`directory.

But i don't get any idea how these two builds should integrate into the xcode project

Can you give some pointers/warnings ?

**Comment by undefiened** [comment]
Same issue as @hanattaw, @atanudey xCode6.1.1, OSX 10.10.1

**Comment by tito** [comment]
Works with the new toolchain commited on master. armv7, arm86, i386 and x86_64 are supported!
