### ISSUE TITLE
tools/build-lxml.sh not compiling

### ISSUE THREAD

**Issue by timpickles** [kivy/kivy-ios#92]
I'm trying to compile `lxml` by adding it to the end of the build scripts in `tools/build-all.sh` with the following command:

    try $(dirname $0)/build-lxml.sh

When building everything seems to go well and successfully compiles `libxml2.a` and `libxslt.a` into the `build/lib` folder but fails when starting the build of `lxml`.

Below is the log output that seems relevant just before it fails.
 
    test -z "/private/tmp/kivy-ios/tmp/lxmlinstall/bin" || ./install-sh -c -d "/private/tmp/kivy-ios/tmp/lxmlinstall/bin"
    /usr/bin/install -c xslt-config '/private/tmp/kivy-ios/tmp/lxmlinstall/bin'
    test -z "/private/tmp/kivy-ios/tmp/lxmlinstall/lib" || ./install-sh -c -d "/private/tmp/kivy-ios/tmp/lxmlinstall/lib"
    /usr/bin/install -c -m 644 xsltConf.sh '/private/tmp/kivy-ios/tmp/lxmlinstall/lib'
    test -z "/private/tmp/kivy-ios/tmp/lxmlinstall/share/aclocal" || ./install-sh -c -d "/private/tmp/kivy-ios/tmp/lxmlinstall/share/aclocal"
    /usr/bin/install -c -m 644 libxslt.m4 '/private/tmp/kivy-ios/tmp/lxmlinstall/share/aclocal'
    test -z "/private/tmp/kivy-ios/tmp/lxmlinstall/lib/pkgconfig" || ./install-sh -c -d "/private/tmp/kivy-ios/tmp/lxmlinstall/lib/pkgconfig"
    /usr/bin/install -c -m 644 libxslt.pc libexslt.pc '/private/tmp/kivy-ios/tmp/lxmlinstall/lib/pkgconfig'
    /tmp/kivy-ios
        /private/tmp/kivy-ios/tmp/lxml-2.3.1 /tmp/kivy-ios
    warning: src/lxml/xmlerror.pxi:531:22: local variable 'args' referenced before assignment
    warning: src/lxml/xmlerror.pxi:533:37: local variable 'args' referenced before assignment
    warning: src/lxml/xmlerror.pxi:537:43: local variable 'args' referenced before assignment
    warning: src/lxml/xmlerror.pxi:545:39: local variable 'args' referenced before assignment
    warning: src/lxml/xmlerror.pxi:549:40: local variable 'args' referenced before assignment
    warning: src/lxml/xmlerror.pxi:552:20: local variable 'args' referenced before assignment
    Building lxml version 2.3.1.
        Building with Cython 0.20.1.
        Using build configuration of libxslt 1.1.26
    Building against libxml2/libxslt in one of the following directories:
        /private/tmp/kivy-ios/tmp/lxmlinstall/lib
        /private/tmp/kivy-ios/tmp/libxml2-2.7.8
    running build_ext
    failed to import Cython: dynamic module does not define init function (initScanning)
    error: Cython does not appear to be installed

**Comment by tito** [comment]
New toolchain is rewriten, lxml is missing, so this issue is not here anymore
