### ISSUE TITLE
Need to reduce large ios app size

### ISSUE THREAD

**Issue by guitarical** [kivy/kivy-ios#99]
Hi, we're building an ios app using Kivy-ios. Our current app size is 397MB (as compared to 40MB for the same app deployed on android using buildozer). We need to drastically reduce the size of this app but can't figure out how to do it. Are there parts of the kivy-ios library that we could exclude to reduce the app size? If so, how would we do it? So far, we've gone one-by-one both within the tools folder of kivy-ios and within xcode's 'linked frameworks and libraries' but haven't been able to eliminate anything of substantial size while also successfully deploying the app. 

Thanks in advance

**Comment by tito** [comment]
This is unlikely to happen now. All the toolchain has been rewriten. :)
